package main

import (
	"encoding/json"
	"testing"
)

// The canned answer is generated FROM the caller's schema, so these two
// functions decide whether a real decoder on the other end sees a value it
// can read. The union and enum rules in particular have no protocol test
// that would catch them getting it wrong: a `["string","null"]` property
// answered as null decodes fine and simply erases the field, which surfaces
// three layers away as "the model returned nothing for the title".

func TestDeclaredTypePicksTheAnswerableMember(t *testing.T) {
	for _, tc := range []struct {
		name string
		node string
		want string
	}{
		{"plain string", `{"type": "string"}`, "string"},
		{"nullable string picks the non-null member", `{"type": ["string", "null"]}`, "string"},
		{"null first, still the non-null member", `{"type": ["null", "integer"]}`, "integer"},
		{"null-only union answers null", `{"type": ["null"]}`, "null"},
		{"first non-null member wins", `{"type": ["number", "string"]}`, "number"},
		{"non-string members are ignored", `{"type": [3, "null", "boolean"]}`, "boolean"},
		{"no type at all", `{"description": "untyped"}`, ""},
		{"empty union", `{"type": []}`, ""},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var node map[string]any
			if err := json.Unmarshal([]byte(tc.node), &node); err != nil {
				t.Fatal(err)
			}
			if got := declaredType(node); got != tc.want {
				t.Errorf("declaredType(%s) = %q, want %q", tc.node, got, tc.want)
			}
		})
	}
}

func TestCannedValueAnswersEachSchemaShape(t *testing.T) {
	for _, tc := range []struct {
		name string
		node string
		prop string
		want any
	}{
		// An enum short-circuits before the type is consulted, because the
		// declared type of an enum property is satisfied by its members and
		// a generic value of that type usually is not.
		{"enum wins over type", `{"type": "string", "enum": ["fix", "feat"]}`, "kind", "fix"},
		{"enum of non-strings", `{"type": "integer", "enum": [7, 8]}`, "count", float64(7)},
		{"empty enum falls through to the type", `{"type": "string", "enum": []}`, "title", "Mock provider thread title"},
		// A nullable string is answered with TEXT: a bare null would erase
		// the field for a caller that reads it as a value.
		{"nullable string", `{"type": ["string", "null"]}`, "body",
			"Generated by ao-mockprovider for the agent test harness."},
		{"null-only union", `{"type": ["null"]}`, "nothing", nil},
		{"unknown field names itself", `{"type": "string"}`, "reviewer", "mock reviewer"},
		{"integer", `{"type": "integer"}`, "count", 0},
		{"number", `{"type": "number"}`, "score", 0},
		{"boolean", `{"type": "boolean"}`, "urgent", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var node map[string]any
			if err := json.Unmarshal([]byte(tc.node), &node); err != nil {
				t.Fatal(err)
			}
			got, err := cannedValue(node, tc.prop)
			if err != nil {
				t.Fatalf("cannedValue(%s) = %v", tc.node, err)
			}
			if got != tc.want {
				t.Errorf("cannedValue(%s, %q) = %#v, want %#v", tc.node, tc.prop, got, tc.want)
			}
		})
	}
}

func TestCannedValueBuildsNestedShapes(t *testing.T) {
	var node map[string]any
	// A nullable array of nullable-string objects: every union in this
	// schema has to resolve to its answerable member for the result to be
	// readable at all.
	if err := json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"subject": {"type": ["string", "null"]},
			"files": {
				"type": "array",
				"items": {"type": "object", "properties": {"path": {"type": "string"}}}
			}
		}
	}`), &node); err != nil {
		t.Fatal(err)
	}
	value, err := cannedValue(node, "")
	if err != nil {
		t.Fatal(err)
	}
	out, ok := value.(map[string]any)
	if !ok {
		t.Fatalf("value = %#v, want an object", value)
	}
	if out["subject"] != "chore: mock provider commit subject" {
		t.Errorf("subject = %#v", out["subject"])
	}
	// One element, not none: `minItems: 1` is legal in the vocabulary and
	// an empty array would fail it.
	files, ok := out["files"].([]any)
	if !ok || len(files) != 1 {
		t.Fatalf("files = %#v, want one element", out["files"])
	}
	entry, ok := files[0].(map[string]any)
	if !ok || entry["path"] != "mock path" {
		t.Errorf("files[0] = %#v", files[0])
	}
}

// A schema this generator cannot answer must be an error naming the
// property, not a silent empty answer: the caller reports the latter as
// "the model returned nothing", far from the schema that caused it.
func TestCannedValueRefusesWhatItCannotAnswer(t *testing.T) {
	for _, node := range []string{
		`{"description": "no type here"}`,
		`{"type": "integer-ish"}`,
		`{"type": ["null", "integer-ish"]}`,
	} {
		var decoded map[string]any
		if err := json.Unmarshal([]byte(node), &decoded); err != nil {
			t.Fatal(err)
		}
		if _, err := cannedValue(decoded, "mystery"); err == nil {
			t.Errorf("cannedValue(%s) was answered", node)
		}
	}
}
