// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Diagnostic,
    DiagnosticBatch,
    DiagnosticSeverity
} from "./models.js";
