// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Attached is one attached machine as the desktop's own admin surface
 * sees it. Richer than the manifest row, which a page needs only to open
 * sockets with.
 */
export class Attached {
    /**
     * ID is this installation's name for the profile, and the id in every
     * carried route. Today it is the backend id — deviceclient files one
     * session per backend id — but the two are kept apart because one is
     * an address on this listener and the other is a machine's identity.
     */
    "id": string;

    /**
     * BackendID is what that machine called itself when this device
     * paired with it, and what a client keys its replica by.
     */
    "backendId": string;

    /**
     * Name is what to show: the owner's nickname, else the machine's own
     * name, else its address.
     */
    "name": string;

    /**
     * Nickname is what the owner typed, empty when they have not.
     */
    "nickname"?: string;

    /**
     * Endpoint is the address this device pinned, in the spelling the
     * pairing link used.
     */
    "endpoint": string;

    /**
     * LastReachedMs is when this machine last answered this process, Unix
     * milliseconds, zero for "not since this launch".
     * 
     * Last-known and nothing more. Nothing here probes: waking every
     * attached laptop to answer one page load would make a boot as slow
     * as the slowest of them, and a page's own socket is the only current
     * answer anyway.
     */
    "lastReachedMs"?: number;
    "deviceNameSyncError"?: string;

    /** Creates a new Attached instance. */
    constructor($$source: Partial<Attached> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("backendId" in $$source)) {
            this["backendId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attached instance from a string or object.
     */
    static createFrom($$source: any = {}): Attached {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attached($$parsedSource as Partial<Attached>);
    }
}

/**
 * Attachment is what an attach attempt answers immediately: the pairing
 * is real and the credential is stored, and it admits NOTHING until the
 * owner of that machine matches VerificationNumber on their own screen.
 */
export class Attachment {
    "id": string;
    "name": string;
    "endpoint": string;
    "verificationNumber": string;

    /** Creates a new Attachment instance. */
    constructor($$source: Partial<Attachment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("verificationNumber" in $$source)) {
            this["verificationNumber"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     */
    static createFrom($$source: any = {}): Attachment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment($$parsedSource as Partial<Attachment>);
    }
}
