// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as highlight$0 from "../highlight/models.js";

/**
 * Stateless highlighting is shared by execution-host and frontend-only RPC
 * receivers. One wire shape keeps both compatible with the same SPA bundle.
 */
export class CodeRequest {
    "lang": string;
    "source": string;

    /** Creates a new CodeRequest instance. */
    constructor($$source: Partial<CodeRequest> = {}) {
        if (!("lang" in $$source)) {
            this["lang"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CodeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CodeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CodeRequest($$parsedSource as Partial<CodeRequest>);
    }
}

export class PatchRequest {
    "path": string;
    "patch": string;

    /** Creates a new PatchRequest instance. */
    constructor($$source: Partial<PatchRequest> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("patch" in $$source)) {
            this["patch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PatchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PatchRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PatchRequest($$parsedSource as Partial<PatchRequest>);
    }
}

export class Result {
    "lang": string;
    "lines": highlight$0.EncodedLine[];
    "truncated": boolean;
    "incomplete": boolean;

    /**
     * Primed marks a contextual cache upgrade; consumers must not replace it
     * with a later stateless result for the same content.
     */
    "primed"?: boolean;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("lang" in $$source)) {
            this["lang"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("incomplete" in $$source)) {
            this["incomplete"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField1_0($$parsedSource["lines"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = highlight$0.EncodedLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
