// A 300x200 truecolour PNG of two flat bands: past the thumbnail cap in
// both axes, and still 494 bytes because flat bands deflate to nothing.
export const PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAASwAAADICAIAAADdvUsCAAABtUlEQVR42u3TAQkAAAjAMLOYxXCGM5QxRBgsweGRPc' +
  'ChkABMCCYETAgmBEwIJgRMCCYETAgmBEwIJgRMCCYETAgmBEwIJgRMCCYETAgmBEwIJgRMCCYETAgmBEwIJgRMCCYE' +
  'TAgmBEwIJgRMCCYETAgmBEwIJgRMCCYETAgmBEwIJgRMCCYETAgmBEwIJgRMCCYETAgmBEwIJgRMCCYETAgmBBOqAC' +
  'YEEwImBBMCJgQTAiYEEwImBBMCJgQTAiYEEwImBBMCJgQTAiYEEwImBBMCJgQTAiYEEwImBBMCJgQTAiYEEwImhNcT' +
  'TiVwyIRgQjAhYEIwIWBCMCFgQjAhYEIwIWBCMCFgQjAhYEIwIWBCMCFgQjAhYEIwIWBCMCFgQjAhYEIwIWBCMCFgQj' +
  'AhYEIwIWBCMCFgQjAhYEIwIWBCMCFgQjAhYEIwIWBCMCFgQjAhYEIwIWBCMCFgQjAhYEIwIWBCMCFgQjAhYEIwIZhQ' +
  'AjAhmBAwIZgQMCGYEDAhmBAwIZgQMCGYEDAhmBAwIZgQMCGYEDAhmBAwIZgQMCGYEDAhmBAwIZgQMCGYEDAhmBAwIb' +
  'y2ay5ZumneNVwAAAAASUVORK5CYII=';
export const PNG_BYTES = Buffer.from(PNG_BASE64, 'base64');
export const PNG_WIDTH = 300;
export const PNG_HEIGHT = 200;
