// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Accelerator is one chord as a native key event reports it: the DOM
 * `KeyboardEvent.key` spelling of the key (lowercase; " " for space) plus the
 * four modifier states, with `mod` already resolved to the platform's key.
 * 
 * It exists for the embedded browser. A chord pressed while a page's NATIVE
 * view holds keyboard focus never reaches the SPA's keydown dispatcher, so the
 * engine asks — synchronously, on the UI thread — whether AO binds that chord
 * before letting the page have it. Matching happens here, on the Go side of
 * the wire, because the answer has to be given before the event is released.
 */
export class Accelerator {
    "key": string;
    "ctrl"?: boolean;
    "meta"?: boolean;
    "alt"?: boolean;
    "shift"?: boolean;

    /** Creates a new Accelerator instance. */
    constructor($$source: Partial<Accelerator> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Accelerator instance from a string or object.
     */
    static createFrom($$source: any = {}): Accelerator {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Accelerator($$parsedSource as Partial<Accelerator>);
    }
}

/**
 * Keybinding is the on-disk / over-the-wire shape of a single
 * keybinding. `When` is an optional VS Code-style context expression
 * (e.g. "!terminalFocus" or "terminalOpen && !approvalPending").
 * `DefaultID` identifies the shipped default row that a user entry
 * overrides, so multiple default chords can target the same command
 * under the same context and still be rebound independently.
 * `DefaultKey` is retained as a legacy fallback for configs written
 * before stable IDs existed. The frontend validates key and when
 * syntax; the backend persists the strings verbatim after checking
 * required fields are present.
 */
export class Keybinding {
    "key": string;
    "command": string;
    "when"?: string;
    "defaultId"?: string;
    "defaultKey"?: string;

    /** Creates a new Keybinding instance. */
    constructor($$source: Partial<Keybinding> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Keybinding instance from a string or object.
     */
    static createFrom($$source: any = {}): Keybinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Keybinding($$parsedSource as Partial<Keybinding>);
    }
}

/**
 * LoadResult is everything Get has to say: the effective bindings and,
 * when the user's override file existed but could not be read, why.
 * 
 * Deliberately one value instead of a ([]Keybinding, error) pair. Both
 * halves are non-nil together in the failure case — the bindings are
 * always usable (Defaults, plus whatever was readable) and the error
 * only reports that the user file was not — and a pair in that shape
 * invites the reflexive `if err != nil { return }` that throws a
 * perfectly good binding list away. Here the failure IS data: it
 * travels to the frontend beside the bindings and renders as
 * user-facing state instead of being dropped on the floor.
 */
export class LoadResult {
    "bindings": Keybinding[];
    "loadError"?: string;

    /** Creates a new LoadResult instance. */
    constructor($$source: Partial<LoadResult> = {}) {
        if (!("bindings" in $$source)) {
            this["bindings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bindings" in $$parsedSource) {
            $$parsedSource["bindings"] = $$createField0_0($$parsedSource["bindings"]);
        }
        return new LoadResult($$parsedSource as Partial<LoadResult>);
    }
}

// Private type creation functions
const $$createType0 = Keybinding.createFrom;
const $$createType1 = $Create.Array($$createType0);
