// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry is one row inside a Listing. IsRepo is only populated for
 * directory entries; files always report IsRepo=false regardless of
 * name.
 */
export class Entry {
    /**
     * basename, no trailing separator
     */
    "name": string;

    /**
     * resolved via stat (symlinks reflect target type)
     */
    "isDir": boolean;

    /**
     * name begins with "."
     */
    "hidden": boolean;

    /**
     * directory contains ".git" (dir OR file); false for non-dirs
     */
    "isRepo": boolean;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("hidden" in $$source)) {
            this["hidden"] = false;
        }
        if (!("isRepo" in $$source)) {
            this["isRepo"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

/**
 * Listing is the structured result of a Browse call.
 * 
 * Exists = false is used for two overlapping "nothing to list" cases
 * the UI treats the same: the path doesn't exist on disk, or it points
 * at a file rather than a directory. Those cases don't return an error
 * — the AddProject modal calls this on every keystroke of a typed path,
 * and logging each in-progress keystroke as a server error produces a
 * flood of spurious ERR lines. True failures (permission denied, I/O
 * errors, bad home-dir lookup) still surface as errors.
 */
export class Listing {
    /**
     * cleaned absolute path of the listed directory
     */
    "path": string;

    /**
     * parent dir, or "" when at the filesystem root
     */
    "parent": string;

    /**
     * "/" on unix, "\\" on windows
     */
    "separator": string;
    "entries": Entry[];

    /**
     * true when entry count exceeded EntryLimit
     */
    "truncated": boolean;

    /**
     * false = path missing OR not a directory (empty Entries)
     */
    "exists": boolean;

    /** Creates a new Listing instance. */
    constructor($$source: Partial<Listing> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("parent" in $$source)) {
            this["parent"] = "";
        }
        if (!("separator" in $$source)) {
            this["separator"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Listing instance from a string or object.
     */
    static createFrom($$source: any = {}): Listing {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        return new Listing($$parsedSource as Partial<Listing>);
    }
}

// Private type creation functions
const $$createType0 = Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
