// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Status mirrors the wire-level state both providers report for MCP
 * connections, plus the AO-side "haven't probed yet" pseudo-state.
 * String values match the JSON the bindings expose to the frontend.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusUnknown = "unknown",
    StatusReady = "ready",
    StatusNeedsAuth = "needs-auth",
    StatusFailed = "failed",
};
