// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * File is the compact per-file summary persisted with checkpoint rows.
 */
export class File {
    "path": string;
    "kind": string;
    "additions": number;
    "deletions": number;

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("additions" in $$source)) {
            this["additions"] = 0;
        }
        if (!("deletions" in $$source)) {
            this["deletions"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new File($$parsedSource as Partial<File>);
    }
}
