package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

// The fixtures the bench workloads run against, built as HarnessSeed specs.
// They are deliberately small on the streaming workloads (the load under
// test arrives on the wire, and a pre-loaded history would put a different
// timeline on screen every time the seed changed) and deliberately large on
// many-threads, where the fixture IS the workload.

// benchProjectRepo is the same throwaway repository every bench seeds: one
// commit, enough files that a path reference in a tool result resolves.
func benchProjectRepo() map[string]any {
	return map[string]any{
		"commits": []map[string]any{{
			"message": "bench fixture",
			"files": map[string]string{
				"README.md":  "# bench workspace\nGenerated by the bench runner.\n",
				"pkg/doc.go": "// Package pkg is bench fixture content.\npackage pkg\n",
			},
		}},
	}
}

func seedSingleThread(run *benchRun) (json.RawMessage, error) {
	spec := map[string]any{
		"projects": []map[string]any{{
			"name": "bench-" + run.workload.Name,
			"repo": benchProjectRepo(),
			"threads": []map[string]any{{
				"title":    "bench " + run.workload.Name,
				"provider": "claude",
				// One completed turn, because App.ListThreads hides a thread
				// with no items: without it the row the bench is about to
				// open would not exist in the sidebar at all.
				"turns": []map[string]any{{
					"userText": "warm up the bench thread",
					"items": []map[string]any{{
						"kind":    "assistant_text",
						"summary": "Ready for the bench workload.",
					}},
				}},
			}},
		}},
	}
	return json.Marshal(spec)
}

// benchMultiPaneCount is how many panes stream at once. Three is what a
// wide monitor actually holds side by side, and it is past the point where
// the panes stop being independent: one main thread, one style and layout
// pass, one frame budget shared between them.
const benchMultiPaneCount = 3

// seedMultiPaneThreads is seedSingleThread widened. Same deliberately thin
// history for the same reason — the load under test arrives on the wire —
// but one thread per pane, each with the one completed turn App.ListThreads
// needs to show a row at all.
func seedMultiPaneThreads(run *benchRun) (json.RawMessage, error) {
	threads := make([]map[string]any, 0, benchMultiPaneCount)
	for i := 1; i <= benchMultiPaneCount; i++ {
		threads = append(threads, map[string]any{
			"title":    fmt.Sprintf("bench pane %02d", i),
			"provider": "claude",
			"turns": []map[string]any{{
				"userText": fmt.Sprintf("warm up bench pane %02d", i),
				"items": []map[string]any{{
					"kind":    "assistant_text",
					"summary": "Ready for the bench workload.",
				}},
			}},
		})
	}
	spec := map[string]any{
		"projects": []map[string]any{{
			"name":    "bench-" + run.workload.Name,
			"repo":    benchProjectRepo(),
			"threads": threads,
		}},
	}
	return json.Marshal(spec)
}

// benchManyThreadsCount is how wide the sidebar gets. Thirty is past the
// point where the list virtualizes and past what a reader can hold on one
// screen, which is the regime the workload is about.
const benchManyThreadsCount = 30

// benchManyThreadsTurns is the history each thread carries. Every switch
// pays a bounded-window load out of SQLite, so the per-thread depth is
// what decides whether a switch is cheap or not.
const benchManyThreadsTurns = 4

func seedManyThreads(run *benchRun) (json.RawMessage, error) {
	threads := make([]map[string]any, 0, benchManyThreadsCount)
	for i := 1; i <= benchManyThreadsCount; i++ {
		threads = append(threads, map[string]any{
			"title":    fmt.Sprintf("bench thread %02d", i),
			"provider": "claude",
			"turns":    benchThreadTurns(i),
		})
	}
	spec := map[string]any{
		"projects": []map[string]any{{
			"name":    "bench-many-threads",
			"repo":    benchProjectRepo(),
			"threads": threads,
		}},
	}
	return json.Marshal(spec)
}

func benchThreadTurns(thread int) []map[string]any {
	turns := make([]map[string]any, 0, benchManyThreadsTurns)
	for turn := 1; turn <= benchManyThreadsTurns; turn++ {
		turns = append(turns, map[string]any{
			"userText": fmt.Sprintf("thread %02d, question %d: what changed here?", thread, turn),
			"items": []map[string]any{
				{
					"kind":    "assistant_text",
					"summary": benchAnswerText(thread, turn),
				},
				{
					"kind":     "tool_call",
					"toolName": "Read",
					"summary":  fmt.Sprintf("Read pkg/doc.go (thread %02d turn %d)", thread, turn),
				},
				{
					"kind":     "tool_call",
					"toolName": "Bash",
					"summary":  fmt.Sprintf("rg -n TODO pkg  (thread %02d turn %d)", thread, turn),
					// The payload is the on-demand half: a switch must not
					// load it, which is exactly what this workload watches.
					"payload": map[string]any{
						"kind": "command_output",
						"data": strings.Repeat("pkg/doc.go:1: // Package pkg is bench fixture content.\n", 40),
					},
				},
			},
		})
	}
	return turns
}

func benchAnswerText(thread, turn int) string {
	return fmt.Sprintf(
		"Thread %02d, answer %d. The fixture repository carries one commit and two files, "+
			"so the diff surface is stable across every seeded thread and any difference a "+
			"switch storm measures comes from the switch rather than from the content.",
		thread, turn)
}
