package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// command descriptors are deliberately small. The executable remains the
// source of flag parsing, while this tree owns names and summaries shared by
// top-level help, group help, and the checked-in reference page.
func commandDescriptor(name, summary string) command {
	return command{name: name, summary: summary}
}

func scenarioCommandDescriptors() []command {
	return []command{
		commandDescriptor("set", "install a mock scenario rule"),
		commandDescriptor("list", "list active rules and the built-in library"),
		commandDescriptor("show", "show one built-in scenario"),
		commandDescriptor("clear", "remove active scenario rules"),
		commandDescriptor("validate", "validate scenario files or library names offline"),
		commandDescriptor("from-thread", "rebuild recorded turns as a scenario"),
	}
}

func mockCommandDescriptors() []command {
	return []command{
		commandDescriptor("list", "list registered mock providers"),
		commandDescriptor("advance", "release a mock waitSignal gate"),
		commandDescriptor("emit", "send a raw wire line to a mock"),
		commandDescriptor("exit", "stop a mock provider"),
	}
}

func eventsCommandDescriptors() []command {
	return []command{
		commandDescriptor("tail", "stream matching events"),
		commandDescriptor("await", "wait for one matching event"),
		commandDescriptor("count", "count retained matching events"),
		commandDescriptor("channels", "list registered event channels"),
	}
}

func recordCommandDescriptors() []command {
	return []command{
		commandDescriptor("start", "start a replay bundle capture"),
		commandDescriptor("stop", "stop the active replay bundle capture"),
	}
}

func replayCommandDescriptors() []command {
	return []command{
		commandDescriptor("bundle", "replay a recorded bundle"),
		commandDescriptor("file", "replay an event-log file"),
		commandDescriptor("pause", "pause replay"),
		commandDescriptor("resume", "resume replay"),
		commandDescriptor("step", "release one paused event"),
		commandDescriptor("stop", "stop replay"),
		commandDescriptor("status", "show replay status"),
	}
}

func uiCommandDescriptors() []command {
	return []command{
		commandDescriptor("snapshot", "capture a semantic viewport snapshot"),
		commandDescriptor("query", "query matching DOM elements"),
		commandDescriptor("state", "read one whitelisted frontend global"),
		commandDescriptor("diff", "compare the current viewport to the saved snapshot"),
		commandDescriptor("reload", "reload the attached page"),
		commandDescriptor("open", "open a thread in the attached page"),
	}
}

func perfCommandDescriptors() []command {
	return []command{
		commandDescriptor("start", "arm frontend and backend performance meters"),
		commandDescriptor("stop", "stop meters and print the report"),
		commandDescriptor("status", "show the active meter run"),
		commandDescriptor("watch", "stream one line per performance sample"),
	}
}

func monitorCommandDescriptors() []command {
	return []command{
		commandDescriptor("list", "list typed app-feel monitor specifications"),
		commandDescriptor("start", "start one or more typed app-feel monitors"),
		commandDescriptor("heartbeat", "record a heartbeat for a monitor run"),
		commandDescriptor("overlap", "record overlap between two live monitor runs"),
		commandDescriptor("status", "collect the current state of a live monitor run"),
		commandDescriptor("collect", "collect observations from a live monitor run"),
		commandDescriptor("stop", "stop one monitor run and retain its result"),
		commandDescriptor("cleanup", "safely stop one monitor run during teardown"),
		commandDescriptor("last", "read retained stopped monitor results"),
	}
}

func compareCommandDescriptors() []command {
	return []command{
		commandDescriptor("prepare", "create a portable comparison capsule"),
		commandDescriptor("run", "run disposable A/B comparison legs"),
	}
}

func artifactsCommandDescriptors() []command {
	return []command{
		commandDescriptor("list", "list retained failed-run artifacts"),
		commandDescriptor("pin", "protect one retained run from cleanup"),
		commandDescriptor("unpin", "allow one retained run to be cleaned"),
		commandDescriptor("clean", "remove oldest eligible runs over the quota"),
	}
}

func commandByName(name string) (command, bool) {
	for _, c := range commands() {
		if c.name == name {
			return c, true
		}
	}
	return command{}, false
}

func commandNames(children []command) []string {
	names := make([]string, 0, len(children))
	for _, child := range children {
		names = append(names, child.name)
	}
	return names
}

// referenceDoc is generated by `go generate ./cmd/ao-harness`. Keep the
// command list in the generated file so a release review can detect a stale
// manual page without running an instance.
func referenceDoc() string {
	var b strings.Builder
	b.WriteString("# ao-harness\n\n")
	b.WriteString("Shell driver for an isolated Agent Overflow harness instance.\n\n")
	b.WriteString("Generated from `cmd/ao-harness` command descriptors. Run `go generate ./cmd/ao-harness` after changing the command tree.\n\n")
	b.WriteString("## Usage\n\n")
	b.WriteString("```text\nao-harness [global flags] <command> [args]\n```\n\n")
	b.WriteString("Global flags work before or after the command. `--instance` accepts a full instance id, a unique `idPrefix` (at least four hexadecimal characters), or a data root.\n\n")
	b.WriteString("| Flag | Meaning |\n| --- | --- |\n| `--instance <id|idPrefix|dataRoot>` | Select the target instance. |\n| `--registry-dir <dir>` | Override discovery state. |\n| `-o <text|json>` | Select output format. |\n| `--page-id <id>` | Select the exact attached frontend page for UI, perf, and bench commands. |\n\n")
	b.WriteString("## Commands\n\n")
	b.WriteString("| Command | Description |\n| --- | --- |\n")
	for _, c := range commands() {
		fmt.Fprintf(&b, "| `%s` | %s |\n", c.name, c.summary)
	}
	b.WriteString("\n")
	for _, c := range commands() {
		if len(c.children) == 0 {
			continue
		}
		fmt.Fprintf(&b, "### `%s` subcommands\n\n", c.name)
		fmt.Fprintf(&b, "Use `ao-harness %s <subcommand> -h` for flags.\n\n", c.name)
		b.WriteString("| Subcommand | Description |\n| --- | --- |\n")
		for _, child := range c.children {
			fmt.Fprintf(&b, "| `%s` | %s |\n", child.name, child.summary)
		}
		b.WriteString("\n")
	}
	b.WriteString("## Managed run example\n\n")
	b.WriteString("Use `run --plan` for a fresh disposable workload. The data root must be absent or empty. Paths are absolute, and `output` belongs under `<dataRoot>.artifacts/<runId>`.\n\n")
	b.WriteString("```json\n{\n  \"version\": 1,\n  \"runId\": \"burst-check\",\n  \"workload\": \"burst-stream\",\n  \"dataRoot\": \"/tmp/ao-burst-check\",\n  \"instance\": \"/tmp/ao-burst-check\",\n  \"adapter\": \"bench\",\n  \"ownership\": \"fresh\",\n  \"window\": true,\n  \"preserveRoot\": true,\n  \"ceiling\": { \"maxPrivateBytes\": 629145600 }\n}\n```\n\n")
	b.WriteString("```sh\nao-harness run --plan /tmp/burst-check.json\n```\n\n")
	b.WriteString("For a functional plan, set `adapter` to `functional`, provide an absolute `scenario` and an `output` under the derived artifact root. For a portable A/B run, set `adapter` to `compare` and provide an absolute capsule manifest. Use the ordinary command verbs only when deliberately selecting a borrowed harness.\n\n")
	b.WriteString("## Monitor examples\n\n")
	b.WriteString("Monitor commands require one exact attached page. With multiple pages, pass `--page-id` from `ao-harness info`; without it the command refuses to guess. Monitor results are bounded to 64 KiB by default. Use `--file <path>` or `--full` for a complete result.\n\n")
	b.WriteString("`status` is the live snapshot spelling and performs the same typed collection as `collect`; it leaves the run active. `cleanup` is an explicit stop alias for teardown and retains the result. The page bridge also stops all live runs when the page unloads, so a lost page cannot leave observers armed.\n\n")
	b.WriteString("```sh\n# Start a clean renderer monitor and retain its run id\nao-harness monitor start --monitor frame-pacing --run-id frame-check\n# Send a heartbeat, inspect without stopping, then retain the final result\nao-harness monitor heartbeat --run-id frame-check\nao-harness monitor status --run-id frame-check\nao-harness monitor cleanup --run-id frame-check --file /tmp/frame-check.json\n# Read the bounded stopped-run ring\nao-harness monitor last\n```\n\n")
	b.WriteString("`bench` operates on and resets the selected borrowed harness. Use `run --plan` for a fresh managed run. `up --soak` starts soak backend mode but does not start the Windows launcher. `up --keep-home` exposes the real home only to child processes; backend provider state remains isolated. `up` applies a hard 600 MiB memory limit by default; use `--memory-limit-bytes` to set another positive limit within host capacity.\n\n")
	b.WriteString("## Output\n\n")
	b.WriteString("Read commands emit human-readable text by default. `-o json` emits one JSON document. Streaming commands (`events tail`, `perf watch`, `health --watch`, and bench progress) use NDJSON or stderr progress so stdout stays machine-readable. Event tails default to 1,000 records on stdout. `events tail --file` captures the complete stream without an event-count cap, bounded by `--max-bytes` (64 MiB by default) or `--timeout`; a bound reached by time is reported as incomplete. Frontend query output defaults to 64 KiB and refuses larger results. Use `ui query --full` or `ui query --file <path>` for complete frontend query output. Use `events tail --full` or `events tail --file <path>` for complete event output.\n\n")
	b.WriteString("Exit codes are 0 for success, 1 for an operational refusal, 2 for invalid arguments, and 3 when a completed health or baseline gate reports bad news.\n")
	b.WriteString("\n## RPC methods\n\nThe RPC method list is instance-specific and generated by the backend. Use `ao-harness rpc --list` for the complete current list. This page intentionally does not duplicate that wire surface.\n")
	return b.String()
}

func writeReferenceDoc(path string) error {
	if path == "" {
		return fmt.Errorf("documentation output path is empty")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create documentation directory: %w", err)
	}
	return os.WriteFile(path, []byte(referenceDoc()), 0o644)
}
