// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Skill is one Claude Code skill discovered on disk. Name is the
 * invocation word (plugin skills carry the CLI's `<plugin>:<skill>`
 * qualified form); Scope records which tier contributed it.
 */
export class Skill {
    "name": string;
    "description": string;

    /**
     * "user" | "project" | "plugin"
     */
    "scope": string;

    /** Creates a new Skill instance. */
    constructor($$source: Partial<Skill> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Skill instance from a string or object.
     */
    static createFrom($$source: any = {}): Skill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Skill($$parsedSource as Partial<Skill>);
    }
}
