// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../mcp/models.js";

/**
 * Result is the projected status the binding layer hands the
 * frontend. ToolCount is best-effort: zero on transports / failures
 * where we can't or don't fetch the tool list.
 */
export class Result {
    "serverId": string;
    "status": mcp$0.Status;
    "error"?: string;
    "protocolVersion"?: string;
    "serverName"?: string;
    "toolCount": number;
    "checkedAt": number;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = mcp$0.Status.$zero;
        }
        if (!("toolCount" in $$source)) {
            this["toolCount"] = 0;
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}
