// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EngineState is both the Paused query result and the `workflow:engine-state`
 * event payload, so the live flag has exactly one wire shape.
 */
export class EngineState {
    "paused": boolean;

    /** Creates a new EngineState instance. */
    constructor($$source: Partial<EngineState> = {}) {
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineState instance from a string or object.
     */
    static createFrom($$source: any = {}): EngineState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EngineState($$parsedSource as Partial<EngineState>);
    }
}
