// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Files is the single spinner RPC's answer: where the directory is,
 * every readable sprite, and every reason a file or the directory could
 * not be fully read.
 * 
 * Warnings are DATA, not log lines: a strip the user just dropped in
 * that is missing its sidecar, oversized, or unreadable has to say so in
 * the UI, because the symptom otherwise is "my spinner silently does
 * nothing".
 */
export class Files {
    "dir": string;
    "sprites": Sprite[];
    "warnings": string[];

    /** Creates a new Files instance. */
    constructor($$source: Partial<Files> = {}) {
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("sprites" in $$source)) {
            this["sprites"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Files instance from a string or object.
     */
    static createFrom($$source: any = {}): Files {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sprites" in $$parsedSource) {
            $$parsedSource["sprites"] = $$createField1_0($$parsedSource["sprites"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new Files($$parsedSource as Partial<Files>);
    }
}

/**
 * Sprite is one custom spinner as it crosses the wire: the id both files
 * share, the sidecar manifest verbatim, and the strip's PNG bytes
 * base64-encoded.
 * 
 * Manifest is deliberately a string and not a parsed structure. Go never
 * parses it — the animation vocabulary lives in the frontend, and a
 * backend that understood it would be a second, silently-drifting
 * definition of the format (root CLAUDE.md principle 1). The frontend
 * parses, validates, and reports.
 * 
 * PNG carries the strip BASE64-ENCODED, and is a string rather than a
 * []byte for a mechanical reason: encoding/json base64-encodes a []byte
 * at runtime, but the Wails binding generator has no special case for it
 * and would emit `number[]` in TypeScript — a declared type that
 * disagrees with what the wire actually carries. Every other binary
 * payload still on the RPC wire (AttachmentThumbnail.Data, terminal
 * replay) already spells base64 out for the same reason; this follows
 * them. The payloads too large for that treatment left the wire entirely
 * in wave 6b — attachment bytes now stream over HTTP — so the rule is not
 * "base64 everything", it is "a binary payload small enough to belong in a
 * frame says so in its type".
 */
export class Sprite {
    "id": string;
    "manifest": string;
    "png": string;

    /** Creates a new Sprite instance. */
    constructor($$source: Partial<Sprite> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("manifest" in $$source)) {
            this["manifest"] = "";
        }
        if (!("png" in $$source)) {
            this["png"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sprite instance from a string or object.
     */
    static createFrom($$source: any = {}): Sprite {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Sprite($$parsedSource as Partial<Sprite>);
    }
}

// Private type creation functions
const $$createType0 = Sprite.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
