package app

import (
	"testing"

	"agent-overflow/internal/store"
	"agent-overflow/internal/triage"
)

// projectBroadcasts captures the `project:updated` frames one mutation
// produced. Mirrors captureThreadBroadcasts; the two channels carry the same
// vocabulary and the same rules, so their tests assert the same two things.
type projectBroadcasts struct {
	t      *testing.T
	events []triage.ProjectUpdateEvent
}

func captureProjectBroadcasts(t *testing.T, app *App) *projectBroadcasts {
	t.Helper()
	recorder := &projectBroadcasts{t: t}
	app.emitEventFn = func(name string, data any) {
		if name != "project:updated" {
			return
		}
		evt, ok := data.(triage.ProjectUpdateEvent)
		if !ok {
			t.Errorf("project:updated payload type = %T, want triage.ProjectUpdateEvent", data)
			return
		}
		recorder.events = append(recorder.events, evt)
	}
	return recorder
}

func (r *projectBroadcasts) reset() { r.events = nil }

// expectRow asserts exactly one frame carrying the named project's row under
// the given action, and returns it for field assertions.
func (r *projectBroadcasts) expectRow(action, projectID string) store.Project {
	r.t.Helper()
	if len(r.events) != 1 {
		r.t.Fatalf("emitted %d project:updated events, want 1: %+v", len(r.events), r.events)
	}
	evt := r.events[0]
	if evt.Action != action {
		r.t.Fatalf("action = %q, want %q", evt.Action, action)
	}
	if evt.Project == nil {
		r.t.Fatalf("action %q carried no row", action)
	}
	if evt.Project.ID != projectID {
		r.t.Fatalf("broadcast row id = %q, want %q", evt.Project.ID, projectID)
	}
	return *evt.Project
}

func (r *projectBroadcasts) expectSilence(what string) {
	r.t.Helper()
	if len(r.events) != 0 {
		r.t.Fatalf("%s emitted %d project:updated events, want 0: %+v", what, len(r.events), r.events)
	}
}

// TestProjectMutationsBroadcastTheChangedRow is the project half of state-sync
// completeness: a second attached client only ever learns about a project-row
// mutation from `project:updated`, because the RPC's return value reaches the
// client that issued it and nobody else. Every persisted mutation is exercised
// for both halves of the contract — the changed row goes out, and repeating
// the same write says nothing.
func TestProjectMutationsBroadcastTheChangedRow(t *testing.T) {
	t.Run("create is listed and carries the generated slug", func(t *testing.T) {
		app := newTestAppWithStore(t)
		broadcasts := captureProjectBroadcasts(t, app)

		created, err := app.CreateProject(t.TempDir())
		if err != nil {
			t.Fatalf("CreateProject: %v", err)
		}
		row := broadcasts.expectRow(triage.ProjectActionListed, created.ID)
		if row.Slug == "" {
			t.Error("broadcast row carried no slug; the slug is generated by the insert")
		}
		// The broadcast row IS the RPC's return value, which is what lets the
		// initiator apply optimistically and then take its own echo without
		// the row changing under it.
		if row != created {
			t.Errorf("broadcast row = %+v, want the RPC's return value %+v", row, created)
		}
	})

	t.Run("rename is full and a repeat says nothing", func(t *testing.T) {
		app := newTestAppWithStore(t)
		created, err := app.CreateProject(t.TempDir())
		if err != nil {
			t.Fatalf("CreateProject: %v", err)
		}
		broadcasts := captureProjectBroadcasts(t, app)

		renamed, err := app.RenameProject(created.ID, "Shiny")
		if err != nil {
			t.Fatalf("RenameProject: %v", err)
		}
		row := broadcasts.expectRow(triage.ProjectActionFull, created.ID)
		if row.Name != "Shiny" || row != renamed {
			t.Errorf("broadcast row = %+v, want the renamed row %+v", row, renamed)
		}

		broadcasts.reset()
		again, err := app.RenameProject(created.ID, "Shiny")
		if err != nil {
			t.Fatalf("repeat RenameProject: %v", err)
		}
		broadcasts.expectSilence("renaming to the name it already had")
		// A no-op still answers with the project, never a blank row: the
		// calling client applies the answer.
		if again.ID != created.ID || again.Name != "Shiny" {
			t.Errorf("no-op rename returned %+v, want the current row", again)
		}
	})

	t.Run("archive is unlisted and unarchive is listed", func(t *testing.T) {
		app := newTestAppWithStore(t)
		created, err := app.CreateProject(t.TempDir())
		if err != nil {
			t.Fatalf("CreateProject: %v", err)
		}
		broadcasts := captureProjectBroadcasts(t, app)

		if err := app.ArchiveProject(created.ID); err != nil {
			t.Fatalf("ArchiveProject: %v", err)
		}
		if row := broadcasts.expectRow(triage.ProjectActionUnlisted, created.ID); !row.Archived {
			t.Error("unlisted frame carried Archived=false")
		}

		broadcasts.reset()
		if err := app.ArchiveProject(created.ID); err != nil {
			t.Fatalf("repeat ArchiveProject: %v", err)
		}
		broadcasts.expectSilence("archiving an archived project")

		broadcasts.reset()
		if _, err := app.UnarchiveProject(created.ID); err != nil {
			t.Fatalf("UnarchiveProject: %v", err)
		}
		if row := broadcasts.expectRow(triage.ProjectActionListed, created.ID); row.Archived {
			t.Error("listed frame carried Archived=true")
		}

		broadcasts.reset()
		if _, err := app.UnarchiveProject(created.ID); err != nil {
			t.Fatalf("repeat UnarchiveProject: %v", err)
		}
		broadcasts.expectSilence("unarchiving an active project")
	})

	t.Run("reorder sends one frame per row it wrote", func(t *testing.T) {
		app := newTestAppWithStore(t)
		first, err := app.CreateProject(t.TempDir())
		if err != nil {
			t.Fatalf("CreateProject(first): %v", err)
		}
		second, err := app.CreateProject(t.TempDir())
		if err != nil {
			t.Fatalf("CreateProject(second): %v", err)
		}
		broadcasts := captureProjectBroadcasts(t, app)

		if err := app.UpdateProjectSortPositions([]string{second.ID, first.ID}); err != nil {
			t.Fatalf("UpdateProjectSortPositions: %v", err)
		}
		if len(broadcasts.events) != 2 {
			t.Fatalf("emitted %d frames, want one per written row: %+v", len(broadcasts.events), broadcasts.events)
		}
		for index, evt := range broadcasts.events {
			if evt.Action != triage.ProjectActionFull || evt.Project == nil {
				t.Fatalf("frame %d = %+v, want a full frame carrying a row", index, evt)
			}
			if evt.Project.SortPosition != index {
				t.Errorf("frame %d carried sortPosition %d, want %d", index, evt.Project.SortPosition, index)
			}
		}

		// An id naming no project is skipped, not refused, and says nothing.
		broadcasts.reset()
		if err := app.UpdateProjectSortPositions([]string{"no-such-project"}); err != nil {
			t.Fatalf("UpdateProjectSortPositions(unknown): %v", err)
		}
		broadcasts.expectSilence("reordering an id that names no project")
	})

	t.Run("worktree setup is full and a repeat says nothing", func(t *testing.T) {
		app := newTestAppWithStore(t)
		created, err := app.CreateProject(t.TempDir())
		if err != nil {
			t.Fatalf("CreateProject: %v", err)
		}
		broadcasts := captureProjectBroadcasts(t, app)

		recipe := WorktreeSetupConfig{Copy: []string{".env"}}
		if _, err := app.SetProjectWorktreeSetup(created.ID, recipe); err != nil {
			t.Fatalf("SetProjectWorktreeSetup: %v", err)
		}
		broadcasts.expectRow(triage.ProjectActionFull, created.ID)

		broadcasts.reset()
		if _, err := app.SetProjectWorktreeSetup(created.ID, recipe); err != nil {
			t.Fatalf("repeat SetProjectWorktreeSetup: %v", err)
		}
		broadcasts.expectSilence("saving the recipe it already had")
	})

	t.Run("delete carries the id alone", func(t *testing.T) {
		app := newTestAppWithStore(t)
		created, err := app.CreateProject(t.TempDir())
		if err != nil {
			t.Fatalf("CreateProject: %v", err)
		}
		broadcasts := captureProjectBroadcasts(t, app)

		if _, err := app.DeleteProject(created.ID); err != nil {
			t.Fatalf("DeleteProject: %v", err)
		}
		if len(broadcasts.events) != 1 {
			t.Fatalf("emitted %d frames, want 1: %+v", len(broadcasts.events), broadcasts.events)
		}
		evt := broadcasts.events[0]
		if evt.Action != triage.ProjectActionDeleted || evt.ID != created.ID {
			t.Fatalf("frame = %+v, want a deleted frame naming %s", evt, created.ID)
		}
		// There is no row left to send, so sending one would be a lie about
		// what SQLite holds.
		if evt.Project != nil {
			t.Errorf("deleted frame carried a row: %+v", evt.Project)
		}
	})
}

// A workspace that belongs to no project yet mints one, and that is a new
// sidebar entry every attached client needs — including the one that started
// the thread, which never called CreateProject and so has nothing to apply.
func TestImplicitProjectCreationBroadcastsListed(t *testing.T) {
	app := newTestAppWithStore(t)
	broadcasts := captureProjectBroadcasts(t, app)

	workspace := t.TempDir()
	created, err := app.ensureProjectForWorkspace(workspace)
	if err != nil {
		t.Fatalf("ensureProjectForWorkspace: %v", err)
	}
	if row := broadcasts.expectRow(triage.ProjectActionListed, created.ID); row != created {
		t.Errorf("broadcast row = %+v, want %+v", row, created)
	}

	// Resolving to the project that already covers the workspace changed
	// nothing and must say nothing.
	broadcasts.reset()
	if _, err := app.ensureProjectForWorkspace(workspace); err != nil {
		t.Fatalf("repeat ensureProjectForWorkspace: %v", err)
	}
	broadcasts.expectSilence("resolving a workspace an existing project covers")
}
