package appimage

import (
	"os"
	"path"
	"slices"
	"strings"
)

// AppImage runtime markers. The type-2 AppImage runtime exports these
// four before exec'ing AppRun: APPIMAGE (the .AppImage file), APPDIR (the
// squashfs mount root, e.g. /tmp/.mount_agentXXXXXX), ARGV0 (the argv[0]
// the user invoked), and OWD (the original working directory). They
// describe how *this* process was launched; a process we spawn is not
// that process, and tooling that branches on them (or on a PATH pointing
// into a mount that disappears when the app exits) misbehaves.
const (
	envAppImage = "APPIMAGE"
	envAppDir   = "APPDIR"
	envArgv0    = "ARGV0"
	envOWD      = "OWD"
)

// markers are dropped wholesale from a child environment when the app is
// running from an AppImage.
var markers = []string{envAppImage, envAppDir, envArgv0, envOWD}

// searchPathVars are the colon-separated search paths an AppImage launch
// can have mount-local segments prepended to (AppRun hooks generated by
// linuxdeploy plugins do this — the GTK plugin prepends the mount's share
// dir to XDG_DATA_DIRS and points GSETTINGS_SCHEMA_DIR at the mount's
// schemas). Only the segments under the APPDIR mount are removed; the
// user's own entries survive in order, and a variable left with no
// segments is unset so the child falls back to the system default. Add a
// variable here if a future AppRun hook prepends to another list.
var searchPathVars = []string{"PATH", "LD_LIBRARY_PATH", "XDG_DATA_DIRS", "GSETTINGS_SCHEMA_DIR"}

// Scrub returns env with the AppImage launch artifacts removed: the four
// markers are dropped and the mount's segments are stripped out of the
// search paths, so the child resolves binaries, libraries, .desktop
// entries, and gsettings schemas against the real system instead of a
// read-only squashfs that vanishes on app exit.
//
// The scrub is gated on the markers actually being present in env, which
// is what makes it safe to apply at every spawn site: a dev, .deb, macOS,
// or Windows-hosted WSL launch carries no markers and comes back
// unchanged (the same slice, not a copy), even when one of its paths
// happens to look mount-shaped.
//
// Pure and deterministic: env is never mutated, order is preserved, and
// entries that are not KEY=VALUE pairs pass through untouched rather than
// being guessed at. Scrubbing an already-scrubbed environment is a no-op,
// since the markers that arm it are gone.
func Scrub(env []string) []string {
	scrubbed, changed := scrub(env)
	if !changed {
		return env
	}
	return scrubbed
}

// ScrubInherited returns the scrubbed form of the current process
// environment, or nil when nothing would change.
//
// The nil is the point: `cmd.Env = appimage.ScrubInherited()` scrubs an
// AppImage launch and leaves every other launch inheriting os.Environ()
// directly through exec.Cmd's own nil-Env path, so a spawn site that
// wants no other env changes does not have to grow a snapshot it would
// otherwise never take.
func ScrubInherited() []string {
	scrubbed, changed := scrub(os.Environ())
	if !changed {
		return nil
	}
	return scrubbed
}

// scrub reports whether it changed anything alongside the result, so both
// public entry points can tell "no AppImage" from "AppImage with nothing
// left to remove" without re-comparing the two slices.
func scrub(env []string) ([]string, bool) {
	rt := detect(env)
	if !rt.active {
		return env, false
	}
	out := make([]string, 0, len(env))
	changed := false
	for _, entry := range env {
		key, value, ok := strings.Cut(entry, "=")
		if !ok {
			// Not a KEY=VALUE pair; pass it through untouched rather than
			// guessing at its shape.
			out = append(out, entry)
			continue
		}
		scrubbed, keep := rt.scrubEntry(entry, key, value)
		if !keep {
			changed = true
			continue
		}
		if scrubbed != entry {
			changed = true
		}
		out = append(out, scrubbed)
	}
	return out, changed
}

// runtime is the AppImage-launch view of an environment.
type runtime struct {
	// active reports whether the environment came from an AppImage launch
	// (either marker set). Nothing is scrubbed when it is false.
	active bool
	// mount is the cleaned APPDIR path with no trailing separator, or ""
	// when APPDIR is absent or is the filesystem root. A "/" mount would
	// make every absolute path look mount-local, so it disables path
	// stripping instead of emptying the user's search paths.
	mount string
}

func detect(env []string) runtime {
	var rt runtime
	for _, entry := range env {
		key, value, ok := strings.Cut(entry, "=")
		if !ok || value == "" {
			continue
		}
		switch key {
		case envAppImage:
			rt.active = true
		case envAppDir:
			rt.active = true
			rt.mount = cleanMount(value)
		}
	}
	return rt
}

// cleanMount normalises an APPDIR value for prefix matching. Paths are
// cleaned with `path`, not `filepath`: the AppImage runtime is Linux-only
// and its mount is always a POSIX path, so the comparison must not pick
// up Windows separator rules just because this package is compiled into
// the Windows launcher binary (where it is inert — no markers).
func cleanMount(value string) string {
	cleaned := path.Clean(value)
	if cleaned == "/" {
		// The filesystem root would match every absolute segment.
		return ""
	}
	return cleaned
}

// scrubEntry maps one KEY=VALUE entry to the value a spawned child should
// see. keep=false means the variable is dropped entirely.
func (rt runtime) scrubEntry(entry, key, value string) (string, bool) {
	if slices.Contains(markers, key) {
		return "", false
	}
	if rt.mount == "" || !slices.Contains(searchPathVars, key) {
		return entry, true
	}
	kept := rt.stripMountSegments(value)
	switch kept {
	case value:
		return entry, true
	case "":
		// Every segment was mount-local. An empty value is not the same as
		// an unset one: an empty PATH has implementation-defined lookup
		// behaviour and an empty LD_LIBRARY_PATH is a pointless extra
		// loader search. Unset the variable so the child falls back to the
		// system default.
		return "", false
	}
	return key + "=" + kept, true
}

// stripMountSegments removes the segments of a colon-separated search path
// that live inside the AppImage mount, preserving the order of the rest.
func (rt runtime) stripMountSegments(list string) string {
	segments := strings.Split(list, ":")
	kept := make([]string, 0, len(segments))
	for _, segment := range segments {
		if rt.underMount(segment) {
			continue
		}
		kept = append(kept, segment)
	}
	return strings.Join(kept, ":")
}

// underMount reports whether a search-path segment resolves inside the
// AppImage mount. Matching is on path boundaries, never substrings: the
// mount root and everything beneath it match, while a sibling whose name
// merely starts with the mount path (/tmp/.mount_abc123-backup) and a path
// that contains it mid-segment (/opt/tmp/.mount_abc123/bin) do not.
func (rt runtime) underMount(segment string) bool {
	if segment == "" || rt.mount == "" {
		return false
	}
	clean := path.Clean(segment)
	return clean == rt.mount || strings.HasPrefix(clean, rt.mount+"/")
}
