// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the primary Wails-bound struct, registered as a v3 service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as design$0 from "./internal/design/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "./internal/git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "./internal/provider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveThread(id) {
    return $Call.ByID(3655608409, id);
}

/**
 * ChooseDesignOption resolves a pending design-choice request.
 * @param {string} threadID
 * @param {string} requestID
 * @param {string} optionID
 * @returns {$CancellablePromise<void>}
 */
export function ChooseDesignOption(threadID, requestID, optionID) {
    return $Call.ByID(1369097107, threadID, requestID, optionID);
}

/**
 * CreateDiscussion validates and persists a discussion definition.
 * @param {store$0.DiscussionDefinition} def
 * @returns {$CancellablePromise<void>}
 */
export function CreateDiscussion(def) {
    return $Call.ByID(757689265, def);
}

/**
 * @param {string} providerName
 * @param {string} workspacePath
 * @param {string} model
 * @param {string} interactionMode
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function CreateThread(providerName, workspacePath, model, interactionMode) {
    return $Call.ByID(2579322833, providerName, workspacePath, model, interactionMode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteDiscussion removes a persisted discussion definition.
 * @param {string} name
 * @param {string} scope
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDiscussion(name, scope) {
    return $Call.ByID(302062730, name, scope);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteThread(id) {
    return $Call.ByID(1186337974, id);
}

/**
 * @param {string} sourceThreadID
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function ForkThread(sourceThreadID) {
    return $Call.ByID(4063914461, sourceThreadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetChannelMessages returns ordered messages for a discussion channel.
 * @param {string} channelID
 * @param {number} afterSeq
 * @param {number} limit
 * @returns {$CancellablePromise<store$0.ChannelMessage[]>}
 */
export function GetChannelMessages(channelID, afterSeq, limit) {
    return $Call.ByID(3595031866, channelID, afterSeq, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetDesignArtifactHTML returns the stored HTML for an artifact.
 * @param {string} threadID
 * @param {string} artifactID
 * @returns {$CancellablePromise<string>}
 */
export function GetDesignArtifactHTML(threadID, artifactID) {
    return $Call.ByID(2043420102, threadID, artifactID);
}

/**
 * GetDiscussion returns a persisted discussion definition by name and scope.
 * @param {string} name
 * @param {string} scope
 * @returns {$CancellablePromise<store$0.DiscussionDefinition>}
 */
export function GetDiscussion(name, scope) {
    return $Call.ByID(1924583939, name, scope).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetGitStatus returns git status for the thread's active workspace.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.GitStatus>}
 */
export function GetGitStatus(threadID) {
    return $Call.ByID(4123560639, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetModelsForProvider returns the known model registry for the given provider.
 * @param {string} providerName
 * @returns {$CancellablePromise<provider$0.ModelInfo[]>}
 */
export function GetModelsForProvider(providerName) {
    return $Call.ByID(1632984917, providerName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} payloadID
 * @returns {$CancellablePromise<string>}
 */
export function GetPayloadData(payloadID) {
    return $Call.ByID(3448919335, payloadID);
}

/**
 * GetProviderStatuses reports provider binary availability using the configured paths.
 * @returns {$CancellablePromise<provider$0.ProviderStatus[]>}
 */
export function GetProviderStatuses() {
    return $Call.ByID(3829328996).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetSettings returns the current persisted settings merged over defaults.
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function GetThread(id) {
    return $Call.ByID(1098302047, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetWorkingTreeDiff returns the current combined staged and unstaged diff.
 * @param {string} threadID
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkingTreeDiff(threadID) {
    return $Call.ByID(1858968113, threadID);
}

/**
 * GitCheckout switches the workspace to an existing branch.
 * @param {string} threadID
 * @param {string} branch
 * @returns {$CancellablePromise<void>}
 */
export function GitCheckout(threadID, branch) {
    return $Call.ByID(1598126927, threadID, branch);
}

/**
 * GitCommit stages all changes and commits workspace changes.
 * WARNING: This stages everything (git add -A) before committing, including
 * untracked files. Use GitStageAll + a direct Commit call for more control.
 * @param {string} threadID
 * @param {string} subject
 * @param {string} body
 * @returns {$CancellablePromise<git$0.GitActionResult>}
 */
export function GitCommit(threadID, subject, body) {
    return $Call.ByID(1971060042, threadID, subject, body).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GitCreateBranch creates a branch in the thread's repository.
 * @param {string} threadID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function GitCreateBranch(threadID, name) {
    return $Call.ByID(2582897723, threadID, name);
}

/**
 * GitCreatePR opens a pull request for the workspace's current branch.
 * @param {string} threadID
 * @param {string} title
 * @param {string} body
 * @returns {$CancellablePromise<git$0.GitActionResult>}
 */
export function GitCreatePR(threadID, title, body) {
    return $Call.ByID(4106667105, threadID, title, body).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GitCreateWorktree creates a new worktree for the requested branch and returns its path.
 * @param {string} threadID
 * @param {string} branch
 * @returns {$CancellablePromise<string>}
 */
export function GitCreateWorktree(threadID, branch) {
    return $Call.ByID(3327650914, threadID, branch);
}

/**
 * GitListBranches lists repository branches from the thread's project root.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.GitBranch[]>}
 */
export function GitListBranches(threadID) {
    return $Call.ByID(2693102179, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GitListWorktrees lists worktrees for the thread's repository.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.Worktree[]>}
 */
export function GitListWorktrees(threadID) {
    return $Call.ByID(3232495403, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GitPull fast-forwards the workspace's current branch.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.GitActionResult>}
 */
export function GitPull(threadID) {
    return $Call.ByID(3933172764, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GitPush pushes the workspace's current branch.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.GitActionResult>}
 */
export function GitPush(threadID) {
    return $Call.ByID(4036251239, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GitRemoveWorktree removes the worktree tracked by the thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function GitRemoveWorktree(threadID) {
    return $Call.ByID(4002429606, threadID);
}

/**
 * GitStageAll runs `git add -A` in the thread's workspace, staging all changes
 * including untracked files. Use before GitCommit when explicit staging is desired.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function GitStageAll(threadID) {
    return $Call.ByID(548906954, threadID);
}

/**
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function InterruptTurn(threadID) {
    return $Call.ByID(850013031, threadID);
}

/**
 * ListDesignArtifacts returns persisted design artifacts for a thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<design$0.DesignArtifact[]>}
 */
export function ListDesignArtifacts(threadID) {
    return $Call.ByID(4255572490, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * ListDiscussions returns persisted discussion definitions for the given scope.
 * @param {string} scope
 * @returns {$CancellablePromise<store$0.DiscussionDefinition[]>}
 */
export function ListDiscussions(scope) {
    return $Call.ByID(942288562, scope).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function ListItems(threadID) {
    return $Call.ByID(2158085763, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.PayloadMeta[]>}
 */
export function ListPayloadMetas(threadID) {
    return $Call.ByID(1007133701, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @returns {$CancellablePromise<store$0.Thread[]>}
 */
export function ListThreads() {
    return $Call.ByID(1090132042).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * PostChannelMessage posts a human-authored intervention into the channel.
 * @param {string} channelID
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function PostChannelMessage(channelID, content) {
    return $Call.ByID(1315440605, channelID, content);
}

/**
 * ReconnectSession tears down the current session and starts a fresh one using
 * the thread's stored resume cursor.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function ReconnectSession(threadID) {
    return $Call.ByID(1420075138, threadID);
}

/**
 * @param {string} id
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function RenameThread(id, title) {
    return $Call.ByID(727416435, id, title);
}

/**
 * RespondToApproval forwards an interactive response to the active provider session.
 * @param {string} threadID
 * @param {provider$0.ApprovalResponse} response
 * @returns {$CancellablePromise<void>}
 */
export function RespondToApproval(threadID, response) {
    return $Call.ByID(1919237704, threadID, response);
}

/**
 * @param {string} threadID
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(threadID, content) {
    return $Call.ByID(1496882310, threadID, content);
}

/**
 * StartDiscussion creates a deliberation channel and marks the thread as operating in discussion mode.
 * @param {string} threadID
 * @param {string} discussionName
 * @returns {$CancellablePromise<void>}
 */
export function StartDiscussion(threadID, discussionName) {
    return $Call.ByID(3188309099, threadID, discussionName);
}

/**
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function StartSession(threadID) {
    return $Call.ByID(2850159713, threadID);
}

/**
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function StopSession(threadID) {
    return $Call.ByID(3838500111, threadID);
}

/**
 * SwitchThread returns the requested thread and auto-resumes its provider
 * session in the background when the thread has a stored session reference.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function SwitchThread(threadID) {
    return $Call.ByID(3897387725, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateDiscussion replaces an existing persisted discussion definition.
 * @param {string} prevName
 * @param {string} prevScope
 * @param {store$0.DiscussionDefinition} def
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDiscussion(prevName, prevScope, def) {
    return $Call.ByID(1706395020, prevName, prevScope, def);
}

/**
 * UpdateSettings applies a partial settings patch and persists it.
 * @param {{ [_ in string]?: any }} patch
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateSettings(patch) {
    return $Call.ByID(2894041249, patch).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * WriteThreadWorkspaceFile writes content to a path relative to the thread's
 * active workspace and returns the normalized relative path.
 * @param {string} threadID
 * @param {string} relativePath
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function WriteThreadWorkspaceFile(threadID, relativePath, content) {
    return $Call.ByID(3895036895, threadID, relativePath, content);
}

// Private type creation functions
const $$createType0 = store$0.Thread.createFrom;
const $$createType1 = store$0.ChannelMessage.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = store$0.DiscussionDefinition.createFrom;
const $$createType4 = git$0.GitStatus.createFrom;
const $$createType5 = provider$0.ModelInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = provider$0.ProviderStatus.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = settings$0.Settings.createFrom;
const $$createType10 = git$0.GitActionResult.createFrom;
const $$createType11 = git$0.GitBranch.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = git$0.Worktree.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = store$0.DesignArtifact.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Array($$createType3);
const $$createType18 = store$0.Item.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = store$0.PayloadMeta.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $Create.Array($$createType0);

/**
 * CloseTerminal kills the terminal's process group and removes the session.
 * @param {string} terminalID
 * @returns {$CancellablePromise<void>}
 */
export function CloseTerminal(terminalID) {
    return $Call.ByID(2702963191, terminalID);
}

/**
 * GetTerminalReplay returns the base64-encoded replay buffer for a terminal.
 * @param {string} terminalID
 * @returns {$CancellablePromise<string>}
 */
export function GetTerminalReplay(terminalID) {
    return $Call.ByID(2329592604, terminalID);
}

/**
 * ListTerminals returns a summary per active terminal for the given thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<any[]>}
 */
export function ListTerminals(threadID) {
    return $Call.ByID(2445206506, threadID);
}

/**
 * OpenTerminal starts a new PTY-backed terminal session bound to the given thread.
 * @param {string} threadID
 * @param {any} opts
 * @returns {$CancellablePromise<any>}
 */
export function OpenTerminal(threadID, opts) {
    return $Call.ByID(2247958725, threadID, opts);
}

/**
 * ResizeTerminal forwards a winsize change to the PTY.
 * @param {string} terminalID
 * @param {number} rows
 * @param {number} cols
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(terminalID, rows, cols) {
    return $Call.ByID(1887984285, terminalID, rows, cols);
}

/**
 * RestartTerminal kills the given terminal and spawns a fresh replacement
 * with the same configuration.
 * @param {string} terminalID
 * @returns {$CancellablePromise<any>}
 */
export function RestartTerminal(terminalID) {
    return $Call.ByID(4152403588, terminalID);
}

/**
 * WriteTerminal writes base64-encoded data to the given terminal.
 * @param {string} terminalID
 * @param {string} dataB64
 * @returns {$CancellablePromise<void>}
 */
export function WriteTerminal(terminalID, dataB64) {
    return $Call.ByID(146795716, terminalID, dataB64);
}

// ---- Composer enhancements (attachments, drafts, workspace files) ----

/**
 * UploadAttachment decodes base64 bytes, validates + persists them on disk,
 * and returns the new attachment metadata.
 * @param {string} threadID
 * @param {string} filename
 * @param {string} mimeType
 * @param {string} dataB64
 * @returns {$CancellablePromise<any>}
 */
export function UploadAttachment(threadID, filename, mimeType, dataB64) {
    return $Call.ByID(2485473713, threadID, filename, mimeType, dataB64);
}

/**
 * ListAttachments returns every attachment metadata row for a thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<any[]>}
 */
export function ListAttachments(threadID) {
    return $Call.ByID(1730798413, threadID);
}

/**
 * DeleteAttachment removes the metadata row and the on-disk file.
 * @param {string} attachmentID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAttachment(attachmentID) {
    return $Call.ByID(2428457759, attachmentID);
}

/**
 * GetAttachmentData returns the base64-encoded raw bytes for rendering.
 * @param {string} attachmentID
 * @returns {$CancellablePromise<string>}
 */
export function GetAttachmentData(attachmentID) {
    return $Call.ByID(71154490, attachmentID);
}

/**
 * SaveDraft persists composer state for a thread.
 * @param {string} threadID
 * @param {string} content
 * @param {string[]} attachmentIDs
 * @param {any[]} terminalChips
 * @returns {$CancellablePromise<void>}
 */
export function SaveDraft(threadID, content, attachmentIDs, terminalChips) {
    return $Call.ByID(3025273299, threadID, content, attachmentIDs, terminalChips);
}

/**
 * GetDraft returns the stored composer draft for a thread (empty if none).
 * @param {string} threadID
 * @returns {$CancellablePromise<any>}
 */
export function GetDraft(threadID) {
    return $Call.ByID(875977146, threadID);
}

/**
 * ClearDraft removes any stored composer draft for a thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function ClearDraft(threadID) {
    return $Call.ByID(296814681, threadID);
}

/**
 * SearchWorkspaceFiles returns workspace files matching the query.
 * @param {string} threadID
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<any>}
 */
export function SearchWorkspaceFiles(threadID, query, limit) {
    return $Call.ByID(3852272821, threadID, query, limit);
}

// ---- Keybindings bindings (hand-appended; FNV32a of main.App.<Method>) ----

/**
 * GetKeybindings returns the effective keybindings (defaults + user overrides).
 * @returns {$CancellablePromise<any[]>}
 */
export function GetKeybindings() {
    return $Call.ByID(3015840904);
}

/**
 * UpdateKeybindings replaces the persisted user keybindings.
 * @param {any[]} bindings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateKeybindings(bindings) {
    return $Call.ByID(3490094229, bindings);
}

/**
 * ResetKeybindings deletes the user keybindings file so defaults are restored.
 * @returns {$CancellablePromise<void>}
 */
export function ResetKeybindings() {
    return $Call.ByID(2775767393);
}

// ---- Checkpoint bindings (hand-appended; FNV32a of main.App.<Method>) ----

/**
 * GetTurnDiff returns the unified diff for a specific turn. Compares the
 * checkpoint at the start of turn N with the checkpoint at the start of
 * turn N+1, or against the current worktree when N is the latest turn.
 * @param {string} threadID
 * @param {number} turnIndex
 * @returns {$CancellablePromise<string>}
 */
export function GetTurnDiff(threadID, turnIndex) {
    return $Call.ByID(1809996571, threadID, turnIndex);
}

/**
 * GetCheckpointToWorktreeDiff returns the diff between a checkpoint ref
 * and the current worktree. Used by the three-source diff panel.
 * @param {string} threadID
 * @param {number} turnIndex
 * @returns {$CancellablePromise<string>}
 */
export function GetCheckpointToWorktreeDiff(threadID, turnIndex) {
    return $Call.ByID(3483878958, threadID, turnIndex);
}

/**
 * RevertToTurn rolls the conversation back to a prior turn's checkpoint.
 * mode="fork" creates a new thread forked at the checkpoint (safe for any
 * provider; the only safe mode for Claude). mode="restore" destructively
 * restores the workspace (Codex only). Returns the new thread ID on fork.
 * @param {string} threadID
 * @param {number} turnIndex
 * @param {string} mode
 * @returns {$CancellablePromise<string>}
 */
export function RevertToTurn(threadID, turnIndex, mode) {
    return $Call.ByID(3569172301, threadID, turnIndex, mode);
}

/**
 * ListThreadCheckpoints returns every persisted checkpoint row for a thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<any[]>}
 */
export function ListThreadCheckpoints(threadID) {
    return $Call.ByID(1853132444, threadID);
}

// ---- Thread unarchive binding (hand-appended; FNV32a of main.App.UnarchiveThread) ----

/**
 * UnarchiveThread flips archived back to false so the thread reappears in
 * the active sidebar. Returns the refreshed row.
 * @param {string} id
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UnarchiveThread(id) {
    return $Call.ByID(3655125512, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// ---- Thread interaction mode binding (hand-appended; FNV32a of main.App.SetThreadInteractionMode) ----

/**
 * SetThreadInteractionMode persists a new interaction mode for a thread and
 * returns the refreshed row. Rejects modes outside
 * default/plan/design/discussion with a clear error.
 * @param {string} threadID
 * @param {string} mode
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function SetThreadInteractionMode(threadID, mode) {
    return $Call.ByID(1283963750, threadID, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// ---- Thread-from-PR binding (hand-appended; FNV32a of main.App.CreateThreadFromPR) ----

/**
 * CreateThreadFromPR creates a new thread seeded with a GitHub PR's metadata
 * and diff as the first user message. Requires the `gh` CLI on PATH.
 * @param {string} ownerRepo
 * @param {number} number
 * @param {string} providerName
 * @param {string} model
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function CreateThreadFromPR(ownerRepo, number, providerName, model) {
    return $Call.ByID(1716017387, ownerRepo, number, providerName, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}
