// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the primary Wails-bound struct, registered as a v3 service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as design$0 from "./internal/design/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "./internal/git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as otel$0 from "./internal/observability/otel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as replay$0 from "./internal/observability/replay/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "./internal/provider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "./internal/terminal/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ArchiveProject hides the project without deleting it.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveProject(id) {
    return $Call.ByID(1352159878, id);
}

/**
 * ArchiveThread flips archived to true so the thread leaves the active sidebar.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function ArchiveThread(id) {
    return $Call.ByID(3655608409, id);
}

/**
 * BrowseDirectory lists the contents of path for the project-picker UI.
 * 
 * Normalization rules (keep the modal forgiving about input shape):
 *   - "" and "~" resolve to the user's home directory.
 *   - "~/sub" resolves to $HOME/sub.
 *   - relative paths resolve against the process CWD via filepath.Abs.
 *   - the final path is cleaned with filepath.Clean before stat.
 * 
 * Symlinks are reported via stat (target-following), NOT lstat — a
 * symlink pointing at a directory shows up as IsDir=true so the
 * frontend can descend into it like any other directory.
 * 
 * Hidden entries (leading ".") are included and flagged so the frontend
 * can style or filter them.
 * 
 * Ordering is compound: directories first (alphabetical), then files
 * (alphabetical). This matches the AddProject modal's keyboard-nav
 * expectation that arrow-down moves through folders before files.
 * 
 * Results cap at directoryEntryLimit entries; Truncated=true signals
 * the cap was hit so the UI can prompt the user to narrow the path.
 * @param {string} path
 * @returns {$CancellablePromise<$models.DirectoryListing>}
 */
export function BrowseDirectory(path) {
    return $Call.ByID(320967638, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ChooseDesignOption resolves a pending design-choice request.
 * @param {string} threadID
 * @param {string} requestID
 * @param {string} optionID
 * @returns {$CancellablePromise<void>}
 */
export function ChooseDesignOption(threadID, requestID, optionID) {
    return $Call.ByID(1369097107, threadID, requestID, optionID);
}

/**
 * ClearDraft deletes any stored draft for a thread. Missing rows are not
 * treated as an error because the caller just wants the thread to have no
 * draft.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function ClearDraft(threadID) {
    return $Call.ByID(296814681, threadID);
}

/**
 * CloseTerminal kills the terminal's process group and removes the session.
 * @param {string} terminalID
 * @returns {$CancellablePromise<void>}
 */
export function CloseTerminal(terminalID) {
    return $Call.ByID(2702963191, terminalID);
}

/**
 * CreateDiscussion validates and persists a discussion definition.
 * @param {store$0.DiscussionDefinition} def
 * @returns {$CancellablePromise<void>}
 */
export function CreateDiscussion(def) {
    return $Call.ByID(757689265, def);
}

/**
 * CreateProject validates that path exists, is a directory, and is not
 * already backing another project. Returns ErrProjectPathInUse when the
 * path already has a project row — the frontend interprets that as
 * "redirect to the existing project" rather than a failure.
 * @param {string} path
 * @returns {$CancellablePromise<store$0.Project>}
 */
export function CreateProject(path) {
    return $Call.ByID(969543070, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateThread persists a new thread rooted at a project. The options
 * struct carries every knob; any empty field except Mode is resolved via
 * settings defaults. Mode defaults to chat so every normal new thread starts
 * as a chat thread. "discussion" is rejected as a mode value because
 * discussion threads must come through StartDiscussion (which wires the
 * deliberation channel).
 * @param {$models.CreateThreadOptions} opts
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function CreateThread(opts) {
    return $Call.ByID(2579322833, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CreateThreadFromPR creates a new thread seeded with a GitHub PR's metadata +
 * diff as the first user message. Relies on the `gh` CLI being available on
 * PATH; returns a structured error with installation hint if it isn't.
 * 
 * Parameters:
 *   - ownerRepo: OWNER/REPO pair (e.g. "agent-overflow/agent-overflow")
 *   - number:    PR number
 *   - providerName + model: provider + model for the new thread
 * 
 * If the user has a local clone of the target repo registered in
 * settings.RecentWorkspaces, that path is auto-selected as the workspace.
 * Otherwise the caller is expected to pick a workspace; we still create the
 * thread but WorkspacePath is left empty and the UI can prompt.
 * @param {string} ownerRepo
 * @param {number} $number
 * @param {string} providerName
 * @param {string} model
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function CreateThreadFromPR(ownerRepo, $number, providerName, model) {
    return $Call.ByID(1716017387, ownerRepo, $number, providerName, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteAttachment removes both the metadata row and the disk file.
 * @param {string} attachmentID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAttachment(attachmentID) {
    return $Call.ByID(2428457759, attachmentID);
}

/**
 * DeleteDiscussion removes a persisted discussion definition.
 * @param {string} name
 * @param {string} scope
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDiscussion(name, scope) {
    return $Call.ByID(302062730, name, scope);
}

/**
 * DeleteProject cascades through the threads FK and returns the list of
 * thread ids that were dropped so the frontend can purge pane state.
 * @param {string} id
 * @returns {$CancellablePromise<string[]>}
 */
export function DeleteProject(id) {
    return $Call.ByID(3379369923, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeleteThread tears down the thread and any child threads. The recursive
 * cascade logic lives in app_thread_delete.go.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteThread(id) {
    return $Call.ByID(1186337974, id);
}

/**
 * ForkThread copies a source thread's timeline into a new fork and wires
 * the provider-specific resume state. The whole sequence is atomic from
 * the caller's point of view: if any step fails, the partially-created
 * fork is torn down so no half-forked rows linger.
 * 
 * The "atomic unit" is emulated in the app layer rather than a single
 * SQLite transaction because the fork flow crosses a boundary — it has
 * to talk to the Codex provider to fork a live session, which can fail
 * independently of the DB. Wrapping the whole sequence in sql.Tx would
 * hold a DB transaction open across a network-speed operation and break
 * the rest of the store's single-connection model. Instead, we compose
 * with a best-effort rollback: cleanupForkThread removes the fork row
 * (CASCADE drops cloned items + drafts), and cleanup errors are joined
 * to the primary error so the caller sees both.
 * @param {string} sourceThreadID
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function ForkThread(sourceThreadID) {
    return $Call.ByID(4063914461, sourceThreadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GenerateCommitMessage inspects the thread's working tree, stages all
 * changes, and asks the configured text-generation CLI (Codex by
 * default, Claude as an alternative) to draft a structured commit
 * subject + body. Routing mirrors t3-code's RoutingTextGeneration.
 * 
 * Errors short-circuit in four shapes the frontend can render cleanly:
 *   - unknown thread
 *   - empty staged diff ("nothing to commit")
 *   - CLI missing on PATH
 *   - CLI exited non-zero (stderr bubbled into the error)
 * 
 * The caller is expected to have the commit dialog open — it will
 * present the result (or the error) to the user for edit before
 * actually committing.
 * @param {string} threadID
 * @returns {$CancellablePromise<$models.GeneratedCommitMessage>}
 */
export function GenerateCommitMessage(threadID) {
    return $Call.ByID(1669373286, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetAttachmentData returns the base64-encoded raw bytes for rendering the
 * attachment inline in the UI. Keeping this behind RPC avoids exposing a
 * static file server.
 * @param {string} attachmentID
 * @returns {$CancellablePromise<string>}
 */
export function GetAttachmentData(attachmentID) {
    return $Call.ByID(71154490, attachmentID);
}

/**
 * GetChannelMessages returns ordered messages for a discussion channel.
 * @param {string} channelID
 * @param {number} afterSeq
 * @param {number} limit
 * @returns {$CancellablePromise<store$0.ChannelMessage[]>}
 */
export function GetChannelMessages(channelID, afterSeq, limit) {
    return $Call.ByID(3595031866, channelID, afterSeq, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetCheckpointToWorktreeDiff returns the diff between a specific checkpoint
 * ref and the current worktree. Used by the three-source diff panel.
 * @param {string} threadID
 * @param {number} turnIndex
 * @returns {$CancellablePromise<string>}
 */
export function GetCheckpointToWorktreeDiff(threadID, turnIndex) {
    return $Call.ByID(3483878958, threadID, turnIndex);
}

/**
 * GetDesignArtifactHTML returns the stored HTML for an artifact.
 * @param {string} threadID
 * @param {string} artifactID
 * @returns {$CancellablePromise<string>}
 */
export function GetDesignArtifactHTML(threadID, artifactID) {
    return $Call.ByID(2043420102, threadID, artifactID);
}

/**
 * GetDiscussion returns a persisted discussion definition by name and scope.
 * @param {string} name
 * @param {string} scope
 * @returns {$CancellablePromise<store$0.DiscussionDefinition>}
 */
export function GetDiscussion(name, scope) {
    return $Call.ByID(1924583939, name, scope).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetDraft returns the draft for a thread. Missing drafts return a zero
 * Draft (with empty arrays) rather than an error.
 * @param {string} threadID
 * @returns {$CancellablePromise<$models.Draft>}
 */
export function GetDraft(threadID) {
    return $Call.ByID(875977146, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetGitStatus returns git status for the thread's active workspace.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.GitStatus>}
 */
export function GetGitStatus(threadID) {
    return $Call.ByID(4123560639, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetKeybindings returns the effective keybindings: defaults with any
 * user overrides layered on top. Invalid entries in the user file are
 * dropped silently (the frontend surfaces parse errors on its own); a
 * completely malformed file falls back to defaults.
 * @returns {$CancellablePromise<$models.Keybinding[]>}
 */
export function GetKeybindings() {
    return $Call.ByID(3015840904).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetModelsForProvider returns the known model registry for the given provider.
 * @param {string} providerName
 * @returns {$CancellablePromise<provider$0.ModelInfo[]>}
 */
export function GetModelsForProvider(providerName) {
    return $Call.ByID(1632984917, providerName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetPayloadData returns a payload body alongside its pre-rendered
 * display HTML for the frontend. The kind-dispatched renderer runs on
 * demand here rather than persisting a column on the payloads table —
 * payload expansions are cold reads (only when the user expands) and
 * render cost is ~1 ms per 32 KB, so paying at binding time keeps the
 * data fresh on renderer upgrades and avoids a wasted streaming write.
 * @param {string} payloadID
 * @returns {$CancellablePromise<$models.PayloadContent>}
 */
export function GetPayloadData(payloadID) {
    return $Call.ByID(3448919335, payloadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} payloadID
 * @param {number} maxBytes
 * @returns {$CancellablePromise<$models.PayloadPreview>}
 */
export function GetPayloadPreview(payloadID, maxBytes) {
    return $Call.ByID(4070214921, payloadID, maxBytes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetProviderStatuses reports provider binary availability using the configured paths.
 * Also pushes a `provider:status` event per non-ready provider so thread-level
 * banners (ProviderStatusBanner) stay in sync with the settings page without
 * polling. Idempotent: re-emitting the same state is harmless — the frontend
 * keeps only the latest per-provider entry.
 * @returns {$CancellablePromise<provider$0.ProviderStatus[]>}
 */
export function GetProviderStatuses() {
    return $Call.ByID(3829328996).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetSettings returns the current persisted settings merged over defaults.
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetTerminalReplay returns the base64-encoded replay buffer. base64 keeps
 * binary safety for non-UTF-8 bytes emitted by the shell.
 * @param {string} terminalID
 * @returns {$CancellablePromise<string>}
 */
export function GetTerminalReplay(terminalID) {
    return $Call.ByID(2329592604, terminalID);
}

/**
 * GetThread returns a single thread row.
 * @param {string} id
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function GetThread(id) {
    return $Call.ByID(1098302047, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetThreadItem returns a single item by id, scoped to a thread for
 * safety so a compromised caller can't read arbitrary thread history
 * via id enumeration. Used by the frontend's scroll-to-item flow to
 * discover an out-of-window item's turn_index before loading back.
 * Returns the zero Item when no row matches — callers check ID != "".
 * @param {string} threadID
 * @param {string} itemID
 * @returns {$CancellablePromise<store$0.Item>}
 */
export function GetThreadItem(threadID, itemID) {
    return $Call.ByID(1969869112, threadID, itemID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * GetThreadRuntimeMode returns the persisted runtime mode for a thread.
 * Exposed as a convenience binding so the frontend picker doesn't have to
 * round-trip the full Thread shape.
 * @param {string} threadID
 * @returns {$CancellablePromise<string>}
 */
export function GetThreadRuntimeMode(threadID) {
    return $Call.ByID(2573491630, threadID);
}

/**
 * GetThreadSlashCommands returns the last-seen Claude slash-command list for
 * a thread. Populated from the `slash_commands` field on Claude's system.init
 * payload (see internal/provider/claude/protocol.go). Codex has no analogue
 * and returns an empty slice.
 * 
 * The binding always returns a non-nil slice so the frontend popover doesn't
 * have to null-check; an empty result means "no commands available" and the
 * UI renders a quiet empty state.
 * @param {string} threadID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetThreadSlashCommands(threadID) {
    return $Call.ByID(520969054, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTurnDiff returns the unified diff produced by a single turn.
 * 
 * Semantics:
 *   - Between the checkpoint captured at the START of turn N and the
 *     checkpoint captured at the start of turn N+1 (if one exists), or
 *   - Between the checkpoint at turn N and the current worktree if this is
 *     the most recent captured turn.
 * 
 * The frontend uses this to render "what did this turn change" diffs.
 * @param {string} threadID
 * @param {number} turnIndex
 * @returns {$CancellablePromise<string>}
 */
export function GetTurnDiff(threadID, turnIndex) {
    return $Call.ByID(1809996571, threadID, turnIndex);
}

/**
 * GetWorkingTreeDiff returns the current combined staged and unstaged diff.
 * @param {string} threadID
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkingTreeDiff(threadID) {
    return $Call.ByID(1858968113, threadID);
}

/**
 * GitCheckout switches the workspace to an existing branch.
 * @param {string} threadID
 * @param {string} branch
 * @returns {$CancellablePromise<void>}
 */
export function GitCheckout(threadID, branch) {
    return $Call.ByID(1598126927, threadID, branch);
}

/**
 * GitCommit stages all changes and commits workspace changes.
 * WARNING: This stages everything (git add -A) before committing, including
 * untracked files. Use GitStageAll + a direct Commit call for more control.
 * @param {string} threadID
 * @param {string} subject
 * @param {string} body
 * @returns {$CancellablePromise<git$0.GitActionResult>}
 */
export function GitCommit(threadID, subject, body) {
    return $Call.ByID(1971060042, threadID, subject, body).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GitCreateBranch creates a branch in the thread's repository.
 * @param {string} threadID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function GitCreateBranch(threadID, name) {
    return $Call.ByID(2582897723, threadID, name);
}

/**
 * GitCreatePR opens a pull request for the workspace's current branch. When
 * draft is true the PR is opened as a GitHub draft (gh pr create --draft).
 * @param {string} threadID
 * @param {string} title
 * @param {string} body
 * @param {boolean} draft
 * @returns {$CancellablePromise<git$0.GitActionResult>}
 */
export function GitCreatePR(threadID, title, body, draft) {
    return $Call.ByID(4106667105, threadID, title, body, draft).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GitCreateWorktree creates a new worktree for the requested branch and returns its path.
 * @param {string} threadID
 * @param {string} branch
 * @returns {$CancellablePromise<string>}
 */
export function GitCreateWorktree(threadID, branch) {
    return $Call.ByID(3327650914, threadID, branch);
}

/**
 * GitListBranches lists repository branches from the thread's project root.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.GitBranch[]>}
 */
export function GitListBranches(threadID) {
    return $Call.ByID(2693102179, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GitListWorktrees lists worktrees for the thread's repository.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.Worktree[]>}
 */
export function GitListWorktrees(threadID) {
    return $Call.ByID(3232495403, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GitPull fast-forwards the workspace's current branch.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.GitActionResult>}
 */
export function GitPull(threadID) {
    return $Call.ByID(3933172764, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GitPush pushes the workspace's current branch.
 * @param {string} threadID
 * @returns {$CancellablePromise<git$0.GitActionResult>}
 */
export function GitPush(threadID) {
    return $Call.ByID(4036251239, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GitRemoveWorktree removes the worktree tracked by the thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function GitRemoveWorktree(threadID) {
    return $Call.ByID(4002429606, threadID);
}

/**
 * GitStageAll runs `git add -A` in the thread's workspace, staging all changes
 * including untracked files. Use before GitCommit when explicit staging is desired.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function GitStageAll(threadID) {
    return $Call.ByID(548906954, threadID);
}

/**
 * HighlightMarkdown renders arbitrary markdown through the shared
 * highlighter. Surfaces that transform raw markdown before display
 * (ProposedPlanCard strips the title heading, truncates for collapsed
 * previews) can't use a pre-rendered payload HTML blob because the
 * transforms must happen at the markdown level. They call this binding
 * after applying their transforms.
 * @param {string} input
 * @returns {$CancellablePromise<string>}
 */
export function HighlightMarkdown(input) {
    return $Call.ByID(1566741474, input);
}

/**
 * InterruptTurn fires a provider-level interrupt on the thread's active
 * session. Returns an error when no session is active or the provider
 * surface isn't wired up.
 * 
 * Spec: on user interrupt, any streaming items on the current turn are
 * flipped to errored with a " — stopped" suffix, and a system `error`
 * row with Summary "Stopped by user" is appended. This happens AFTER
 * the provider interrupt signal is sent so the UI gets a consistent
 * "signal sent, now here's the record" ordering. If the triage
 * bookkeeping fails we log — the provider interrupt already fired, so
 * the session state is correct even if the timeline marker is missing.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function InterruptTurn(threadID) {
    return $Call.ByID(850013031, threadID);
}

/**
 * ListAttachments returns every attachment metadata row for a thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Attachment[]>}
 */
export function ListAttachments(threadID) {
    return $Call.ByID(1730798413, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * ListDesignArtifacts returns persisted design artifacts for a thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<design$0.DesignArtifact[]>}
 */
export function ListDesignArtifacts(threadID) {
    return $Call.ByID(4255572490, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * ListDiscussions returns persisted discussion definitions for the given scope.
 * @param {string} scope
 * @returns {$CancellablePromise<store$0.DiscussionDefinition[]>}
 */
export function ListDiscussions(scope) {
    return $Call.ByID(942288562, scope).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * ListItems returns every item persisted for a thread in chronological order.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function ListItems(threadID) {
    return $Call.ByID(2158085763, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * ListItemsBeforeTurn loads older turns on demand, strictly below
 * `beforeTurnIndex` (the frontend's current window floor). `turnLimit`
 * defaults to paginationTurns when <= 0.
 * @param {string} threadID
 * @param {number} beforeTurnIndex
 * @param {number} turnLimit
 * @returns {$CancellablePromise<store$0.PagedItems>}
 */
export function ListItemsBeforeTurn(threadID, beforeTurnIndex, turnLimit) {
    return $Call.ByID(2147361923, threadID, beforeTurnIndex, turnLimit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * ListLiveBackgroundTasks returns running background launches plus
 * recently-completed completions (within the tray retention window) so
 * the BackgroundTaskTray can render without scanning `pane.items`.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function ListLiveBackgroundTasks(threadID) {
    return $Call.ByID(320784263, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * ListPayloadMetas returns all payload metadata for a thread without the body.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.PayloadMeta[]>}
 */
export function ListPayloadMetas(threadID) {
    return $Call.ByID(1007133701, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * ListProjects returns projects with a lightweight thread count per
 * project for the sidebar.
 * @returns {$CancellablePromise<store$0.ProjectWithCounts[]>}
 */
export function ListProjects() {
    return $Call.ByID(2721360259).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * ListRecentThreadItems loads the tail of a thread's history into the
 * timeline pane: the last `turnLimit` turns (defaulting to
 * initialTurnWindow when <= 0) plus enough surrounding turns to keep
 * the total item count in [minWindowItems, maxWindowItems], plus any
 * subagent ancestors those items reference. This is the binding the
 * frontend calls on thread switch.
 * @param {string} threadID
 * @param {number} turnLimit
 * @returns {$CancellablePromise<store$0.PagedItems>}
 */
export function ListRecentThreadItems(threadID, turnLimit) {
    return $Call.ByID(2604956482, threadID, turnLimit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * ListRecentTurns returns the N most recent turn records for the given
 * thread, newest first. Used by the frontend on thread-switch to rehydrate
 * the completion divider from the latest settled turn row.
 * 
 * The frontend MUST NOT light up the working indicator from these rows —
 * an in-flight (completed_at=NULL) row from a prior session/crash is
 * historical, not live. Only a fresh `provider:turn_started` push can set
 * `pane.activeTurn`. See docs/architecture/invariants.md #22 and
 * docs/architecture/turn-lifecycle.md §Frontend state shape.
 * @param {string} threadID
 * @param {number} limit
 * @returns {$CancellablePromise<store$0.Turn[]>}
 */
export function ListRecentTurns(threadID, limit) {
    return $Call.ByID(1083162294, threadID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * ListTerminals returns a summary per active terminal for the given thread.
 * @param {string} threadID
 * @returns {$CancellablePromise<terminal$0.SessionSummary[]>}
 */
export function ListTerminals(threadID) {
    return $Call.ByID(2445206506, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * ListThreadCheckpoints returns every persisted checkpoint row for a thread.
 * Ordering is ascending by turn_index so the UI can render a turn-navigation
 * strip without additional sorting.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Checkpoint[]>}
 */
export function ListThreadCheckpoints(threadID) {
    return $Call.ByID(1853132444, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * ListThreadDiffPayloads returns every diff or tool_result item for a
 * thread so the diff panel's cumulative view can summarize the entire
 * thread independent of the timeline window.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function ListThreadDiffPayloads(threadID) {
    return $Call.ByID(2341943393, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * ListThreadProposedPlans returns every proposed-plan item for a thread,
 * newest-first. Backs PlanSidebar, which needs the full plan history
 * regardless of the timeline window.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Item[]>}
 */
export function ListThreadProposedPlans(threadID) {
    return $Call.ByID(2485050629, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * ListThreads backs the frontend sidebar. It deliberately excludes
 * "draft" threads (newly created but never sent) so the sidebar stays
 * clean: a thread only becomes visible once its first item lands.
 * Internal callers that need every thread (tests, fork inspection,
 * discussion runtime) go through a.store.ListThreads directly.
 * @returns {$CancellablePromise<store$0.Thread[]>}
 */
export function ListThreads() {
    return $Call.ByID(1090132042).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * OpenTerminal starts a new PTY-backed terminal session bound to the given
 * thread.
 * @param {string} threadID
 * @param {$models.TerminalOpenOptions} opts
 * @returns {$CancellablePromise<$models.TerminalHandle>}
 */
export function OpenTerminal(threadID, opts) {
    return $Call.ByID(2247958725, threadID, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * PostChannelMessage posts a human-authored intervention into the channel.
 * @param {string} channelID
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function PostChannelMessage(channelID, content) {
    return $Call.ByID(1315440605, channelID, content);
}

/**
 * ProbeClaudeAccount spawns a short-lived Claude CLI subprocess with
 * `--max-turns 0` and returns the authenticated account metadata from
 * the emitted `system/init` message. Results are cached per binary path
 * for 5 minutes. Zero tokens are consumed — the CLI aborts before any
 * API call.
 * 
 * On a successful probe that returns an empty AccountInfo (no
 * subscription and no token source) we also emit a `provider:status`
 * event with Status="unauthenticated" so the thread-level banner can
 * prompt the user to run `claude login`.
 * @returns {$CancellablePromise<provider$0.AccountInfo>}
 */
export function ProbeClaudeAccount() {
    return $Call.ByID(1313986574).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * ReconfigureObservability reconciles the live observability stack with the
 * current Settings snapshot. Tracing changes always require restart (we
 * don't hot-swap tracer providers — that path is too easy to break in
 * ways the user only sees when a trace goes missing). The replay toggle
 * is cheap to flip in place.
 * 
 * This is the hook the UI calls after UpdateSettings persists a change —
 * see app_settings.go.
 * @param {settings$0.Settings} prev
 * @param {settings$0.Settings} next
 * @returns {$CancellablePromise<void>}
 */
export function ReconfigureObservability(prev, next) {
    return $Call.ByID(225050321, prev, next);
}

/**
 * ReconnectSession tears down the current session and starts a fresh one using
 * the thread's stored resume cursor.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function ReconnectSession(threadID) {
    return $Call.ByID(1420075138, threadID);
}

/**
 * RenameProject updates the display name. Path is immutable.
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<store$0.Project>}
 */
export function RenameProject(id, name) {
    return $Call.ByID(3728890856, id, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RenameThread updates the thread title.
 * @param {string} id
 * @param {string} title
 * @returns {$CancellablePromise<void>}
 */
export function RenameThread(id, title) {
    return $Call.ByID(727416435, id, title);
}

/**
 * ReplayManager returns the active replay manager. May be nil before startup.
 * @returns {$CancellablePromise<replay$0.Manager | null>}
 */
export function ReplayManager() {
    return $Call.ByID(3320777729).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * ResetKeybindings deletes the user file so GetKeybindings returns defaults.
 * @returns {$CancellablePromise<void>}
 */
export function ResetKeybindings() {
    return $Call.ByID(2775767393);
}

/**
 * ResizeTerminal forwards a winsize change to the PTY.
 * @param {string} terminalID
 * @param {number} rows
 * @param {number} cols
 * @returns {$CancellablePromise<void>}
 */
export function ResizeTerminal(terminalID, rows, cols) {
    return $Call.ByID(1887984285, terminalID, rows, cols);
}

/**
 * RespondToApproval forwards an interactive response to the active provider session.
 * @param {string} threadID
 * @param {provider$0.ApprovalResponse} response
 * @returns {$CancellablePromise<void>}
 */
export function RespondToApproval(threadID, response) {
    return $Call.ByID(1919237704, threadID, response);
}

/**
 * RestartTerminal kills the given terminal and spawns a fresh replacement
 * with the same configuration.
 * @param {string} terminalID
 * @returns {$CancellablePromise<$models.TerminalHandle>}
 */
export function RestartTerminal(terminalID) {
    return $Call.ByID(4152403588, terminalID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * RevertToTurn rolls a thread back to a prior turn's captured state. The
 * checkpoint at turnIndex records the state *before* turn turnIndex ran, so
 * every revert mode drops turn turnIndex and everything after it.
 * 
 * Modes:
 *   - "fork": create a new thread forked from this one at the checkpoint,
 *     leave the source thread untouched. Returns the new thread ID.
 *   - "revert-both": in-place revert of both conversation history and
 *     working tree.
 *   - "revert-conversation": in-place revert of conversation history only
 *     (working tree untouched). Codex uses its native thread/rollback;
 *     Claude clears the session ref so the next message starts fresh.
 *   - "revert-code": restore the working tree only, leave conversation
 *     history and provider session state untouched.
 * 
 * All in-place modes stop the active session first. Fork does not touch
 * the source session.
 * @param {string} threadID
 * @param {number} turnIndex
 * @param {string} mode
 * @returns {$CancellablePromise<string>}
 */
export function RevertToTurn(threadID, turnIndex, mode) {
    return $Call.ByID(3569172301, threadID, turnIndex, mode);
}

/**
 * SaveDraft replaces the draft row for a thread.
 * @param {string} threadID
 * @param {string} content
 * @param {string[]} attachmentIDs
 * @param {$models.TerminalChip[]} terminalChips
 * @returns {$CancellablePromise<void>}
 */
export function SaveDraft(threadID, content, attachmentIDs, terminalChips) {
    return $Call.ByID(3025273299, threadID, content, attachmentIDs, terminalChips);
}

/**
 * @param {string} payloadID
 * @returns {$CancellablePromise<string>}
 */
export function SavePayloadToFile(payloadID) {
    return $Call.ByID(3576148797, payloadID);
}

/**
 * SearchThreadMessages runs a global substring search across thread titles
 * and item summaries. Intended to back the message-search overlay in the
 * frontend — kept thin so the store owns the query shape.
 * 
 * A zero or empty query short-circuits to an empty slice in the store; this
 * binding returns the same without an error so the frontend can call it on
 * every keystroke cheaply. limit caps the result set; callers should pass a
 * reasonable ceiling (50–100) for interactive UIs.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<store$0.ThreadMessageHit[]>}
 */
export function SearchThreadMessages(query, limit) {
    return $Call.ByID(3644945077, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * SearchWorkspaceFiles returns workspace files matching the query, scoped to
 * the workspace of the given thread.
 * @param {string} threadID
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.WorkspaceFileSearchResult>}
 */
export function SearchWorkspaceFiles(threadID, query, limit) {
    return $Call.ByID(3852272821, threadID, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType49($result);
    }));
}

/**
 * SendMessage is the Wails-bound entry point for user-typed content.
 * The real work lives in app_send.go.
 * @param {string} threadID
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(threadID, content) {
    return $Call.ByID(1496882310, threadID, content);
}

/**
 * SetThreadRuntimeMode is the legacy binding name preserved only while
 * the frontend migration lands (Wave 2c+). The implementation routes to
 * UpdateThreadRuntimeMode, emits the same runtime-mode-changed event,
 * and returns the older event struct.
 * 
 * The new per-field binding UpdateThreadRuntimeMode in app_threads.go
 * is the going-forward surface and returns store.Thread directly.
 * @param {string} threadID
 * @param {string} mode
 * @returns {$CancellablePromise<$models.ThreadRuntimeModeChangedEvent>}
 */
export function SetThreadRuntimeMode(threadID, mode) {
    return $Call.ByID(1115610690, threadID, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * StartDiscussion creates a deliberation channel and marks the thread as operating in discussion mode.
 * @param {string} threadID
 * @param {string} discussionName
 * @returns {$CancellablePromise<void>}
 */
export function StartDiscussion(threadID, discussionName) {
    return $Call.ByID(3188309099, threadID, discussionName);
}

/**
 * StartSession is the Wails-bound entry point for "bring this thread's
 * provider subprocess up." The sendMessage path also calls
 * startSessionNow via runSessionStart when a thread has no active
 * session yet.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function StartSession(threadID) {
    return $Call.ByID(2850159713, threadID);
}

/**
 * StopSession tears down the thread's provider session. Idempotent: a
 * thread with no active session still runs the design teardown +
 * triage cleanup so stale per-thread state doesn't leak.
 * @param {string} threadID
 * @returns {$CancellablePromise<void>}
 */
export function StopSession(threadID) {
    return $Call.ByID(3838500111, threadID);
}

/**
 * SwitchThread returns the requested thread and auto-resumes its provider
 * session in the background when the thread has a stored session reference.
 * @param {string} threadID
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function SwitchThread(threadID) {
    return $Call.ByID(3897387725, threadID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Telemetry returns the active OpenTelemetry provider. Returns nil when the
 * app has not completed ServiceStartup. Exported for tests that need to
 * inspect or replace the provider at runtime.
 * @returns {$CancellablePromise<otel$0.Provider | null>}
 */
export function Telemetry() {
    return $Call.ByID(669486408).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * UnarchiveProject reverses ArchiveProject and returns the refreshed row.
 * @param {string} id
 * @returns {$CancellablePromise<store$0.Project>}
 */
export function UnarchiveProject(id) {
    return $Call.ByID(2561521885, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * UnarchiveThread flips archived back to false so the thread reappears in the
 * active sidebar. Returns the refreshed row so the caller can re-render
 * without a follow-up GetThread round-trip.
 * @param {string} id
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UnarchiveThread(id) {
    return $Call.ByID(3655125512, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateDiscussion replaces an existing persisted discussion definition.
 * @param {string} prevName
 * @param {string} prevScope
 * @param {store$0.DiscussionDefinition} def
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDiscussion(prevName, prevScope, def) {
    return $Call.ByID(1706395020, prevName, prevScope, def);
}

/**
 * UpdateKeybindings replaces the user keybindings file with the caller's
 * config. The config is capped at maxKeybindingsCount entries; entries past
 * the cap are dropped from the tail.
 * @param {$models.Keybinding[]} bindings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateKeybindings(bindings) {
    return $Call.ByID(3490094229, bindings);
}

/**
 * UpdateSettings applies a partial settings patch and persists it. Observability
 * toggles that can flip at runtime (e.g. replay log) are reconciled here.
 * Tracing changes are persisted but require a restart to take effect — the
 * UI shows a banner when that path is taken.
 * @param {{ [_ in string]?: any }} patch
 * @returns {$CancellablePromise<settings$0.Settings>}
 */
export function UpdateSettings(patch) {
    return $Call.ByID(2894041249, patch).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * UpdateThreadBranch persists the branch column. Does NOT perform the
 * git checkout — that flow lives in GitCheckout. This binding exists
 * because the EnvPicker in the new UI needs to attach a branch string
 * to a thread without forcing a checkout.
 * @param {string} id
 * @param {string} branch
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadBranch(id, branch) {
    return $Call.ByID(2929723500, id, branch).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateThreadContextWindow persists the context window size and
 * restarts the session if one is live.
 * @param {string} id
 * @param {number} tokens
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadContextWindow(id, tokens) {
    return $Call.ByID(2456875639, id, tokens).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateThreadFastMode persists the fast-mode boolean and restarts the
 * session if one is live. Fast mode typically swaps the model to the
 * provider's small-model tier (per the per-provider translator) so a
 * running session won't pick up the change without a restart.
 * @param {string} id
 * @param {boolean} on
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadFastMode(id, on) {
    return $Call.ByID(4175109385, id, on).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateThreadMode updates the thread's mode and returns the refreshed
 * row. Rejects unknown modes with a clear error message so the frontend
 * can surface it verbatim.
 * 
 * When the thread has an active provider session at the time of the
 * change we emit a "thread:mode_changed" event with NeedsReconnect=true
 * so the frontend can prompt the user to reconnect — the running
 * session was started under the previous mode and will not pick up the
 * new one until a new session is spawned. The persisted row is always
 * updated regardless.
 * @param {string} threadID
 * @param {string} mode
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadMode(threadID, mode) {
    return $Call.ByID(3609479719, threadID, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateThreadModel changes a thread's model and restarts an active provider
 * session so the new model takes effect immediately. Threads without an active
 * session are updated in place and will use the new model on the next start.
 * @param {string} threadID
 * @param {string} model
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadModel(threadID, model) {
    return $Call.ByID(4179686417, threadID, model).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateThreadProvider persists the provider column and restarts the
 * session if one is live so the new provider takes effect.
 * @param {string} id
 * @param {string} providerName
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadProvider(id, providerName) {
    return $Call.ByID(665741969, id, providerName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateThreadReasoningEffort persists the effort tier and restarts the
 * session if one is live.
 * @param {string} id
 * @param {string} effort
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadReasoningEffort(id, effort) {
    return $Call.ByID(892204206, id, effort).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateThreadRuntimeMode persists the runtime mode and restarts the
 * session if one is live. Replaces the older SetThreadRuntimeMode
 * naming; kept as a single surface so the frontend speaks one shape.
 * @param {string} id
 * @param {string} mode
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadRuntimeMode(id, mode) {
    return $Call.ByID(325190827, id, mode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateThreadWorkspace persists a new workspace path. Used by the
 * EnvPicker to switch a thread between the project root and a worktree
 * without creating the worktree itself. Restarts the session if one is
 * live because the provider CWD is part of its launch config.
 * @param {string} id
 * @param {string} path
 * @returns {$CancellablePromise<store$0.Thread>}
 */
export function UpdateThreadWorkspace(id, path) {
    return $Call.ByID(3875142865, id, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UploadAttachment decodes base64 bytes, validates + persists them on disk,
 * and returns the new attachment metadata.
 * @param {string} threadID
 * @param {string} filename
 * @param {string} mimeType
 * @param {string} dataB64
 * @returns {$CancellablePromise<store$0.Attachment>}
 */
export function UploadAttachment(threadID, filename, mimeType, dataB64) {
    return $Call.ByID(2485473713, threadID, filename, mimeType, dataB64).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * WriteTerminal writes base64-encoded data to the given terminal. The
 * payload is base64 rather than a raw string so that non-UTF-8 byte
 * sequences (control codes, mouse events, binary heredocs) round-trip
 * losslessly from the frontend.
 * @param {string} terminalID
 * @param {string} dataB64
 * @returns {$CancellablePromise<void>}
 */
export function WriteTerminal(terminalID, dataB64) {
    return $Call.ByID(146795716, terminalID, dataB64);
}

/**
 * WriteThreadWorkspaceFile writes content to a path relative to the thread's
 * active workspace and returns the normalized relative path.
 * @param {string} threadID
 * @param {string} relativePath
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function WriteThreadWorkspaceFile(threadID, relativePath, content) {
    return $Call.ByID(3895036895, threadID, relativePath, content);
}

// Private type creation functions
const $$createType0 = $models.DirectoryListing.createFrom;
const $$createType1 = store$0.Project.createFrom;
const $$createType2 = store$0.Thread.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.GeneratedCommitMessage.createFrom;
const $$createType5 = store$0.ChannelMessage.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = store$0.DiscussionDefinition.createFrom;
const $$createType8 = $models.Draft.createFrom;
const $$createType9 = git$0.GitStatus.createFrom;
const $$createType10 = $models.Keybinding.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = provider$0.ModelInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.PayloadContent.createFrom;
const $$createType15 = $models.PayloadPreview.createFrom;
const $$createType16 = provider$0.ProviderStatus.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = settings$0.Settings.createFrom;
const $$createType19 = store$0.Item.createFrom;
const $$createType20 = git$0.GitActionResult.createFrom;
const $$createType21 = git$0.GitBranch.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = git$0.Worktree.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = store$0.Attachment.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = store$0.DesignArtifact.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $Create.Array($$createType7);
const $$createType30 = $Create.Array($$createType19);
const $$createType31 = store$0.PagedItems.createFrom;
const $$createType32 = store$0.PayloadMeta.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = store$0.ProjectWithCounts.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = store$0.Turn.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = terminal$0.SessionSummary.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = store$0.Checkpoint.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = $Create.Array($$createType2);
const $$createType43 = $models.TerminalHandle.createFrom;
const $$createType44 = provider$0.AccountInfo.createFrom;
const $$createType45 = replay$0.Manager.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = store$0.ThreadMessageHit.createFrom;
const $$createType48 = $Create.Array($$createType47);
const $$createType49 = $models.WorkspaceFileSearchResult.createFrom;
const $$createType50 = $models.ThreadRuntimeModeChangedEvent.createFrom;
const $$createType51 = otel$0.Provider.createFrom;
const $$createType52 = $Create.Nullable($$createType51);
