// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the primary Wails-bound struct, registered as a v3 service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as design$0 from "./internal/design/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "./internal/git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as otel$0 from "./internal/observability/otel/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as replay$0 from "./internal/observability/replay/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "./internal/provider/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "./internal/settings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "./internal/terminal/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wsllauncher$0 from "./internal/wsllauncher/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddRemoteEndpoint persists a new --connect target. The settings
 * service mints the ID; the operator-supplied name is optional (a
 * blank nickname renders as the URL).
 * 
 * SECURITY: returns the redacted Summary shape, not the raw stored
 * record. A LAN-attached token-holder calling AddRemoteEndpoint with
 * arbitrary inputs would otherwise see the persisted token echoed back
 * (and Update with a no-op patch would harvest the existing token
 * without writing). Forcing the return through Summary keeps both
 * paths token-free; the local UI fetches the token explicitly via
 * GetRemoteEndpointToken when the user copies the launch command.
 */
export function AddRemoteEndpoint(name: string, url: string, token: string): $CancellablePromise<$models.RemoteEndpointSummary> {
    return $Call.ByID(893963951, name, url, token).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AppendUIRenderTraceBatch appends compact dev-only UI render trace records.
 * The frontend batches calls so rendering never waits on disk. This binding
 * still validates each line because it writes directly into the user's config
 * directory.
 */
export function AppendUIRenderTraceBatch(lines: string[]): $CancellablePromise<string> {
    return $Call.ByID(2157691816, lines);
}

/**
 * ArchiveProject hides the project without deleting it.
 */
export function ArchiveProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(1352159878, id);
}

/**
 * ArchiveThread flips archived to true so the thread leaves the active sidebar.
 */
export function ArchiveThread(id: string): $CancellablePromise<void> {
    return $Call.ByID(3655608409, id);
}

/**
 * BrowseDirectory lists the contents of path for the project-picker UI.
 * 
 * Normalization rules (keep the modal forgiving about input shape):
 *   - "" and "~" resolve to the user's home directory.
 *   - "~/sub" resolves to $HOME/sub.
 *   - relative paths resolve against the process CWD via filepath.Abs.
 *   - the final path is cleaned with filepath.Clean before stat.
 * 
 * Symlinks are reported via stat (target-following), NOT lstat — a
 * symlink pointing at a directory shows up as IsDir=true so the
 * frontend can descend into it like any other directory.
 * 
 * Hidden entries (leading ".") are included and flagged so the frontend
 * can style or filter them.
 * 
 * Ordering is compound: directories first (alphabetical), then files
 * (alphabetical). This matches the AddProject modal's keyboard-nav
 * expectation that arrow-down moves through folders before files.
 * 
 * Results cap at directoryEntryLimit entries; Truncated=true signals
 * the cap was hit so the UI can prompt the user to narrow the path.
 */
export function BrowseDirectory(path: string): $CancellablePromise<$models.DirectoryListing> {
    return $Call.ByID(320967638, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ChooseDesignOption resolves a pending design-choice request.
 */
export function ChooseDesignOption(threadID: string, requestID: string, optionID: string): $CancellablePromise<void> {
    return $Call.ByID(1369097107, threadID, requestID, optionID);
}

/**
 * CleanCodexBackgroundTerminals asks the Codex app-server to terminate
 * every running unified-exec background PTY for `threadID`. This is the
 * thread-wide "Stop all" primitive for Codex — the protocol exposes no
 * per-process kill RPC for model-initiated backgrounded commands
 * (see docs/references/codex.md#known-upstream-constraints). The
 * frontend Stop-all button lands in Phase 5; this binding is the
 * plumbing it will call.
 * 
 * After the RPC succeeds, Codex emits one `item/completed` notification
 * per terminated PTY. Those update triage's transient tray state; the
 * command output becomes transcript history only if the model explicitly
 * waits/polls the terminal with write_stdin. No follow-up work is needed
 * here.
 * 
 * Returns typed errors for:
 * 
 *   - session-missing: no Codex session for this thread. The caller
 *     reached the binding before Start / after Close.
 *   - provider-mismatch: the thread exists but it's a Claude session.
 *     Claude has its own per-row stop primitive (StopClaudeTask); the
 *     frontend must branch on provider before reaching for this.
 *   - timeout / provider error: surfaced verbatim so the UI can render
 *     the CLI-supplied message.
 */
export function CleanCodexBackgroundTerminals(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(16360282, threadID);
}

/**
 * ClearDraft deletes any stored draft for a thread. Missing rows are not
 * treated as an error because the caller just wants the thread to have no
 * draft.
 */
export function ClearDraft(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(296814681, threadID);
}

/**
 * CloseTerminal kills the terminal's process group and removes the session.
 */
export function CloseTerminal(terminalID: string): $CancellablePromise<void> {
    return $Call.ByID(2702963191, terminalID);
}

/**
 * CreateDiscussion validates and persists a discussion definition.
 */
export function CreateDiscussion(def: store$0.DiscussionDefinition): $CancellablePromise<void> {
    return $Call.ByID(757689265, def);
}

/**
 * CreateProject validates that path exists, is a directory, and is not
 * already backing another project. Returns ErrProjectPathInUse when the
 * path already has a project row — the frontend interprets that as
 * "redirect to the existing project" rather than a failure.
 */
export function CreateProject(path: string): $CancellablePromise<store$0.Project> {
    return $Call.ByID(969543070, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateProposedPlanComment(threadID: string, input: store$0.ProposedPlanCommentInput): $CancellablePromise<store$0.ProposedPlanComment> {
    return $Call.ByID(4246792665, threadID, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateThread persists a new thread rooted at a project. The options
 * struct carries every knob. Empty chat-bar fields are resolved from the
 * most recently used persisted chat model profile; if no profile exists yet,
 * built-in provider defaults seed the first draft. Mode defaults to chat so
 * every normal new thread starts as a chat thread. "discussion" is rejected
 * as a mode value because discussion threads must come through
 * StartDiscussion (which wires the deliberation channel).
 */
export function CreateThread(opts: $models.CreateThreadOptions): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(2579322833, opts).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CreateThreadFromPR creates a new thread seeded with a PR/MR's metadata +
 * diff as the first user message. Routes through the appropriate forge CLI
 * (`gh` for GitHub, `glab` for GitLab) detected from the `forge` parameter.
 * 
 * Parameters:
 *   - project:       "owner/repo" for GitHub, "namespace/.../repo" for GitLab
 *   - number:        PR / MR number
 *   - providerName + model: provider + model for the new thread
 *   - forge:         "github" (default for empty) or "gitlab"
 * 
 * If the user has a local clone of the target repo registered in
 * settings.RecentWorkspaces, that path is auto-selected as the workspace.
 * Otherwise the caller is expected to pick a workspace; we still create the
 * thread but WorkspacePath is left empty and the UI can prompt.
 */
export function CreateThreadFromPR(project: string, $number: number, providerName: string, model: string, forge: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(1716017387, project, $number, providerName, model, forge).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * DeleteAttachment removes both the metadata row and the disk file.
 */
export function DeleteAttachment(attachmentID: string): $CancellablePromise<void> {
    return $Call.ByID(2428457759, attachmentID);
}

/**
 * DeleteDiscussion removes a persisted discussion definition.
 */
export function DeleteDiscussion(name: string, scope: string): $CancellablePromise<void> {
    return $Call.ByID(302062730, name, scope);
}

/**
 * DeleteProject cascades through the threads FK and returns the list of
 * thread ids that were dropped so the frontend can purge pane state.
 */
export function DeleteProject(id: string): $CancellablePromise<string[]> {
    return $Call.ByID(3379369923, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function DeleteProposedPlanComment(threadID: string, commentID: string): $CancellablePromise<void> {
    return $Call.ByID(554913120, threadID, commentID);
}

/**
 * DeleteRemoteEndpoint removes the named-by-ID record. Returns an
 * error if the ID isn't found so a stale UI gets a clear signal
 * rather than silently no-oping.
 */
export function DeleteRemoteEndpoint(id: string): $CancellablePromise<void> {
    return $Call.ByID(3667944297, id);
}

/**
 * DeleteThread tears down the thread and any child threads. The recursive
 * cascade logic lives in app_thread_delete.go.
 */
export function DeleteThread(id: string): $CancellablePromise<void> {
    return $Call.ByID(1186337974, id);
}

/**
 * ForkThread copies a source thread's timeline into a new fork and wires
 * the provider-specific resume state. The whole sequence is atomic from
 * the caller's point of view: if any step fails, the partially-created
 * fork is torn down so no half-forked rows linger.
 * 
 * When atTurnIndex is non-nil, the fork is sliced at that turn (0-indexed):
 * items with turn_index > *atTurnIndex are dropped, the provider session
 * is forked + truncated to match, and the fork's checkpoint baseline is
 * captured at checkpointTurnCount = *atTurnIndex + 1. atTurnIndex == nil
 * preserves the existing fork-at-tail behavior (clone everything, fork
 * provider state at the latest message).
 * 
 * The "atomic unit" is emulated in the app layer rather than a single
 * SQLite transaction because the fork flow crosses a boundary — it has
 * to talk to the Codex provider to fork a live session, can write a
 * new Claude session JSONL on disk, and can capture a git ref. Wrapping
 * the whole sequence in sql.Tx would hold a DB transaction open across
 * a network-speed operation and break the rest of the store's
 * single-connection model. Instead, we compose with a best-effort
 * rollback: each step that has a side-effect appends an undo to a LIFO
 * `cleanups` slice; on later failure the chain runs in reverse order
 * and any cleanup errors are joined with the primary error.
 */
export function ForkThread(sourceThreadID: string, atTurnIndex: number | null): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(4063914461, sourceThreadID, atTurnIndex).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GenerateCommitMessage inspects the thread's working tree, stages all
 * changes, and asks the configured text-generation CLI (Codex by
 * default, Claude as an alternative) to draft a structured commit
 * subject + body. Routing mirrors t3-code's RoutingTextGeneration.
 * 
 * Errors short-circuit in four shapes the frontend can render cleanly:
 *   - unknown thread
 *   - empty staged diff ("nothing to commit")
 *   - CLI missing on PATH
 *   - CLI exited non-zero (stderr bubbled into the error)
 * 
 * The caller is expected to have the commit dialog open — it will
 * present the result (or the error) to the user for edit before
 * actually committing.
 */
export function GenerateCommitMessage(threadID: string): $CancellablePromise<$models.GeneratedCommitMessage> {
    return $Call.ByID(1669373286, threadID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetAttachmentData returns the base64-encoded raw bytes for rendering a
 * thread-owned attachment inline in the UI. Keeping this behind RPC avoids
 * exposing a static file server.
 * 
 * This is the FULL-SIZE path used by the lightbox modal. Inline grid
 * rendering should call GetAttachmentThumbnail instead so we don't ship
 * 5 MB of pixels for a 128 px tile (especially over the remote
 * `--connect` transport).
 */
export function GetAttachmentData(threadID: string, attachmentID: string): $CancellablePromise<string> {
    return $Call.ByID(71154490, threadID, attachmentID);
}

/**
 * GetAttachmentThumbnail returns a small, inline-grid-sized version of the
 * attachment, generating it lazily on first call and caching the result on
 * the attachments row. ~10–30 KB per thumb vs ~1–10 MB for the original;
 * the savings matter even locally (base64 + JSON encode cost) and become
 * the difference between "instant grid" and "watch them load" over the
 * remote `--connect` transport.
 */
export function GetAttachmentThumbnail(threadID: string, attachmentID: string): $CancellablePromise<$models.AttachmentThumbnail> {
    return $Call.ByID(3414107538, threadID, attachmentID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetChannelMessages returns ordered messages for a discussion channel.
 */
export function GetChannelMessages(channelID: string, afterSeq: number, limit: number): $CancellablePromise<store$0.ChannelMessage[]> {
    return $Call.ByID(3595031866, channelID, afterSeq, limit).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetCheckpointRangeDiff returns the unified diff between two finalized
 * checkpoint turn counts. Turn count 0 is the baseline before the first turn;
 * turn count N is the workspace after completed turn N.
 */
export function GetCheckpointRangeDiff(threadID: string, fromTurnCount: number, toTurnCount: number): $CancellablePromise<string> {
    return $Call.ByID(3292511153, threadID, fromTurnCount, toTurnCount);
}

export function GetContextSettings(providerName: string, model: string): $CancellablePromise<$models.ContextSettingsProfile> {
    return $Call.ByID(3416004963, providerName, model).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetDesignArtifactHTML returns the stored HTML for an artifact.
 */
export function GetDesignArtifactHTML(threadID: string, artifactID: string): $CancellablePromise<string> {
    return $Call.ByID(2043420102, threadID, artifactID);
}

/**
 * GetDiscussion returns a persisted discussion definition by name and scope.
 */
export function GetDiscussion(name: string, scope: string): $CancellablePromise<store$0.DiscussionDefinition> {
    return $Call.ByID(1924583939, name, scope).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetDraft returns the draft for a thread. Missing drafts return a zero
 * Draft (with empty arrays) rather than an error.
 */
export function GetDraft(threadID: string): $CancellablePromise<$models.Draft> {
    return $Call.ByID(875977146, threadID).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetEditorSettings returns the user's persisted open-in-editor
 * preferences. Empty preference means the catalog default applies at
 * open time — surfaced verbatim so the settings UI can render an
 * "Auto" pill rather than guessing on the frontend.
 */
export function GetEditorSettings(): $CancellablePromise<settings$0.EditorSettings> {
    return $Call.ByID(1655853383).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetGitStatus returns git status for the thread's active workspace.
 */
export function GetGitStatus(threadID: string): $CancellablePromise<git$0.GitStatus> {
    return $Call.ByID(4123560639, threadID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetKeybindings returns the effective keybindings: defaults with any
 * user overrides layered on top. Invalid entries in the user file are
 * dropped silently (the frontend surfaces parse errors on its own); a
 * completely malformed file falls back to defaults.
 */
export function GetKeybindings(): $CancellablePromise<$models.Keybinding[]> {
    return $Call.ByID(3015840904).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetModelsForProvider returns the known model registry for the given provider.
 */
export function GetModelsForProvider(providerName: string): $CancellablePromise<provider$0.ModelInfo[]> {
    return $Call.ByID(1632984917, providerName).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetNetworkSettings returns the current persisted bind-all preference
 * plus the server-derived URL and token. The URL and token are
 * recomputed on every call so a rebind (e.g. via SetNetworkSettings)
 * reflects immediately on the next read.
 */
export function GetNetworkSettings(): $CancellablePromise<$models.NetworkSettings> {
    return $Call.ByID(1026796858).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetPayloadChunk(threadID: string, payloadID: string, offset: number, maxBytes: number): $CancellablePromise<$models.PayloadChunk> {
    return $Call.ByID(73280836, threadID, payloadID, offset, maxBytes).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * GetPayloadData returns a payload body. The caller must supply the owning
 * thread so payload ids cannot be read outside the thread timeline that
 * references them.
 */
export function GetPayloadData(threadID: string, payloadID: string): $CancellablePromise<$models.PayloadContent> {
    return $Call.ByID(3448919335, threadID, payloadID).then(($result: any) => {
        return $$createType21($result);
    });
}

export function GetPayloadPreview(threadID: string, payloadID: string, maxBytes: number): $CancellablePromise<$models.PayloadPreview> {
    return $Call.ByID(4070214921, threadID, payloadID, maxBytes).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * GetProviderStatuses reports provider binary availability using the configured paths.
 * Also pushes a `provider:status` event per non-ready provider so thread-level
 * banners (ProviderStatusBanner) stay in sync with the settings page without
 * polling. Idempotent: re-emitting the same state is harmless — the frontend
 * keeps only the latest per-provider entry.
 */
export function GetProviderStatuses(): $CancellablePromise<provider$0.ProviderStatus[]> {
    return $Call.ByID(3829328996).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * GetRemoteEndpointToken returns the token for a saved endpoint by ID.
 * Split off ListRemoteEndpoints so the bulk-read path doesn't carry
 * credentials. Used by the frontend's "Copy launch command" affordance,
 * which is an explicit user action; ListRemoteEndpoints fires on every
 * settings render and would otherwise leak tokens to any LAN-attached
 * token-holder.
 */
export function GetRemoteEndpointToken(id: string): $CancellablePromise<string> {
    return $Call.ByID(3604571249, id);
}

/**
 * GetSessionAgentDiff returns the unified diff between the thread's
 * baseline checkpoint (turn count 0) and the latest checkpoint, restricted
 * to the cumulative set of paths the agent's file-mutating tools wrote
 * across the session. Empty result when no checkpoints exist or no agent
 * writes have been recorded.
 */
export function GetSessionAgentDiff(threadID: string): $CancellablePromise<string> {
    return $Call.ByID(2631559849, threadID);
}

/**
 * GetSettings returns the current persisted settings merged over defaults.
 * 
 * SECURITY: RemoteEndpoints[*].Token is redacted to the empty string
 * before returning. A LAN-attached token-holder calling GetSettings
 * must not be able to harvest credentials for other backends — without
 * this redaction, a single GetSettings call enumerates every saved
 * token, defeating the on-demand token fetch model that
 * ListRemoteEndpoints + GetRemoteEndpointToken were designed to
 * enforce. Callers that need an actual token (the "Copy launch
 * command" affordance) fetch it through GetRemoteEndpointToken, which
 * is a logged single-record lookup.
 */
export function GetSettings(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * GetTerminalReplay returns the base64-encoded replay buffer. base64 keeps
 * binary safety for non-UTF-8 bytes emitted by the shell.
 */
export function GetTerminalReplay(terminalID: string): $CancellablePromise<string> {
    return $Call.ByID(2329592604, terminalID);
}

/**
 * GetThread returns a single thread row.
 */
export function GetThread(id: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(1098302047, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetThreadItem returns a single item by id, scoped to a thread for
 * safety so a compromised caller can't read arbitrary thread history
 * via id enumeration. Used by the frontend's scroll-to-item flow to
 * discover an out-of-window item's turn_index before loading back.
 * Returns the zero Item when no row matches — callers check ID != "".
 */
export function GetThreadItem(threadID: string, itemID: string): $CancellablePromise<store$0.Item> {
    return $Call.ByID(1969869112, threadID, itemID).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * GetThreadRuntimeMode returns the persisted runtime mode for a thread.
 * Exposed as a convenience binding so the frontend picker doesn't have to
 * round-trip the full Thread shape.
 */
export function GetThreadRuntimeMode(threadID: string): $CancellablePromise<string> {
    return $Call.ByID(2573491630, threadID);
}

/**
 * GetThreadSlashCommands returns the last-seen Claude slash-command list for
 * a thread. Populated from the `slash_commands` field on Claude's system.init
 * payload (see internal/provider/claude/protocol.go). Codex has no analogue
 * and returns an empty slice.
 * 
 * The binding always returns a non-nil slice so the frontend popover doesn't
 * have to null-check; an empty result means "no commands available" and the
 * UI renders a quiet empty state.
 */
export function GetThreadSlashCommands(threadID: string): $CancellablePromise<string[]> {
    return $Call.ByID(520969054, threadID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetUIRenderTracePath returns the dev trace file path used by
 * AppendUIRenderTraceBatch. The frontend exposes it through the console trace
 * API so a debug run can be inspected after a visual glitch.
 */
export function GetUIRenderTracePath(): $CancellablePromise<string> {
    return $Call.ByID(1009213933);
}

/**
 * GetWSLDistroPreference returns the distro the Windows launcher is
 * configured to boot into on next launch, or "" when the preference
 * isn't readable: not running under WSL, the launcher didn't inject
 * AGENT_OVERFLOW_WIN_APPDATA, or the wsl.json file doesn't exist yet.
 */
export function GetWSLDistroPreference(): $CancellablePromise<string> {
    return $Call.ByID(294719565);
}

/**
 * GetWorkingTreeDiff returns the current combined staged and unstaged diff.
 */
export function GetWorkingTreeDiff(threadID: string): $CancellablePromise<string> {
    return $Call.ByID(1858968113, threadID);
}

/**
 * GetWorkspaceCurrentDiff returns the full uncommitted diff in the
 * thread's workspace — `git diff HEAD` plus untracked-not-ignored files —
 * without filtering by tool_paths. Surfaces manual user edits alongside
 * any post-checkpoint agent activity.
 */
export function GetWorkspaceCurrentDiff(threadID: string): $CancellablePromise<string> {
    return $Call.ByID(736820142, threadID);
}

/**
 * GitCheckout switches the workspace to an existing branch.
 */
export function GitCheckout(threadID: string, branch: string): $CancellablePromise<void> {
    return $Call.ByID(1598126927, threadID, branch);
}

/**
 * GitCommit stages all changes and commits workspace changes.
 * WARNING: This stages everything (git add -A) before committing, including
 * untracked files. Use GitStageAll + a direct Commit call for more control.
 */
export function GitCommit(threadID: string, subject: string, body: string): $CancellablePromise<git$0.GitActionResult> {
    return $Call.ByID(1971060042, threadID, subject, body).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * GitCreateBranch creates a branch in the thread's repository.
 */
export function GitCreateBranch(threadID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2582897723, threadID, name);
}

/**
 * GitCreatePR opens a pull request for the workspace's current branch. When
 * draft is true the PR is opened as a GitHub draft (gh pr create --draft).
 */
export function GitCreatePR(threadID: string, title: string, body: string, draft: boolean): $CancellablePromise<git$0.GitActionResult> {
    return $Call.ByID(4106667105, threadID, title, body, draft).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * GitCreateWorktree creates a new worktree for the requested branch and returns its path.
 */
export function GitCreateWorktree(threadID: string, branch: string): $CancellablePromise<string> {
    return $Call.ByID(3327650914, threadID, branch);
}

/**
 * GitListBranches lists repository branches from the thread's project root.
 */
export function GitListBranches(threadID: string): $CancellablePromise<git$0.GitBranch[]> {
    return $Call.ByID(2693102179, threadID).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * GitListWorktrees lists worktrees for the thread's repository.
 */
export function GitListWorktrees(threadID: string): $CancellablePromise<git$0.Worktree[]> {
    return $Call.ByID(3232495403, threadID).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * GitPull fast-forwards the workspace's current branch.
 */
export function GitPull(threadID: string): $CancellablePromise<git$0.GitActionResult> {
    return $Call.ByID(3933172764, threadID).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * GitPush pushes the workspace's current branch.
 */
export function GitPush(threadID: string): $CancellablePromise<git$0.GitActionResult> {
    return $Call.ByID(4036251239, threadID).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * GitRemoveWorktree removes the worktree tracked by the thread.
 */
export function GitRemoveWorktree(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(4002429606, threadID);
}

/**
 * GitStageAll runs `git add -A` in the thread's workspace, staging all changes
 * including untracked files. Use before GitCommit when explicit staging is desired.
 */
export function GitStageAll(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(548906954, threadID);
}

/**
 * GitStatusSubscribe begins streaming git-status updates for the
 * thread's workspace. Returns the initial status synchronously so the
 * caller can render immediately, plus a subscription id used to filter
 * the "git:status" event channel and to call GitStatusUnsubscribe.
 * 
 * LocalOnly: workspace paths are local FS paths and gitwatch can spawn
 * recursive fs watches plus continuous git invocations; exposing this
 * surface to LAN peers would leak repo locations and let a token-only
 * peer enumerate threads via probe attempts.
 * 
 * The subscription is automatically released when the calling WS
 * connection drops (via transport.ConnState cleanup). The frontend
 * SHOULD still call GitStatusUnsubscribe on unmount; the
 * connection-tied cleanup is the safety net for unclean disconnects.
 */
export function GitStatusSubscribe(threadID: string): $CancellablePromise<$models.GitStatusSubscriptionResult> {
    return $Call.ByID(3282404643, threadID).then(($result: any) => {
        return $$createType32($result);
    });
}

/**
 * GitStatusUnsubscribe releases a subscription previously created via
 * GitStatusSubscribe. Idempotent — unknown ids and double-unsubscribes
 * are no-ops because the connection-cleanup safety net may have run
 * first on disconnect.
 */
export function GitStatusUnsubscribe(subscriptionID: string): $CancellablePromise<void> {
    return $Call.ByID(3263989430, subscriptionID);
}

/**
 * InterruptTurn fires a provider-level interrupt on the thread's active
 * session. Returns an error when no session is active, the provider
 * surface isn't wired up, or the provider's Interrupt call failed
 * (e.g. CLI never acked the control_request — surfaces as a toast so
 * a wedged Claude Code CLI is visible to the user rather than silently
 * masked).
 * 
 * Spec: on user interrupt, any streaming items on the current turn are
 * flipped to errored with a " — stopped" suffix, and a system `error`
 * row with Summary "Stopped by user" is appended. This happens AFTER
 * the provider interrupt signal is sent so the UI gets a consistent
 * "signal sent, now here's the record" ordering. If the triage
 * bookkeeping fails we log — the provider interrupt already fired, so
 * the session state is correct even if the timeline marker is missing.
 */
export function InterruptTurn(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(850013031, threadID);
}

/**
 * IsWSL reports whether the backend is running inside a WSL
 * distribution.
 */
export function IsWSL(): $CancellablePromise<boolean> {
    return $Call.ByID(2789068977);
}

/**
 * ListAttachments returns every attachment metadata row for a thread.
 */
export function ListAttachments(threadID: string): $CancellablePromise<store$0.Attachment[]> {
    return $Call.ByID(1730798413, threadID).then(($result: any) => {
        return $$createType34($result);
    });
}

/**
 * ListAvailableEditors returns every editor the open-in-editor
 * pipeline knows about. Available rows are launchable; unavailable
 * rows are returned too so the settings picker can surface
 * "VS Code (not installed)" instead of silently hiding options.
 * 
 * On WSL backends this enforces the editor-bridge rule: the only
 * editors that come back available are those reachable via the
 * vendor's WSL bridge (PATH-resolved shim that targets /mnt/c, or a
 * direct hit under /mnt/c/Users/.../AppData or /mnt/c/Program Files).
 * Linux-native installs are intentionally absent from the available
 * set even when their binary is on PATH — see
 * /Users/randy/.claude/projects/-Users-randy-repos-agent-overflow/memory/feedback_wsl_editor_bridge.md.
 */
export function ListAvailableEditors(): $CancellablePromise<$models.EditorInfo[]> {
    return $Call.ByID(2556802234).then(($result: any) => {
        return $$createType36($result);
    });
}

export function ListChatBarFavorites(): $CancellablePromise<store$0.ChatBarFavorite[]> {
    return $Call.ByID(2114948965).then(($result: any) => {
        return $$createType38($result);
    });
}

/**
 * ListDesignArtifacts returns persisted design artifacts for a thread.
 */
export function ListDesignArtifacts(threadID: string): $CancellablePromise<design$0.DesignArtifact[]> {
    return $Call.ByID(4255572490, threadID).then(($result: any) => {
        return $$createType40($result);
    });
}

/**
 * ListDiscussions returns persisted discussion definitions for the given scope.
 */
export function ListDiscussions(scope: string): $CancellablePromise<store$0.DiscussionDefinition[]> {
    return $Call.ByID(942288562, scope).then(($result: any) => {
        return $$createType41($result);
    });
}

export function ListDiscussionsForThread(threadID: string): $CancellablePromise<store$0.DiscussionDefinition[]> {
    return $Call.ByID(2502562885, threadID).then(($result: any) => {
        return $$createType41($result);
    });
}

/**
 * ListItems returns every item persisted for a thread in chronological order.
 */
export function ListItems(threadID: string): $CancellablePromise<store$0.Item[]> {
    return $Call.ByID(2158085763, threadID).then(($result: any) => {
        return $$createType42($result);
    });
}

/**
 * ListItemsBeforeTurn loads older turns on demand, strictly below
 * `beforeTurnIndex` (the frontend's current window floor). `turnLimit`
 * defaults to paginationTurns when <= 0.
 */
export function ListItemsBeforeTurn(threadID: string, beforeTurnIndex: number, turnLimit: number): $CancellablePromise<store$0.PagedItems> {
    return $Call.ByID(2147361923, threadID, beforeTurnIndex, turnLimit).then(($result: any) => {
        return $$createType43($result);
    });
}

/**
 * ListLiveBackgroundTasks returns running launches plus their
 * recently-completed siblings (within the tray retention window) so the
 * BackgroundTaskTray can render without scanning `pane.items`. SQLite
 * rows cover persisted Claude / Codex subagent launches; the triage
 * router appends transient Codex unified-exec tasks that intentionally
 * do not exist in chat history. Pending Codex unifiedExec launches
 * surface here before they are known to be backgrounded.
 */
export function ListLiveBackgroundTasks(threadID: string): $CancellablePromise<store$0.Item[]> {
    return $Call.ByID(320784263, threadID).then(($result: any) => {
        return $$createType42($result);
    });
}

/**
 * ListPayloadMetas returns all payload metadata for a thread without the body.
 */
export function ListPayloadMetas(threadID: string): $CancellablePromise<store$0.PayloadMeta[]> {
    return $Call.ByID(1007133701, threadID).then(($result: any) => {
        return $$createType45($result);
    });
}

/**
 * ListProjects returns projects with a lightweight thread count per
 * project for the sidebar.
 */
export function ListProjects(): $CancellablePromise<store$0.ProjectWithCounts[]> {
    return $Call.ByID(2721360259).then(($result: any) => {
        return $$createType47($result);
    });
}

/**
 * ListProposedPlanComments returns inline comments for one immutable plan
 * version. Resolved comments stay persisted and visible on older versions so
 * review history does not disappear when the agent proposes a revision.
 */
export function ListProposedPlanComments(threadID: string, planItemID: string): $CancellablePromise<store$0.ProposedPlanComment[]> {
    return $Call.ByID(2030403250, threadID, planItemID).then(($result: any) => {
        return $$createType48($result);
    });
}

/**
 * ListRecentThreadItems loads the tail of a thread's history into the
 * timeline pane: the last `turnLimit` turns (defaulting to
 * initialTurnWindow when <= 0) plus enough surrounding turns to keep
 * the total item count in [minWindowItems, maxWindowItems], plus any
 * subagent ancestors those items reference. This is the binding the
 * frontend calls on thread switch.
 */
export function ListRecentThreadItems(threadID: string, turnLimit: number): $CancellablePromise<store$0.PagedItems> {
    return $Call.ByID(2604956482, threadID, turnLimit).then(($result: any) => {
        return $$createType43($result);
    });
}

/**
 * ListRecentTurns returns the N most recent turn records for the given
 * thread, newest first. Used by the frontend on thread-switch to rehydrate
 * the latest settled-turn projection.
 * 
 * The frontend MUST NOT light up the working indicator from these rows —
 * an in-flight (completed_at=NULL) row from a prior session/crash is
 * historical, not live. Only a fresh `provider:turn_started` push can set
 * `pane.activeTurn`. See docs/architecture/invariants.md #22 and
 * docs/architecture/turn-lifecycle.md §Frontend state shape.
 */
export function ListRecentTurns(threadID: string, limit: number): $CancellablePromise<store$0.Turn[]> {
    return $Call.ByID(1083162294, threadID, limit).then(($result: any) => {
        return $$createType50($result);
    });
}

/**
 * ListRemoteEndpoints returns every saved `--connect` target with the
 * Token field stripped. The local UI fetches a token on-demand via
 * GetRemoteEndpointToken when copying a launch command — that pattern
 * keeps the bulk read path free of credentials so a remote token-
 * holder enumerating saved endpoints can't grab tokens for unrelated
 * backends.
 */
export function ListRemoteEndpoints(): $CancellablePromise<$models.RemoteEndpointSummary[]> {
    return $Call.ByID(3443007043).then(($result: any) => {
        return $$createType51($result);
    });
}

/**
 * ListTerminals returns a summary per active terminal for the given thread.
 */
export function ListTerminals(threadID: string): $CancellablePromise<terminal$0.SessionSummary[]> {
    return $Call.ByID(2445206506, threadID).then(($result: any) => {
        return $$createType53($result);
    });
}

/**
 * ListThreadCheckpoints returns every persisted checkpoint row for a thread.
 * Ordering is ascending by checkpoint turn count so the UI can render a
 * turn-navigation strip without additional sorting.
 */
export function ListThreadCheckpoints(threadID: string): $CancellablePromise<store$0.Checkpoint[]> {
    return $Call.ByID(1853132444, threadID).then(($result: any) => {
        return $$createType55($result);
    });
}

/**
 * ListThreadProposedPlans returns the current proposed-plan item for a thread,
 * outside the timeline window. It keeps the historical slice return shape for
 * binding compatibility, but callers should treat it as 0-or-1 items.
 */
export function ListThreadProposedPlans(threadID: string): $CancellablePromise<store$0.Item[]> {
    return $Call.ByID(2485050629, threadID).then(($result: any) => {
        return $$createType42($result);
    });
}

/**
 * ListThreads backs the frontend sidebar. It deliberately excludes
 * "draft" threads (newly created but never sent) so the sidebar stays
 * clean: a thread only becomes visible once its first item lands.
 * Internal callers that need every thread (tests, fork inspection,
 * discussion runtime) go through a.store.ListThreads directly.
 */
export function ListThreads(): $CancellablePromise<store$0.Thread[]> {
    return $Call.ByID(1090132042).then(($result: any) => {
        return $$createType56($result);
    });
}

/**
 * ListWSLDistros returns the WSL distros reported by `wsl.exe -l -v`
 * over WSL interop, or nil + nil on non-WSL hosts. Re-queries each
 * call so a distro installed mid-session shows up without a restart.
 */
export function ListWSLDistros(): $CancellablePromise<wsllauncher$0.Distro[]> {
    return $Call.ByID(2332614075).then(($result: any) => {
        return $$createType58($result);
    });
}

/**
 * MarkThreadRead stamps the thread's last_read_at to at least its latest
 * completed turn so the sidebar stops showing a Completed pill. The timestamp
 * is owned by the store so the App layer stays free of nowMillis() calls,
 * matching ArchiveThread / UpdateTitle etc.
 */
export function MarkThreadRead(id: string): $CancellablePromise<void> {
    return $Call.ByID(1480646012, id);
}

/**
 * MarkThreadUnread stamps last_read_at to zero. NULL is reserved for
 * "never tracked" rows that should not flood the sidebar as unread after
 * migration; explicit unread uses a concrete old timestamp.
 */
export function MarkThreadUnread(id: string): $CancellablePromise<void> {
    return $Call.ByID(236597375, id);
}

/**
 * OpenInEditor launches the user's preferred editor against `path`,
 * optionally placing the cursor at (line, col). Both are 1-indexed;
 * pass 0 for either to open without cursor placement.
 * 
 * `workspacePath`, when non-empty, is the absolute base directory used
 * to resolve a relative `path`. Click sites in the SPA that hand us
 * repo-relative paths (diff cards, tool-result file paths, markdown
 * path links inside chat) pass the active thread's workspace so the
 * path round-trips correctly. Empty workspacePath + relative path is
 * an error — see editor.ResolvePath for the full contract, including
 * the traversal-escape guard that keeps a token-holder over the
 * network from opening files outside the workspace.
 * 
 * Resolution order: settings.Editor.Preference → catalog priority →
 * $EDITOR / $VISUAL fallback. On WSL the editor must be the
 * Windows-installed app reachable via the vendor's WSL bridge; a
 * Linux-native `code-oss` (or equivalent) on PATH is deliberately
 * rejected because it would render via WSLg and miss the user's
 * actual editor environment. See
 * /Users/randy/.claude/projects/-Users-randy-repos-agent-overflow/memory/feedback_wsl_editor_bridge.md.
 * 
 * Errors flow back to the frontend as user-facing toasts; the strings
 * here are intentionally friendly — "no editor available" names
 * install paths the user can act on rather than dumping the internal
 * sentinel error.
 */
export function OpenInEditor(path: string, line: number, col: number, workspacePath: string): $CancellablePromise<void> {
    return $Call.ByID(3994295523, path, line, col, workspacePath);
}

/**
 * OpenTerminal starts a new PTY-backed terminal session bound to the given
 * thread.
 */
export function OpenTerminal(threadID: string, opts: $models.TerminalOpenOptions): $CancellablePromise<$models.TerminalHandle> {
    return $Call.ByID(2247958725, threadID, opts).then(($result: any) => {
        return $$createType59($result);
    });
}

/**
 * PinThread marks the thread as pinned. Pinned threads sort into a
 * dedicated tier above needs-attention so the user can keep a reference
 * thread permanently visible without status churn shuffling it.
 * Re-pinning an already-pinned thread bumps its pinnedAt, which moves
 * it within the pinned tier.
 */
export function PinThread(id: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(1748405812, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * PostChannelMessage posts a human-authored intervention into the channel.
 */
export function PostChannelMessage(channelID: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1315440605, channelID, content);
}

/**
 * PrepareThreadWorktree creates a new worktree from baseBranch, switches the
 * thread to it, and returns the updated thread. requestedBranch is optional:
 * blank means "create a temporary auto branch using the configured prefix".
 */
export function PrepareThreadWorktree(threadID: string, baseBranch: string, requestedBranch: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(2870364785, threadID, baseBranch, requestedBranch).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ProbeClaudeAccount spawns a short-lived Claude CLI subprocess with
 * `--max-turns 0` and returns the authenticated account metadata from
 * the emitted `system/init` message. Results are cached per binary path
 * for 5 minutes. Zero tokens are consumed — the CLI aborts before any
 * API call.
 * 
 * On a successful probe that returns an empty AccountInfo (no
 * subscription and no token source) we also emit a `provider:status`
 * event with Status="unauthenticated" so the thread-level banner can
 * prompt the user to run `claude login`.
 */
export function ProbeClaudeAccount(): $CancellablePromise<provider$0.AccountInfo> {
    return $Call.ByID(1313986574).then(($result: any) => {
        return $$createType60($result);
    });
}

/**
 * ReconfigureObservability reconciles the live observability stack with the
 * current Settings snapshot. Tracing changes always require restart (we
 * don't hot-swap tracer providers — that path is too easy to break in
 * ways the user only sees when a trace goes missing). The replay toggle
 * is cheap to flip in place.
 * 
 * This is the hook the UI calls after UpdateSettings persists a change —
 * see app_settings.go.
 */
export function ReconfigureObservability(prev: settings$0.Settings, next: settings$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(225050321, prev, next);
}

/**
 * ReconnectSession tears down the current session and starts a fresh one using
 * the thread's stored resume cursor.
 */
export function ReconnectSession(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(1420075138, threadID);
}

/**
 * RenameProject updates the display name. Path is immutable.
 */
export function RenameProject(id: string, name: string): $CancellablePromise<store$0.Project> {
    return $Call.ByID(3728890856, id, name).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RenameThread updates the thread title and emits a thread:updated
 * event so any other observer (chat header, multi-tab clients, future
 * remote viewers) re-renders with the new title without a follow-up
 * poll. Mirrors the emit shape used by applyGeneratedThreadTitle.
 */
export function RenameThread(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(727416435, id, title);
}

/**
 * ReplayManager returns the active replay manager. May be nil before startup.
 */
export function ReplayManager(): $CancellablePromise<replay$0.Manager | null> {
    return $Call.ByID(3320777729).then(($result: any) => {
        return $$createType62($result);
    });
}

/**
 * ResetKeybindings deletes the user file so GetKeybindings returns defaults.
 */
export function ResetKeybindings(): $CancellablePromise<void> {
    return $Call.ByID(2775767393);
}

/**
 * ResizeTerminal forwards a winsize change to the PTY.
 */
export function ResizeTerminal(terminalID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(1887984285, terminalID, rows, cols);
}

/**
 * RespondToApproval forwards an interactive response to the active provider session.
 */
export function RespondToApproval(threadID: string, response: provider$0.ApprovalResponse): $CancellablePromise<void> {
    return $Call.ByID(1919237704, threadID, response);
}

/**
 * RespondToUserInput forwards structured answers to the active provider session.
 */
export function RespondToUserInput(threadID: string, response: provider$0.UserInputResponse): $CancellablePromise<void> {
    return $Call.ByID(1071592868, threadID, response);
}

/**
 * RestartTerminal kills the given terminal and spawns a fresh replacement
 * with the same configuration.
 */
export function RestartTerminal(terminalID: string): $CancellablePromise<$models.TerminalHandle> {
    return $Call.ByID(4152403588, terminalID).then(($result: any) => {
        return $$createType59($result);
    });
}

/**
 * RevertToCheckpoint rolls a thread back to a checkpoint turn count. The
 * conversation-only mode keeps the current worktree and recaptures that kept
 * state as the new checkpoint baseline.
 */
export function RevertToCheckpoint(threadID: string, checkpointTurnCount: number, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3403186872, threadID, checkpointTurnCount, mode);
}

/**
 * SaveDraft replaces the draft row for a thread.
 */
export function SaveDraft(threadID: string, content: string, attachmentIDs: string[], terminalChips: $models.TerminalChip[], sourceProposedPlan: $models.SourceProposedPlan | null): $CancellablePromise<void> {
    return $Call.ByID(3025273299, threadID, content, attachmentIDs, terminalChips, sourceProposedPlan);
}

export function SavePayloadToFile(threadID: string, payloadID: string): $CancellablePromise<string> {
    return $Call.ByID(3576148797, threadID, payloadID);
}

/**
 * SearchThreadMessages runs a global substring search across thread titles
 * and item summaries. Intended to back the message-search overlay in the
 * frontend — kept thin so the store owns the query shape.
 * 
 * A zero or empty query short-circuits to an empty slice in the store; this
 * binding returns the same without an error so the frontend can call it on
 * every keystroke cheaply. limit caps the result set; callers should pass a
 * reasonable ceiling (50–100) for interactive UIs.
 */
export function SearchThreadMessages(query: string, limit: number): $CancellablePromise<store$0.ThreadMessageHit[]> {
    return $Call.ByID(3644945077, query, limit).then(($result: any) => {
        return $$createType64($result);
    });
}

/**
 * SearchWorkspaceFiles returns workspace files matching the query, scoped to
 * the workspace of the given thread.
 */
export function SearchWorkspaceFiles(threadID: string, query: string, limit: number): $CancellablePromise<$models.WorkspaceFileSearchResult> {
    return $Call.ByID(3852272821, threadID, query, limit).then(($result: any) => {
        return $$createType65($result);
    });
}

/**
 * SendMessage is the Wails-bound compatibility entry point for user-typed
 * content. The options-aware path below owns newer composer controls.
 */
export function SendMessage(threadID: string, content: string, attachmentIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1496882310, threadID, content, attachmentIDs);
}

/**
 * SendMessageWithOptions applies send-time composer settings and dispatches the
 * user turn. RuntimeMode is staged in the composer and persisted here, under
 * the same per-thread send lock as provider session start/send.
 */
export function SendMessageWithOptions(threadID: string, content: string, opts: $models.SendMessageOptions): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(3632185196, threadID, content, opts).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SendPlanRevisionComments sends only the selected draft comments back to the
 * agent. The same thread already contains the plan body, so this deliberately
 * avoids stuffing the full plan text into the prompt.
 */
export function SendPlanRevisionComments(threadID: string, planItemID: string, commentIDs: string[]): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(1407159655, threadID, planItemID, commentIDs).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetChatBarFavorite(fav: store$0.ChatBarFavorite, starred: boolean): $CancellablePromise<store$0.ChatBarFavorite[]> {
    return $Call.ByID(2813580982, fav, starred).then(($result: any) => {
        return $$createType38($result);
    });
}

/**
 * SetEditorSettings persists the user's editor preference. The value
 * is validated against the live catalog at open time, not here, so a
 * preference that becomes invalid (editor uninstalled) silently falls
 * back to the catalog default — see internal/editor.Resolve.
 * 
 * On success, RefreshEditors invalidates the detection cache so the
 * settings UI's next ListAvailableEditors call surfaces fresh state
 * — the user just made a deliberate change and shouldn't see stale
 * availability flags.
 */
export function SetEditorSettings(s: settings$0.EditorSettings): $CancellablePromise<settings$0.EditorSettings> {
    return $Call.ByID(3655340267, s).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SetNetworkSettings persists the new bind-all preference and rebinds
 * the transport server. Going false → true rebinds to 0.0.0.0:<port>
 * so LAN clients can reach the app; true → false rebinds back to
 * 127.0.0.1:<port>. The port is reused so a previously-shared URL
 * stays valid (only the host changes).
 * 
 * On rebind failure the transport state is unchanged (Rebind is
 * state-intact on error) and the persisted setting is rolled back so
 * a subsequent GetNetworkSettings returns the actual transport state.
 * Returns the post-rebind NetworkSettings so the UI can update the URL
 * display in one round trip.
 * 
 * Origin allow-list: a LAN bind requires an explicit allow-list so a
 * stray browser tab on the LAN can't WebSocket-hijack a leaked token
 * (CSWSH). On bind-all=true the list contains loopback variants plus
 * the discovered LAN IP; on bind-all=false the list is empty (loopback
 * has no browser-origin to validate, and InsecureSkipVerify is fine).
 */
export function SetNetworkSettings(s: $models.NetworkSettings): $CancellablePromise<$models.NetworkSettings> {
    return $Call.ByID(3915514446, s).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * SetThreadRuntimeMode is the legacy binding name preserved only while
 * the frontend migration lands (Wave 2c+). The implementation routes to
 * UpdateThreadRuntimeMode and returns the older event struct.
 * 
 * The new per-field binding UpdateThreadRuntimeMode in app_threads.go
 * is the going-forward surface and returns store.Thread directly.
 */
export function SetThreadRuntimeMode(threadID: string, mode: string): $CancellablePromise<$models.ThreadRuntimeModeChangedEvent> {
    return $Call.ByID(1115610690, threadID, mode).then(($result: any) => {
        return $$createType66($result);
    });
}

/**
 * SetWSLDistroPreference persists the new distro pick to the
 * launcher's wsl.json. The change applies on the next Windows-side
 * launch; the running backend stays in its current distro for the
 * remainder of this session.
 * 
 * Validates `name` against the live wsl.exe distro list so a typo or
 * stale reference can't trap the user with an unbootable saved pick.
 * InstalledVer / InstalledDistro are preserved by load-mutate-save —
 * those fields are owned by the launcher's install path.
 */
export function SetWSLDistroPreference(name: string): $CancellablePromise<string> {
    return $Call.ByID(3978807241, name);
}

/**
 * StartDiscussion creates a deliberation channel and marks the thread as operating in discussion mode.
 */
export function StartDiscussion(threadID: string, discussionName: string): $CancellablePromise<void> {
    return $Call.ByID(3188309099, threadID, discussionName);
}

export function StartDiscussionByID(threadID: string, discussionID: string): $CancellablePromise<void> {
    return $Call.ByID(2336869067, threadID, discussionID);
}

/**
 * StartSession is the Wails-bound entry point for "bring this thread's
 * provider subprocess up." The sendMessage path also calls
 * startSessionNow via runSessionStart when a thread has no active
 * session yet.
 */
export function StartSession(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(2850159713, threadID);
}

/**
 * StopClaudeTask asks the Claude CLI to kill a backgrounded task
 * (run_in_background Bash or a Task subagent) identified by `taskID`.
 * On success the CLI emits a follow-up `system/task_updated` with
 * `patch.status:"killed"` on the normal event stream, which flows
 * through triage into the sibling `tool_completion` row as
 * status=killed — rendered as a distinct "Stopped" badge in the UI.
 * 
 * Returns typed errors for:
 * 
 *   - session-missing: no Claude session for this thread. The caller
 *     started a stop before Start / after Close.
 *   - provider-mismatch: the thread exists but it's a Codex session,
 *     not a Claude one. Codex has no per-row stop primitive
 *     (see docs/references/codex.md#known-upstream-constraints); the
 *     frontend must branch on provider before reaching for this.
 *   - timeout / provider error: surfaced verbatim so the UI can render
 *     the CLI-supplied message.
 */
export function StopClaudeTask(threadID: string, taskID: string): $CancellablePromise<void> {
    return $Call.ByID(536320598, threadID, taskID);
}

/**
 * StopSession tears down the thread's provider session. Idempotent: a
 * thread with no active session still runs the design teardown +
 * triage cleanup so stale per-thread state doesn't leak.
 */
export function StopSession(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(3838500111, threadID);
}

/**
 * SwitchThread returns the requested thread, marks it read durably, and
 * auto-resumes its provider session in the background when the thread has a
 * stored session reference.
 */
export function SwitchThread(threadID: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(3897387725, threadID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Telemetry returns the active OpenTelemetry provider. Returns nil when the
 * app has not completed ServiceStartup. Exported for tests that need to
 * inspect or replace the provider at runtime.
 */
export function Telemetry(): $CancellablePromise<otel$0.Provider | null> {
    return $Call.ByID(669486408).then(($result: any) => {
        return $$createType68($result);
    });
}

/**
 * TouchRemoteEndpoint bumps the LastUsedAt timestamp on the named
 * record. Used by the settings UI's "Connect" affordance so the
 * list can sort or visually emphasise recently-used endpoints.
 */
export function TouchRemoteEndpoint(id: string): $CancellablePromise<void> {
    return $Call.ByID(2647456459, id);
}

/**
 * UnarchiveProject reverses ArchiveProject and returns the refreshed row.
 */
export function UnarchiveProject(id: string): $CancellablePromise<store$0.Project> {
    return $Call.ByID(2561521885, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * UnarchiveThread flips archived back to false so the thread reappears in the
 * active sidebar. Returns the refreshed row so the caller can re-render
 * without a follow-up GetThread round-trip.
 */
export function UnarchiveThread(id: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(3655125512, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UnpinThread clears the thread's pinned_at and returns the refreshed
 * row so the frontend can reconcile its store without a list refetch.
 */
export function UnpinThread(id: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(3175043037, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UpdateContextSettingsProfile(update: $models.ContextSettingsUpdate): $CancellablePromise<$models.ContextSettingsProfile> {
    return $Call.ByID(1472386383, update).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * UpdateDiscussion replaces an existing persisted discussion definition.
 */
export function UpdateDiscussion(prevName: string, prevScope: string, def: store$0.DiscussionDefinition): $CancellablePromise<void> {
    return $Call.ByID(1706395020, prevName, prevScope, def);
}

/**
 * UpdateKeybindings replaces the user keybindings file with the caller's
 * config. The config is capped at maxKeybindingsCount entries; entries past
 * the cap are dropped from the tail.
 */
export function UpdateKeybindings(bindings: $models.Keybinding[]): $CancellablePromise<void> {
    return $Call.ByID(3490094229, bindings);
}

/**
 * UpdateProjectSortPositions re-orders the projects list. The frontend
 * emits the full ordered list when the user drops a drag-reorder so the
 * store assigns dense positions 0..N-1 in one transaction.
 */
export function UpdateProjectSortPositions(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(3717363955, orderedIDs);
}

export function UpdateProposedPlanComment(threadID: string, commentID: string, input: store$0.ProposedPlanCommentUpdate): $CancellablePromise<store$0.ProposedPlanComment> {
    return $Call.ByID(2747956806, threadID, commentID, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * UpdateRemoteEndpoint mutates the named-by-ID record. Empty fields
 * in the patch leave the existing value untouched, matching the
 * settings-service semantics, so the UI can update a nickname
 * without re-typing the URL or token.
 * 
 * SECURITY: returns RemoteEndpointSummary so a no-op Update from a
 * LAN-attached token-holder can't harvest the persisted token. See
 * AddRemoteEndpoint for the threat model.
 */
export function UpdateRemoteEndpoint(id: string, name: string, url: string, token: string): $CancellablePromise<$models.RemoteEndpointSummary> {
    return $Call.ByID(4268476031, id, name, url, token).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateSettings applies a partial settings patch and persists it. Observability
 * toggles that can flip at runtime (e.g. replay log) are reconciled here.
 * Tracing changes are persisted but require a restart to take effect — the
 * UI shows a banner when that path is taken.
 * 
 * When the patch touches "editor", the catalog detection cache is
 * invalidated so the next ListAvailableEditors call surfaces fresh
 * state. The dedicated SetEditorSettings binding does the same; this
 * generic path needs the parallel hook because the frontend Settings
 * panel writes through UpdateSettings for any field — a stale cache
 * after a generic update would leave the picker showing the wrong
 * availability flags until the next app launch.
 */
export function UpdateSettings(patch: { [_ in string]?: any }): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2894041249, patch).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * UpdateThreadBranch persists the branch column. Does NOT perform the
 * git checkout — that flow lives in GitCheckout. Kept as a narrow metadata
 * binding for callers that need to repair/import thread state without touching
 * the repository checkout.
 */
export function UpdateThreadBranch(id: string, branch: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(2929723500, id, branch).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UpdateThreadContextSettings(threadID: string, update: $models.ContextSettingsUpdate): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(2621473242, threadID, update).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateThreadContextWindow persists the context window size and
 * restarts the session if one is live.
 */
export function UpdateThreadContextWindow(id: string, tokens: number): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(2456875639, id, tokens).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateThreadFastMode persists the fast-mode boolean and restarts the
 * session if one is live. Fast mode typically swaps the model to the
 * provider's small-model tier (per the per-provider translator) so a
 * running session won't pick up the change without a restart.
 */
export function UpdateThreadFastMode(id: string, on: boolean): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(4175109385, id, on).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateThreadMode updates the thread's mode and returns the refreshed
 * row. Rejects unknown modes with a clear error message so the frontend
 * can surface it verbatim.
 * 
 * Active Claude sessions apply chat/plan changes immediately through
 * set_permission_mode. Codex reads the persisted mode on the next turn/start.
 * Modes that cannot be applied to the live session emit NeedsReconnect=true.
 * The persisted row is always updated regardless.
 */
export function UpdateThreadMode(threadID: string, mode: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(3609479719, threadID, mode).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateThreadModel changes a thread's model and restarts an active provider
 * session so the new model takes effect immediately. Threads without an active
 * session are updated in place and will use the new model on the next start.
 */
export function UpdateThreadModel(threadID: string, model: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(4179686417, threadID, model).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateThreadProvider persists the provider column and restarts the
 * session if one is live so the new provider takes effect.
 * 
 * A thread is locked to its provider once any item has been persisted:
 * provider sessions are not interchangeable (Codex can't resume a Claude
 * rollout and vice versa), so an in-flight switch would surface as a
 * "thread/resume: no rollout found" error from the reconnect goroutine
 * and leave the thread in a confusing half-switched state. Reject at the
 * binding boundary with a user-facing message instead. Same-provider
 * calls short-circuit so a UI that re-sends the current provider on
 * every model change doesn't trip the lock.
 */
export function UpdateThreadProvider(id: string, providerName: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(665741969, id, providerName).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateThreadReasoningEffort persists the effort tier and restarts the
 * session if one is live.
 */
export function UpdateThreadReasoningEffort(id: string, effort: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(892204206, id, effort).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateThreadRuntimeMode persists the runtime mode and restarts the
 * session if one is live. Replaces the older SetThreadRuntimeMode
 * naming; kept as a single surface so the frontend speaks one shape.
 */
export function UpdateThreadRuntimeMode(id: string, mode: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(325190827, id, mode).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateThreadWorkspace persists a new workspace path. Used by the
 * EnvPicker to switch a thread between the project root and a worktree
 * without creating the worktree itself. Restarts the session if one is
 * live because the provider CWD is part of its launch config.
 */
export function UpdateThreadWorkspace(id: string, path: string): $CancellablePromise<store$0.Thread> {
    return $Call.ByID(3875142865, id, path).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UploadAttachment decodes base64 bytes, validates + persists them on disk,
 * and returns the new attachment metadata.
 */
export function UploadAttachment(threadID: string, filename: string, mimeType: string, dataB64: string): $CancellablePromise<store$0.Attachment> {
    return $Call.ByID(2485473713, threadID, filename, mimeType, dataB64).then(($result: any) => {
        return $$createType33($result);
    });
}

/**
 * WriteTerminal writes base64-encoded data to the given terminal. The
 * payload is base64 rather than a raw string so that non-UTF-8 byte
 * sequences (control codes, mouse events, binary heredocs) round-trip
 * losslessly from the frontend.
 */
export function WriteTerminal(terminalID: string, dataB64: string): $CancellablePromise<void> {
    return $Call.ByID(146795716, terminalID, dataB64);
}

/**
 * WriteThreadWorkspaceFile writes content to a path relative to the thread's
 * active workspace and returns the normalized relative path.
 */
export function WriteThreadWorkspaceFile(threadID: string, relativePath: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(3895036895, threadID, relativePath, content);
}

// Private type creation functions
const $$createType0 = $models.RemoteEndpointSummary.createFrom;
const $$createType1 = $models.DirectoryListing.createFrom;
const $$createType2 = store$0.Project.createFrom;
const $$createType3 = store$0.ProposedPlanComment.createFrom;
const $$createType4 = store$0.Thread.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.GeneratedCommitMessage.createFrom;
const $$createType7 = $models.AttachmentThumbnail.createFrom;
const $$createType8 = store$0.ChannelMessage.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.ContextSettingsProfile.createFrom;
const $$createType11 = store$0.DiscussionDefinition.createFrom;
const $$createType12 = $models.Draft.createFrom;
const $$createType13 = settings$0.EditorSettings.createFrom;
const $$createType14 = git$0.GitStatus.createFrom;
const $$createType15 = $models.Keybinding.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = provider$0.ModelInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.NetworkSettings.createFrom;
const $$createType20 = $models.PayloadChunk.createFrom;
const $$createType21 = $models.PayloadContent.createFrom;
const $$createType22 = $models.PayloadPreview.createFrom;
const $$createType23 = provider$0.ProviderStatus.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = settings$0.Settings.createFrom;
const $$createType26 = store$0.Item.createFrom;
const $$createType27 = git$0.GitActionResult.createFrom;
const $$createType28 = git$0.GitBranch.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = git$0.Worktree.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = $models.GitStatusSubscriptionResult.createFrom;
const $$createType33 = store$0.Attachment.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = $models.EditorInfo.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = store$0.ChatBarFavorite.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = store$0.DesignArtifact.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = $Create.Array($$createType11);
const $$createType42 = $Create.Array($$createType26);
const $$createType43 = store$0.PagedItems.createFrom;
const $$createType44 = store$0.PayloadMeta.createFrom;
const $$createType45 = $Create.Array($$createType44);
const $$createType46 = store$0.ProjectWithCounts.createFrom;
const $$createType47 = $Create.Array($$createType46);
const $$createType48 = $Create.Array($$createType3);
const $$createType49 = store$0.Turn.createFrom;
const $$createType50 = $Create.Array($$createType49);
const $$createType51 = $Create.Array($$createType0);
const $$createType52 = terminal$0.SessionSummary.createFrom;
const $$createType53 = $Create.Array($$createType52);
const $$createType54 = store$0.Checkpoint.createFrom;
const $$createType55 = $Create.Array($$createType54);
const $$createType56 = $Create.Array($$createType4);
const $$createType57 = wsllauncher$0.Distro.createFrom;
const $$createType58 = $Create.Array($$createType57);
const $$createType59 = $models.TerminalHandle.createFrom;
const $$createType60 = provider$0.AccountInfo.createFrom;
const $$createType61 = replay$0.Manager.createFrom;
const $$createType62 = $Create.Nullable($$createType61);
const $$createType63 = store$0.ThreadMessageHit.createFrom;
const $$createType64 = $Create.Array($$createType63);
const $$createType65 = $models.WorkspaceFileSearchResult.createFrom;
const $$createType66 = $models.ThreadRuntimeModeChangedEvent.createFrom;
const $$createType67 = otel$0.Provider.createFrom;
const $$createType68 = $Create.Nullable($$createType67);
