// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * desktopApplyWindow is the helper's window (desktopApplyUI): the loading
 * page while the update or the migration runs, and a failure page after
 * one that does not end in a launch. It is also the Wails service whose
 * RetryMigration the Retry button calls. It holds the desktop's
 * single-instance identity, so a launch while it runs shows it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * RetryMigration is bound to the page of a database upgrade the failure
 * memory stopped. It runs the upgrade again, once.
 */
export function RetryMigration(): $CancellablePromise<void> {
    return $Call.ByID(4247868426);
}
