// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Provider identifies which native config a status entry was sourced
 * from. The same server name can exist for both providers so every
 * cache lookup is keyed by (Provider, Name) — see Key.
 */
export enum Provider {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderClaude = "claude",
    ProviderCodex = "codex",
};

/**
 * ServerStatus is the wire shape every binding speaks. ToolCount /
 * Tools / AuthStatus / Error / Raw are best-effort — present when the
 * wire source carries them, empty otherwise. Tools holds tool NAMES
 * only: both providers' status responses also carry server config
 * (args/env can hold live tokens) and tool schemas, and neither may
 * ever reach this shape. CheckedAt is for "how stale" display; the
 * cache uses its own clock for TTL.
 */
export class ServerStatus {
    "provider": Provider;
    "name": string;
    "status": Status;
    "toolCount"?: number;
    "tools"?: string[];
    "authStatus"?: string;
    "error"?: string;
    "raw"?: string;
    "source": Source;
    "checkedAt": string;

    /** Creates a new ServerStatus instance. */
    constructor($$source: Partial<ServerStatus> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = Provider.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("source" in $$source)) {
            this["source"] = Source.$zero;
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStatus {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField4_0($$parsedSource["tools"]);
        }
        return new ServerStatus($$parsedSource as Partial<ServerStatus>);
    }
}

/**
 * Source attributes how a ServerStatus was produced so callers can
 * reason about freshness without consulting timestamps. "live-session"
 * is authoritative (the provider's own process reported it);
 * "notification" is a delta from a running provider; "ephemeral-fetch"
 * is the on-demand stdout-parse/JSON-RPC-list path used when no live
 * session exists.
 */
export enum Source {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SourceLiveSession = "live-session",
    SourceNotification = "notification",
    SourceEphemeralFetch = "ephemeral-fetch",
};

/**
 * Status is the normalized state every MCP server resolves to,
 * regardless of which provider reported it. The string values match
 * the JSON the bindings hand the frontend; the enum is closed so the
 * UI can switch over it exhaustively.
 * 
 * Provider-native → Status projection lives in the provider packages
 * (`internal/provider/claude/mcpstatus.go`,
 * `internal/provider/codex/mcpstatus.go`) so each adapter owns its
 * own wire vocabulary.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * never observed, or ambiguous wire state
     */
    StatusUnknown = "unknown",

    /**
     * Codex notification "starting" / Claude "pending"
     */
    StatusStarting = "starting",

    /**
     * Codex authStatus∈{unknown,unsupported,bearerToken,oAuth} ∧ initialize proven (serverInfo or tools) OR notif "ready" / Claude "connected"
     */
    StatusConnected = "connected",

    /**
     * Codex "notLoggedIn" / Claude "needs-auth"
     */
    StatusNeedsAuth = "needs-auth",

    /**
     * Codex notif "failed"|"cancelled", or a settled list probe with no initialize evidence / Claude "failed"
     */
    StatusFailed = "failed",

    /**
     * Claude "disabled" (toggled off; the CLI keeps the row and reports it)
     */
    StatusDisabled = "disabled",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
