// Android vectors from the official AO mark. Run with --check in APK builds.
import { readFileSync, writeFileSync } from 'node:fs';

const root = new URL('../../', import.meta.url);
const read = path => readFileSync(new URL(path, root), 'utf8');
const svg = read('build/appicon.icon/Assets/agent-overflow-mark.svg');
const attrs = tag => Object.fromEntries([...tag.matchAll(/([\w-]+)="([^"]*)"/g)].map(m => [m[1], m[2]]));
const group = attrs(svg.match(/<g\s[^>]*>/)?.[0] ?? '');
const path = svg.match(/<path\s+d="([^"]+)"\s*\/>/)?.[1];
const circle = attrs(svg.match(/<circle\s[^>]*\/>/)?.[0] ?? '');
// Deliberately only the canonical mark's two primitives, not a partial SVG renderer.
if (!svg.includes('viewBox="0 0 1024 1024"') || !path ||
    (svg.match(/<path\b/g) ?? []).length !== 1 || (svg.match(/<circle\b/g) ?? []).length !== 1 ||
    (svg.match(/<g\b/g) ?? []).length !== 1 || /\btransform\s*=/.test(svg) ||
    [...svg.matchAll(/<([a-zA-Z][\w:-]*)\b/g)].some(m => !['svg', 'title', 'g', 'path', 'circle'].includes(m[1])) ||
    group.fill !== 'none' || group['stroke-linecap'] !== 'round' || group['stroke-linejoin'] !== 'round' ||
    !/^#[0-9a-f]{6}$/i.test(group.stroke) || !/^\d+$/.test(group['stroke-width']) ||
    !['cx', 'cy', 'r'].every(key => /^\d+$/.test(circle[key] ?? ''))) {
  throw new Error('AO artwork structure changed; update generate-icons.mjs to preserve its geometry.');
}
const [x, y, r] = ['cx', 'cy', 'r'].map(key => Number(circle[key]));
const paths = [path, `M ${x + r} ${y} A ${r} ${r} 0 1 0 ${x - r} ${y} A ${r} ${r} 0 1 0 ${x + r} ${y}`];
const header = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by mobile/scripts/generate-icons.mjs; do not edit. -->\n';
const vector = (size, scale) => `${header}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${size}dp" android:height="${size}dp" android:viewportWidth="1024" android:viewportHeight="1024">
    <group android:pivotX="512" android:pivotY="512" android:scaleX="${scale}" android:scaleY="${scale}">
${paths.map(d => `        <path android:pathData="${d}" android:fillColor="@android:color/transparent"
            android:strokeColor="${group.stroke}" android:strokeWidth="${group['stroke-width']}"
            android:strokeLineCap="round" android:strokeLineJoin="round"/>`).join('\n')}
    </group>
</vector>
`;
const fill = JSON.parse(read('build/appicon.icon/icon.json')).fill?.solid;
if (typeof fill !== 'string' || !fill.startsWith('srgb:')) throw new Error('AO icon background must be sRGB.');
const rgb = fill.slice(5).split(',');
if (rgb.length !== 4 || rgb.some(v => v.trim() === '' || !Number.isFinite(Number(v)) || Number(v) < 0 || Number(v) > 1) || Number(rgb[3]) !== 1) {
  throw new Error('AO icon background must be an opaque sRGB color.');
}
const background = '#' + rgb.slice(0, 3).map(v => Math.round(Number(v) * 255).toString(16).padStart(2, '0')).join('').toUpperCase();
const files = {
  // 60dp-wide artwork inside Android's central 66dp safe region on a 108dp layer.
  'drawable/ic_launcher_foreground.xml': vector(108, 0.72),
  // Notification small icons use alpha only: never an opaque/adaptive launcher tile.
  'drawable/ic_notification.xml': vector(24, 1),
  'values/ic_launcher_background.xml': `${header}<resources>
    <color name="ic_launcher_background">${background}</color>
</resources>
`,
};
for (const [name, content] of Object.entries(files)) {
  const target = new URL(`mobile/android/app/src/main/res/${name}`, root);
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== content) throw new Error(`Stale ${name}; run node mobile/scripts/generate-icons.mjs`);
  } else writeFileSync(target, content);
}
