// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Attachment is the persisted metadata for a file attached to a thread.
 */
export class Attachment {
    "id": string;
    "threadId": string;
    "filename": string;
    "mimeType": string;
    "size": number;
    "relativePath": string;
    "createdAt": number;

    /** Creates a new Attachment instance. */
    constructor($$source: Partial<Attachment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("threadId" in $$source)) {
            this["threadId"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     */
    static createFrom($$source: any = {}): Attachment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment($$parsedSource as Partial<Attachment>);
    }
}

/**
 * ChannelMessage is one ordered message within a channel.
 * 
 * Meta is JSON-shaped optional sidecar data persisted alongside the
 * raw message content. Today it carries the pathlinks allowlist
 * (`pathRefs`) stamped at PostMessage time so the frontend's markdown
 * linkifier knows which file references in the rendered text point
 * at real files in the thread's workspace. The column is nullable
 * (pre-v2 rows have no value); callers should treat absence as
 * "no allowlist".
 */
export class ChannelMessage {
    "id": string;
    "channelId": string;
    "sequence": number;
    "fromType": string;
    "fromId": string;
    "fromRole"?: string;
    "content": string;
    "meta"?: string;
    "createdAt": number;

    /** Creates a new ChannelMessage instance. */
    constructor($$source: Partial<ChannelMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("channelId" in $$source)) {
            this["channelId"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("fromType" in $$source)) {
            this["fromType"] = "";
        }
        if (!("fromId" in $$source)) {
            this["fromId"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelMessage($$parsedSource as Partial<ChannelMessage>);
    }
}

/**
 * ChatBarFavorite is one starred entry in the composer model menu.
 * Kind is "model" or "discussion". Provider is set only for model
 * favorites; Value is the model slug or discussion definition id.
 */
export class ChatBarFavorite {
    "kind": string;
    "provider"?: string;
    "value": string;
    "label": string;
    "createdAt": number;

    /** Creates a new ChatBarFavorite instance. */
    constructor($$source: Partial<ChatBarFavorite> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatBarFavorite instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatBarFavorite {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatBarFavorite($$parsedSource as Partial<ChatBarFavorite>);
    }
}

export class DiffReviewComment {
    "id": string;
    "threadId": string;
    "scope": string;
    "sourceKey": string;
    "filePath": string;
    "status": string;
    "oldLine"?: number;
    "newLine"?: number;
    "side": string;
    "selectedText": string;
    "body": string;
    "sentAt"?: number;
    "sentTurnId"?: string;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new DiffReviewComment instance. */
    constructor($$source: Partial<DiffReviewComment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("threadId" in $$source)) {
            this["threadId"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("sourceKey" in $$source)) {
            this["sourceKey"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("side" in $$source)) {
            this["side"] = "";
        }
        if (!("selectedText" in $$source)) {
            this["selectedText"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffReviewComment instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffReviewComment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffReviewComment($$parsedSource as Partial<DiffReviewComment>);
    }
}

export class DiffReviewCommentInput {
    "scope": string;
    "sourceKey": string;
    "filePath": string;
    "oldLine"?: number;
    "newLine"?: number;
    "side": string;
    "selectedText": string;
    "body": string;

    /** Creates a new DiffReviewCommentInput instance. */
    constructor($$source: Partial<DiffReviewCommentInput> = {}) {
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("sourceKey" in $$source)) {
            this["sourceKey"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("side" in $$source)) {
            this["side"] = "";
        }
        if (!("selectedText" in $$source)) {
            this["selectedText"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffReviewCommentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffReviewCommentInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffReviewCommentInput($$parsedSource as Partial<DiffReviewCommentInput>);
    }
}

export class DiffReviewCommentUpdate {
    "body": string;

    /** Creates a new DiffReviewCommentUpdate instance. */
    constructor($$source: Partial<DiffReviewCommentUpdate> = {}) {
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffReviewCommentUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffReviewCommentUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffReviewCommentUpdate($$parsedSource as Partial<DiffReviewCommentUpdate>);
    }
}

export class DiffReviewSourceRef {
    "threadId"?: string;
    "scope": string;
    "sourceKey": string;

    /** Creates a new DiffReviewSourceRef instance. */
    constructor($$source: Partial<DiffReviewSourceRef> = {}) {
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("sourceKey" in $$source)) {
            this["sourceKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffReviewSourceRef instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffReviewSourceRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffReviewSourceRef($$parsedSource as Partial<DiffReviewSourceRef>);
    }
}

/**
 * DiscussionDefinition is the persisted discussion registry record.
 */
export class DiscussionDefinition {
    "id": string;
    "name": string;
    "description": string;
    "scope": string;
    "projectId"?: string;
    "participants": DiscussionParticipant[];
    "settings": DiscussionSettings;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new DiscussionDefinition instance. */
    constructor($$source: Partial<DiscussionDefinition> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("participants" in $$source)) {
            this["participants"] = [];
        }
        if (!("settings" in $$source)) {
            this["settings"] = (new DiscussionSettings());
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscussionDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscussionDefinition {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("participants" in $$parsedSource) {
            $$parsedSource["participants"] = $$createField5_0($$parsedSource["participants"]);
        }
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField6_0($$parsedSource["settings"]);
        }
        return new DiscussionDefinition($$parsedSource as Partial<DiscussionDefinition>);
    }
}

/**
 * DiscussionParticipant defines a single participant in a discussion.
 */
export class DiscussionParticipant {
    "role": string;
    "description": string;
    "system": string;
    "provider"?: string;
    "model"?: string;

    /** Creates a new DiscussionParticipant instance. */
    constructor($$source: Partial<DiscussionParticipant> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("system" in $$source)) {
            this["system"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscussionParticipant instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscussionParticipant {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscussionParticipant($$parsedSource as Partial<DiscussionParticipant>);
    }
}

/**
 * DiscussionSettings contains runtime discussion configuration.
 */
export class DiscussionSettings {
    "maxTurns": number;

    /** Creates a new DiscussionSettings instance. */
    constructor($$source: Partial<DiscussionSettings> = {}) {
        if (!("maxTurns" in $$source)) {
            this["maxTurns"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscussionSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscussionSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscussionSettings($$parsedSource as Partial<DiscussionSettings>);
    }
}

/**
 * Item represents a persisted timeline entry.
 */
export class Item {
    "id": string;
    "threadId": string;
    "turnIndex": number;
    "itemIndex": number;
    "kind": string;
    "role": string;
    "status": string;
    "summary": string;
    "payloadId"?: string;
    "payloadKind"?: string;
    "payloadMeta"?: string;
    "inputPayloadId"?: string;
    "parentId"?: string;
    "isBackground"?: boolean;
    "completionOf"?: string;
    "toolName"?: string;
    "decision"?: string;
    "meta"?: string;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new Item instance. */
    constructor($$source: Partial<Item> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("threadId" in $$source)) {
            this["threadId"] = "";
        }
        if (!("turnIndex" in $$source)) {
            this["turnIndex"] = 0;
        }
        if (!("itemIndex" in $$source)) {
            this["itemIndex"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     */
    static createFrom($$source: any = {}): Item {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Item($$parsedSource as Partial<Item>);
    }
}

/**
 * PagedItems is the return shape for windowed item loads. `Items` is sorted
 * by (turn_index, item_index) ASC so callers can append the slice directly
 * to a timeline. `OldestTurnIndex` is the inclusive floor of the returned
 * set — the smallest turn_index that appears in `Items`. It is -1 when
 * `Items` is empty. `HasMore` is true when the database has at least one
 * item with `turn_index < OldestTurnIndex` for this thread, which is the
 * signal the frontend uses to render "Load older messages".
 */
export class PagedItems {
    "items": Item[];
    "oldestTurnIndex": number;
    "hasMore": boolean;

    /** Creates a new PagedItems instance. */
    constructor($$source: Partial<PagedItems> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("oldestTurnIndex" in $$source)) {
            this["oldestTurnIndex"] = 0;
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PagedItems instance from a string or object.
     */
    static createFrom($$source: any = {}): PagedItems {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new PagedItems($$parsedSource as Partial<PagedItems>);
    }
}

/**
 * PayloadMeta is the meta-only view (no data blob).
 */
export class PayloadMeta {
    "id": string;
    "kind": string;
    "meta": string;
    "createdAt": number;

    /** Creates a new PayloadMeta instance. */
    constructor($$source: Partial<PayloadMeta> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("meta" in $$source)) {
            this["meta"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PayloadMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): PayloadMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PayloadMeta($$parsedSource as Partial<PayloadMeta>);
    }
}

/**
 * Project represents a user-defined grouping of threads rooted at a
 * directory. Threads belong to a project via the project_id FK; the
 * project's path is the canonical workspace root, though individual
 * threads may operate in a worktree that diverges from project.path.
 */
export class Project {
    "id": string;
    "path": string;
    "name": string;
    "color"?: string;
    "sortPosition": number;
    "createdAt": number;
    "updatedAt": number;
    "archived": boolean;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sortPosition" in $$source)) {
            this["sortPosition"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("archived" in $$source)) {
            this["archived"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * ProjectWithCounts is the sidebar-lightweight view: the project row plus
 * its thread count and the timestamp of the most recently touched thread.
 * LastActive is 0 when the project has no active (non-archived) threads.
 */
export class ProjectWithCounts {
    "project": Project;
    "threadCount": number;
    "lastActive"?: number;

    /** Creates a new ProjectWithCounts instance. */
    constructor($$source: Partial<ProjectWithCounts> = {}) {
        if (!("project" in $$source)) {
            this["project"] = (new Project());
        }
        if (!("threadCount" in $$source)) {
            this["threadCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectWithCounts instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectWithCounts {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField0_0($$parsedSource["project"]);
        }
        return new ProjectWithCounts($$parsedSource as Partial<ProjectWithCounts>);
    }
}

/**
 * ProposedPlanComment is one inline review note anchored to a proposed plan.
 */
export class ProposedPlanComment {
    "id": string;
    "threadId": string;
    "planItemId": string;
    "status": string;
    "startLine": number;
    "endLine": number;
    "selectedText": string;
    "body": string;
    "sentAt"?: number;
    "sentTurnId"?: string;
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new ProposedPlanComment instance. */
    constructor($$source: Partial<ProposedPlanComment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("threadId" in $$source)) {
            this["threadId"] = "";
        }
        if (!("planItemId" in $$source)) {
            this["planItemId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("startLine" in $$source)) {
            this["startLine"] = 0;
        }
        if (!("endLine" in $$source)) {
            this["endLine"] = 0;
        }
        if (!("selectedText" in $$source)) {
            this["selectedText"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProposedPlanComment instance from a string or object.
     */
    static createFrom($$source: any = {}): ProposedPlanComment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProposedPlanComment($$parsedSource as Partial<ProposedPlanComment>);
    }
}

/**
 * ProposedPlanCommentInput carries the editable comment fields from the UI.
 */
export class ProposedPlanCommentInput {
    "planItemId": string;
    "startLine": number;
    "endLine": number;
    "body": string;

    /** Creates a new ProposedPlanCommentInput instance. */
    constructor($$source: Partial<ProposedPlanCommentInput> = {}) {
        if (!("planItemId" in $$source)) {
            this["planItemId"] = "";
        }
        if (!("startLine" in $$source)) {
            this["startLine"] = 0;
        }
        if (!("endLine" in $$source)) {
            this["endLine"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProposedPlanCommentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ProposedPlanCommentInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProposedPlanCommentInput($$parsedSource as Partial<ProposedPlanCommentInput>);
    }
}

/**
 * ProposedPlanCommentUpdate carries the fields that can be changed after a
 * comment exists. Editing a sent comment makes it draft again so it can be sent
 * as a fresh revision request.
 */
export class ProposedPlanCommentUpdate {
    "body": string;

    /** Creates a new ProposedPlanCommentUpdate instance. */
    constructor($$source: Partial<ProposedPlanCommentUpdate> = {}) {
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProposedPlanCommentUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): ProposedPlanCommentUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProposedPlanCommentUpdate($$parsedSource as Partial<ProposedPlanCommentUpdate>);
    }
}

export class ProposedPlanSourceRef {
    "threadId"?: string;
    "itemId": string;
    "payloadId"?: string;
    "title"?: string;

    /** Creates a new ProposedPlanSourceRef instance. */
    constructor($$source: Partial<ProposedPlanSourceRef> = {}) {
        if (!("itemId" in $$source)) {
            this["itemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProposedPlanSourceRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ProposedPlanSourceRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProposedPlanSourceRef($$parsedSource as Partial<ProposedPlanSourceRef>);
    }
}

/**
 * Thread represents a conversation thread.
 * 
 * The shape changed at migration v13: ProjectPath is no longer persisted on
 * threads (ProjectID is the FK to the projects table), InteractionMode is
 * renamed to Mode, and three new per-thread composer controls
 * (ReasoningEffort, FastMode, ContextWindow) are persisted so two threads
 * sharing a project can diverge on these axes.
 */
export class Thread {
    "id": string;
    "projectId": string;
    "projectPath": string;
    "title": string;
    "provider": string;
    "model": string;
    "workspacePath": string;
    "worktreePath"?: string;
    "branch"?: string;
    "sessionRef"?: string;
    "pendingForkRef"?: string;
    "mode": string;
    "reasoningEffort": string;
    "fastMode": boolean;
    "contextWindow": number;
    "autoCompactStandardPercent": number;
    "autoCompactExtendedPercent": number;

    /**
     * RuntimeMode is one of provider.RuntimeMode's three values. Kept as
     * a plain string on the struct so store/ doesn't import provider/
     * (which would create a cycle) — provider.NormalizeRuntimeMode is the
     * authoritative normalizer at the binding boundary.
     */
    "runtimeMode": string;
    "discussionId"?: string;
    "parentThreadId"?: string;
    "forkedFromThreadId"?: string;
    "lastTokenUsage"?: string;
    "createdAt": number;
    "updatedAt": number;

    /**
     * LatestTurnCompletedAt is the newest completed turn timestamp for
     * sidebar read-state. Unlike UpdatedAt, it ignores metadata-only changes
     * such as session refs, title/model changes, and settings edits.
     */
    "latestTurnCompletedAt"?: number | null;
    "archived": boolean;

    /**
     * LastReadAt is the Unix-ms timestamp of when the user last viewed
     * the thread. NULL (nil) means "never tracked" and is treated as
     * read by the UI so pre-migration rows don't all show as unread on
     * first launch. Set by MarkThreadRead, stamped to zero by
     * MarkThreadUnread, and auto-refreshed when the user switches into a
     * thread.
     */
    "lastReadAt"?: number | null;

    /**
     * PinnedAt is the Unix-ms timestamp of when the user pinned the
     * thread. NULL (nil) = unpinned. Pinned threads sort into a
     * dedicated tier above needs-attention in the sidebar. Set by
     * PinThread; cleared by UnpinThread.
     */
    "pinnedAt"?: number | null;

    /**
     * HasActionableProposedPlan is derived for sidebar boot state. It is
     * true when the latest assistant proposed plan is completed and has
     * not been implemented yet. It is not a persisted threads column.
     */
    "hasActionableProposedPlan": boolean;

    /**
     * HasIncompleteTurn is derived from the newest unseen turn row. A
     * newest turn with completed_at=NULL and started_at newer than
     * last_read_at means the prior provider process died or was closed
     * mid-turn, so the sidebar should show Interrupted, not live Working.
     * It is not a persisted threads column.
     */
    "hasIncompleteTurn": boolean;

    /** Creates a new Thread instance. */
    constructor($$source: Partial<Thread> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("workspacePath" in $$source)) {
            this["workspacePath"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("reasoningEffort" in $$source)) {
            this["reasoningEffort"] = "";
        }
        if (!("fastMode" in $$source)) {
            this["fastMode"] = false;
        }
        if (!("contextWindow" in $$source)) {
            this["contextWindow"] = 0;
        }
        if (!("autoCompactStandardPercent" in $$source)) {
            this["autoCompactStandardPercent"] = 0;
        }
        if (!("autoCompactExtendedPercent" in $$source)) {
            this["autoCompactExtendedPercent"] = 0;
        }
        if (!("runtimeMode" in $$source)) {
            this["runtimeMode"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("archived" in $$source)) {
            this["archived"] = false;
        }
        if (!("hasActionableProposedPlan" in $$source)) {
            this["hasActionableProposedPlan"] = false;
        }
        if (!("hasIncompleteTurn" in $$source)) {
            this["hasIncompleteTurn"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thread instance from a string or object.
     */
    static createFrom($$source: any = {}): Thread {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Thread($$parsedSource as Partial<Thread>);
    }
}

/**
 * ThreadMessageHit is one hit from a global message search. The result set is
 * designed for an interactive UI: it pairs the thread's display title with the
 * specific item's kind + summary so users can jump directly to the matching
 * turn.
 */
export class ThreadMessageHit {
    "threadId": string;
    "threadTitle": string;
    "provider": string;
    "itemId": string;
    "turnIndex": number;
    "itemKind": string;
    "itemRole": string;

    /**
     * Summary is the item's stored summary field, truncated to the preview
     * budget. The frontend can highlight the query within it.
     */
    "summary": string;

    /**
     * MatchType reports whether the hit came from the thread title or from
     * a specific item's summary. Both are bundled into one result set so
     * callers can render a unified list.
     * "title" or "item"
     */
    "matchType": string;

    /** Creates a new ThreadMessageHit instance. */
    constructor($$source: Partial<ThreadMessageHit> = {}) {
        if (!("threadId" in $$source)) {
            this["threadId"] = "";
        }
        if (!("threadTitle" in $$source)) {
            this["threadTitle"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("itemId" in $$source)) {
            this["itemId"] = "";
        }
        if (!("turnIndex" in $$source)) {
            this["turnIndex"] = 0;
        }
        if (!("itemKind" in $$source)) {
            this["itemKind"] = "";
        }
        if (!("itemRole" in $$source)) {
            this["itemRole"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("matchType" in $$source)) {
            this["matchType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadMessageHit instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreadMessageHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadMessageHit($$parsedSource as Partial<ThreadMessageHit>);
    }
}

/**
 * Turn is one row in the turns table — a record of a single user → assistant
 * round-trip on a thread.
 * 
 * CompletedAt is a pointer because NULL is load-bearing on the latest
 * turn row: it means "in-flight or crashed mid-turn." We never write a
 * synthetic CompletedAt just to dismiss that latest stuck row. Older
 * NULL rows followed by newer turns are obsolete crash/error residue
 * and may be repaired by migration. The frontend treats a NULL
 * CompletedAt on rehydration as "interrupted," separate from the
 * live-push "provider:turn_started" path that drives the working
 * indicator.
 * 
 * See docs/architecture/turn-lifecycle.md §Turn lifecycle for the full
 * mental model and docs/architecture/invariants.md #22-24 for the rules
 * that depend on this shape.
 */
export class Turn {
    "turnId": string;
    "threadId": string;
    "turnIndex": number;
    "startedAt": number;
    "completedAt"?: number | null;
    "stopReason"?: string;
    "assistantMessageId"?: string;
    "tokenUsageJson"?: string;
    "errorMessage"?: string;

    /** Creates a new Turn instance. */
    constructor($$source: Partial<Turn> = {}) {
        if (!("turnId" in $$source)) {
            this["turnId"] = "";
        }
        if (!("threadId" in $$source)) {
            this["threadId"] = "";
        }
        if (!("turnIndex" in $$source)) {
            this["turnIndex"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Turn instance from a string or object.
     */
    static createFrom($$source: any = {}): Turn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Turn($$parsedSource as Partial<Turn>);
    }
}

// Private type creation functions
const $$createType0 = DiscussionParticipant.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = DiscussionSettings.createFrom;
const $$createType3 = Item.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Project.createFrom;
