// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * AccountInfo describes the authenticated Claude account surfaced through
 * the `system/init` message. Subscription type and token source fields are
 * populated only when the CLI includes them; older CLI versions or
 * unauthenticated invocations may leave them empty.
 */
export class AccountInfo {
    /**
     * Creates a new AccountInfo instance.
     * @param {Partial<AccountInfo>} [$$source = {}] - The source object to create the AccountInfo.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subscriptionType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tokenSource"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["apiProvider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountInfo(/** @type {Partial<AccountInfo>} */($$parsedSource));
    }
}

/**
 * ApprovalResponse is sent back to the provider.
 */
export class ApprovalResponse {
    /**
     * Creates a new ApprovalResponse instance.
     * @param {Partial<ApprovalResponse>} [$$source = {}] - The source object to create the ApprovalResponse.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * Codex-native: "accept", "acceptForSession", "decline", "cancel"
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * for user-input responses
             * @member
             * @type {{ [_ in string]?: UserInputAnswer } | undefined}
             */
            this["answers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * for granted permissions
             * @member
             * @type {PermissionProfile | null | undefined}
             */
            this["permissions"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "turn"|"session" for permissions
             * @member
             * @type {string | undefined}
             */
            this["scope"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * for MCP elicitation responses
             * @member
             * @type {ElicitationResolution | null | undefined}
             */
            this["elicitation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * UpdatedInput replaces the original tool input when an approval is granted.
             * Only meaningful for allow decisions; ignored on deny. Opaque JSON — the
             * shape mirrors the tool's input schema, which is provider-specific.
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["updatedInput"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * UpdatedPermissions mirrors the Claude SDK's `updatedPermissions` field on
             * allow decisions: a JSON array of PermissionUpdate objects used to broaden
             * or narrow the session's permission scope. Ignored on deny.
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["updatedPermissions"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApprovalResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField2_0($$parsedSource["answers"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField3_0($$parsedSource["permissions"]);
        }
        if ("elicitation" in $$parsedSource) {
            $$parsedSource["elicitation"] = $$createField5_0($$parsedSource["elicitation"]);
        }
        return new ApprovalResponse(/** @type {Partial<ApprovalResponse>} */($$parsedSource));
    }
}

/**
 * ElicitationResolution carries the MCP elicitation response fields.
 */
export class ElicitationResolution {
    /**
     * Creates a new ElicitationResolution instance.
     * @param {Partial<ElicitationResolution>} [$$source = {}] - The source object to create the ElicitationResolution.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["content"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {json$0.RawMessage | undefined}
             */
            this["meta"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ElicitationResolution instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ElicitationResolution}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ElicitationResolution(/** @type {Partial<ElicitationResolution>} */($$parsedSource));
    }
}

/**
 * FileSystemPermissions controls filesystem access.
 */
export class FileSystemPermissions {
    /**
     * Creates a new FileSystemPermissions instance.
     * @param {Partial<FileSystemPermissions>} [$$source = {}] - The source object to create the FileSystemPermissions.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["read"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["write"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileSystemPermissions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileSystemPermissions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("read" in $$parsedSource) {
            $$parsedSource["read"] = $$createField0_0($$parsedSource["read"]);
        }
        if ("write" in $$parsedSource) {
            $$parsedSource["write"] = $$createField1_0($$parsedSource["write"]);
        }
        return new FileSystemPermissions(/** @type {Partial<FileSystemPermissions>} */($$parsedSource));
    }
}

/**
 * ModelInfo describes a model available from a provider.
 */
export class ModelInfo {
    /**
     * Creates a new ModelInfo instance.
     * @param {Partial<ModelInfo>} [$$source = {}] - The source object to create the ModelInfo.
     */
    constructor($$source = {}) {
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["capabilities"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField3_0($$parsedSource["capabilities"]);
        }
        return new ModelInfo(/** @type {Partial<ModelInfo>} */($$parsedSource));
    }
}

/**
 * NetworkPermissions controls network access.
 */
export class NetworkPermissions {
    /**
     * Creates a new NetworkPermissions instance.
     * @param {Partial<NetworkPermissions>} [$$source = {}] - The source object to create the NetworkPermissions.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["enabled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkPermissions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkPermissions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkPermissions(/** @type {Partial<NetworkPermissions>} */($$parsedSource));
    }
}

/**
 * PermissionProfile describes requested or granted permissions.
 */
export class PermissionProfile {
    /**
     * Creates a new PermissionProfile instance.
     * @param {Partial<PermissionProfile>} [$$source = {}] - The source object to create the PermissionProfile.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {NetworkPermissions | null | undefined}
             */
            this["network"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FileSystemPermissions | null | undefined}
             */
            this["fileSystem"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionProfile}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField0_0($$parsedSource["network"]);
        }
        if ("fileSystem" in $$parsedSource) {
            $$parsedSource["fileSystem"] = $$createField1_0($$parsedSource["fileSystem"]);
        }
        return new PermissionProfile(/** @type {Partial<PermissionProfile>} */($$parsedSource));
    }
}

/**
 * ProviderStatus describes whether a provider binary is available and its version.
 */
export class ProviderStatus {
    /**
     * Creates a new ProviderStatus instance.
     * @param {Partial<ProviderStatus>} [$$source = {}] - The source object to create the ProviderStatus.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("binaryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["binaryPath"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "ready", "not_found", "error"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderStatus(/** @type {Partial<ProviderStatus>} */($$parsedSource));
    }
}

/**
 * UserInputAnswer stores one or more selected answers for a question.
 * It marshals as a string for single-select answers and a string array for
 * multi-select answers to match the frontend/Forge contract.
 * @typedef {any} UserInputAnswer
 */

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = PermissionProfile.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = ElicitationResolution.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = NetworkPermissions.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = FileSystemPermissions.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
