// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Distro describes one WSL distribution as reported by wsl.exe -l -v.
 * 
 * The wsl.exe output is fixed-width, with a leading "* " marker on the
 * default distro and a single character of indent for non-defaults.
 * Version is parsed numerically (1 for WSL1, 2 for WSL2). State is the
 * raw column ("Running", "Stopped", "Installing", etc) — we don't
 * normalise it because WSL has added new states over time and a literal
 * pass-through is robust to that.
 * 
 * JSON tags: lowercased to match the rest of the wire-bound types in
 * this codebase (see settings.NetworkSettings, store.Item, etc). The
 * App method ListWSLDistros returns []Distro, which the Wails binding
 * generator surfaces to TypeScript using these tag names.
 */
export class Distro {
    "name": string;
    "default": boolean;
    "version": number;
    "state": string;

    /** Creates a new Distro instance. */
    constructor($$source: Partial<Distro> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = false;
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Distro instance from a string or object.
     */
    static createFrom($$source: any = {}): Distro {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Distro($$parsedSource as Partial<Distro>);
    }
}
