// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Chunk is the patch bytes [Offset, NextOffset) of a Diff. EOF reports
 * that NextOffset is the end of the patch.
 */
export class Chunk {
    "data": string;
    "offset": number;
    "nextOffset": number;
    "eof": boolean;

    /** Creates a new Chunk instance. */
    constructor($$source: Partial<Chunk> = {}) {
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("nextOffset" in $$source)) {
            this["nextOffset"] = 0;
        }
        if (!("eof" in $$source)) {
            this["eof"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chunk instance from a string or object.
     */
    static createFrom($$source: any = {}): Chunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chunk($$parsedSource as Partial<Chunk>);
    }
}

/**
 * Commit is one row of the review pane's per-commit selector.
 */
export class Commit {
    "sha": string;
    "shortSha": string;
    "subject": string;
    "author": string;
    "authoredAt": number;

    /** Creates a new Commit instance. */
    constructor($$source: Partial<Commit> = {}) {
        if (!("sha" in $$source)) {
            this["sha"] = "";
        }
        if (!("shortSha" in $$source)) {
            this["shortSha"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("authoredAt" in $$source)) {
            this["authoredAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Commit instance from a string or object.
     */
    static createFrom($$source: any = {}): Commit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Commit($$parsedSource as Partial<Commit>);
    }
}
