package harnessrpc

import (
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"agent-overflow/internal/harness"
	"agent-overflow/internal/harness/scenario"
)

// SoakConfig is the fixture and scenario vocabulary of the soak rig. Root
// owns when the autopilot runs; this package owns how its harness state is
// installed.
type SoakConfig struct {
	ScenarioName      string
	ScenarioFileName  string
	ProjectName       string
	IdleThreadTitle   string
	ActiveThreadTitle string
	Prompt            string
}

// ArmSoakSteadyState installs the soak scenario, reuses or creates its two
// threads, and starts the never-completing turn on the active thread.
func ArmSoakSteadyState(receiver *Harness, config SoakConfig) error {
	if receiver == nil || receiver.config.Host == nil {
		return fmt.Errorf("soak harness host unavailable")
	}
	if err := installSoakScenario(receiver, config); err != nil {
		return err
	}
	threadID, err := ensureSoakThreads(receiver, config)
	if err != nil {
		return err
	}
	log.Printf("soak: arming live background-agent turn on thread %s", threadID)
	if err := receiver.config.Host.SendMessage(threadID, config.Prompt); err != nil {
		return fmt.Errorf("send soak prompt: %w", err)
	}
	return nil
}

func installSoakScenario(receiver *Harness, config SoakConfig) error {
	spec := HarnessScenarioSpec{Name: config.ScenarioName}
	override := filepath.Join(receiver.config.DataRoot, config.ScenarioFileName)
	switch raw, err := os.ReadFile(override); {
	case err == nil:
		log.Printf("soak: using scenario override %s", override)
		spec = HarnessScenarioSpec{Scenario: json.RawMessage(raw)}
	case !errors.Is(err, os.ErrNotExist):
		return fmt.Errorf("read scenario override %s: %w", override, err)
	}
	if _, err := receiver.HarnessSetScenario(spec); err != nil {
		return fmt.Errorf("install soak scenario: %w", err)
	}
	return nil
}

func ensureSoakThreads(receiver *Harness, config SoakConfig) (string, error) {
	threads, err := receiver.config.Host.ListVisibleThreads()
	if err != nil {
		return "", fmt.Errorf("list threads: %w", err)
	}
	for _, thread := range threads {
		if thread.Title == config.ActiveThreadTitle {
			return thread.ID, nil
		}
	}
	if len(threads) > 0 {
		return "", fmt.Errorf(
			"soak data dir holds %d thread(s) but none titled %q; "+
				"delete the data root to reseed, or start the turn by hand",
			len(threads), config.ActiveThreadTitle)
	}

	result, err := receiver.seed(HarnessSeedSpec{Projects: []HarnessSeedProject{{
		Name: config.ProjectName,
		Repo: &harness.RepoSpec{Commits: []harness.CommitSpec{{
			Message: "soak workspace",
			Files: map[string]string{
				"README.md": "# soak workspace\n\nGenerated by the soak rig (docs/architecture/soak-rig.md).\n",
			},
		}}},
		Threads: []HarnessSeedThread{
			{
				Title:    config.IdleThreadTitle,
				Provider: "claude",
				Turns: []HarnessSeedTurn{{
					UserText: "What does this workspace contain?",
					Items: []HarnessSeedItem{{
						Kind:    "assistant_text",
						Summary: "One README. Nothing is running in this thread — it is the idle half of the soak fixture.",
					}},
				}},
			},
			{
				Title:    config.ActiveThreadTitle,
				Provider: "claude",
				Turns: []HarnessSeedTurn{{
					UserText: "Ready when you are.",
					Items: []HarnessSeedItem{{
						Kind:    "assistant_text",
						Summary: "Standing by. Send the word and I will fan out three background agents.",
					}},
				}},
			},
		},
	}}})
	if err != nil {
		return "", fmt.Errorf("seed soak fixtures: %w", err)
	}
	if len(result.Projects) != 1 || len(result.Projects[0].ThreadIDs) != 2 {
		return "", fmt.Errorf("seed soak fixtures: unexpected result %+v", result)
	}
	return result.Projects[0].ThreadIDs[1], nil
}

// ValidateSoakScenario proves the named embedded scenario exists and is a
// Claude script before the delayed autopilot needs it.
func ValidateSoakScenario(name string) error {
	_, definition, err := scenario.LoadLibrary(name)
	if err != nil {
		return err
	}
	if definition.Provider != scenario.ProviderClaude {
		return fmt.Errorf("scenario %q is a %s script, want claude", name, definition.Provider)
	}
	return nil
}
