//go:build !windows

package terminal

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// AppImage runtime markers. The type-2 AppImage runtime exports these
// four before exec'ing AppRun: APPIMAGE (the .AppImage file), APPDIR (the
// squashfs mount root, e.g. /tmp/.mount_agentXXXXXX), ARGV0 (the argv[0]
// the user invoked), and OWD (the original working directory). They
// describe how *this* process was launched; a shell we spawn is not that
// process, and tooling that branches on them (or on a PATH pointing into
// a mount that disappears when the app exits) misbehaves.
const (
	envAppImage = "APPIMAGE"
	envAppDir   = "APPDIR"
	envArgv0    = "ARGV0"
	envOWD      = "OWD"
)

// appImageMarkers are dropped wholesale from a spawned terminal's
// environment when the app is running from an AppImage.
var appImageMarkers = []string{envAppImage, envAppDir, envArgv0, envOWD}

// appImageSearchPathVars are the colon-separated search paths an AppImage
// launch can have mount-local segments prepended to (AppRun hooks
// generated by linuxdeploy plugins do this). Only the segments under the
// APPDIR mount are removed; the user's own entries survive in order. Add
// a variable here if a future AppRun hook prepends to another list.
var appImageSearchPathVars = []string{"PATH", "LD_LIBRARY_PATH"}

// terminalCapabilityVars are replaced rather than inherited — see
// normalizeTerminalEnv.
var terminalCapabilityVars = []string{"TERM", "COLORTERM"}

// normalizeTerminalEnv returns a private environment slice describing the
// PTY xterm.js renders, with the launching process's own packaging
// artifacts removed.
//
// Terminal capabilities: desktop app launches commonly inherit no TERM (or
// TERM=dumb), especially from Finder/launchd on macOS; interactive shells
// then disable the cursor movement and line-clearing sequences their editors
// need, leaving stale prompt glyphs smeared across the screen. Always
// replacing these two keys is intentional — values inherited from the process
// that launched Agent Overflow (for example screen-256color from tmux)
// describe that parent terminal, not this PTY, and xterm.js supports the
// xterm-256color capability set and true color on every platform where this
// POSIX implementation runs.
//
// AppImage: when and only when the AppImage markers are present, the markers
// are dropped and the mount's segments are stripped out of the search paths,
// so the user's commands resolve binaries and libraries against their real
// system instead of a read-only squashfs that vanishes on app exit. A dev,
// .deb, or macOS launch carries no markers and comes back byte-identical.
//
// The Windows launcher uses process_windows.go and never reaches this path;
// its terminals run in the WSL-side Linux backend.
func normalizeTerminalEnv(base []string) []string {
	if base == nil {
		base = os.Environ()
	}
	appImage := detectAppImageRuntime(base)

	out := make([]string, 0, len(base)+2)
	for _, entry := range base {
		key, value, ok := strings.Cut(entry, "=")
		if !ok {
			// Not a KEY=VALUE pair; pass it through untouched rather than
			// guessing at its shape.
			out = append(out, entry)
			continue
		}
		if slices.Contains(terminalCapabilityVars, key) {
			continue
		}
		scrubbed, keep := appImage.scrub(entry, key, value)
		if !keep {
			continue
		}
		out = append(out, scrubbed)
	}
	return append(out, "TERM=xterm-256color", "COLORTERM=truecolor")
}

// appImageRuntime is the AppImage-launch view of an environment.
type appImageRuntime struct {
	// active reports whether the environment came from an AppImage launch
	// (either marker set). Nothing is scrubbed when it is false.
	active bool
	// mount is the cleaned APPDIR path with no trailing separator, or ""
	// when APPDIR is absent or is the filesystem root. A "/" mount would
	// make every absolute path look mount-local, so it disables path
	// stripping instead of emptying the user's search paths.
	mount string
}

func detectAppImageRuntime(env []string) appImageRuntime {
	var rt appImageRuntime
	for _, entry := range env {
		key, value, ok := strings.Cut(entry, "=")
		if !ok || value == "" {
			continue
		}
		switch key {
		case envAppImage:
			rt.active = true
		case envAppDir:
			rt.active = true
			rt.mount = strings.TrimSuffix(filepath.Clean(value), "/")
		}
	}
	return rt
}

// scrub maps one KEY=VALUE entry to the value a spawned terminal should
// see. keep=false means the variable is dropped entirely.
func (rt appImageRuntime) scrub(entry, key, value string) (string, bool) {
	if !rt.active {
		return entry, true
	}
	if slices.Contains(appImageMarkers, key) {
		return "", false
	}
	if rt.mount == "" || !slices.Contains(appImageSearchPathVars, key) {
		return entry, true
	}
	kept := rt.stripMountSegments(value)
	switch kept {
	case value:
		return entry, true
	case "":
		// Every segment was mount-local. An empty value is not the same as
		// an unset one: an empty PATH has implementation-defined lookup
		// behaviour and an empty LD_LIBRARY_PATH is a pointless extra
		// loader search. Unset the variable so the child falls back to the
		// system default.
		return "", false
	}
	return key + "=" + kept, true
}

// stripMountSegments removes the segments of a colon-separated search path
// that live inside the AppImage mount, preserving the order of the rest.
func (rt appImageRuntime) stripMountSegments(list string) string {
	segments := strings.Split(list, ":")
	kept := make([]string, 0, len(segments))
	for _, segment := range segments {
		if rt.underMount(segment) {
			continue
		}
		kept = append(kept, segment)
	}
	return strings.Join(kept, ":")
}

// underMount reports whether a search-path segment resolves inside the
// AppImage mount. Matching is on path boundaries, never substrings: the
// mount root and everything beneath it match, while a sibling whose name
// merely starts with the mount path (/tmp/.mount_abc123-backup) and a path
// that contains it mid-segment (/opt/tmp/.mount_abc123/bin) do not.
func (rt appImageRuntime) underMount(segment string) bool {
	if segment == "" || rt.mount == "" {
		return false
	}
	clean := filepath.Clean(segment)
	return clean == rt.mount || strings.HasPrefix(clean, rt.mount+string(filepath.Separator))
}
