// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as windowgeom$0 from "../windowgeom/models.js";

/**
 * Claude Code cross-session messaging — the machine-wide peer inbox.
 * 
 * Claude Code 2.1.224+ lets one Claude session on a host discover
 * (`ListAgents`) and address (`SendMessage`) another. A delivered peer
 * message arrives in the recipient as a USER-ROLE turn the recipient
 * never asked for, wrapped in `<cross-session-message from="..."
 * from-name="...">`, and the model answers it like any other prompt.
 * 
 * Two things have to be true for an Agent Overflow thread to take part,
 * and they are two different mechanisms, which is why this is one struct
 * rather than two settings:
 * 
 *  1. **The inbox has to be bound.** It is gated behind a GrowthBook
 *     experiment with one environment override, `CLAUDE_CODE_HARBOR_KITE`
 *     — a parsed boolean, so "0" and "" are OFF. With the gate open the
 *     session binds a unix socket and `system/init` carries
 *     `messaging_socket_path`; without it the CLI logs
 *     "cross-session messaging gate off" and binds nothing, which no
 *     settings key can undo (spike-verified 2.1.237, /tmp/spike-xsession).
 *     That is what `Enabled` controls.
 *  2. **Delivery policy.** Once bound, the `crossSessionInbound` key in
 *     the `--settings` block decides what happens to an arriving message.
 *     That is `Inbound`.
 * 
 * Enabled is NOT the only thing that can bind the inbox, which is why
 * "off" is a stated refusal rather than silence. The gate variable is
 * only an OVERRIDE: `tengu_harbor_kite` can bind the socket remotely for
 * a user who never opted in here, and `tengu_harbor_kite_mode_emit` —
 * which has no environment override at all — turns on the permission-
 * class attestation the CLI's unset-key default (mode parity) reads. A
 * disabled AO session therefore spawns with an explicit
 * `"crossSessionInbound":"refuse"`, so a remotely bound inbox still
 * delivers nothing. See claudeCrossSessionInbound in
 * internal/provider/claude/options.go, which is the wall.
 * 
 * Discovery is keyed on a SHARED `CLAUDE_CONFIG_DIR` — the peer registry
 * is `<CLAUDE_CONFIG_DIR>/sessions/<pid>.json`. Agent Overflow's Claude
 * sessions deliberately CLEAR that variable (claude.NewSession's
 * `UnsetEnv`), so they land in the user's own `~/.claude` and can see —
 * and be seen by — the user's terminal sessions, provided those also run
 * with the gate open.
 */
export class ClaudeCrossSession {
    /**
     * Enabled opens the gate: the spawn exports
     * CLAUDE_CODE_HARBOR_KITE=1 and passes `--name`, so the session is
     * discoverable and addressable by other Claude sessions on this
     * machine. Default FALSE — letting another process start a turn in
     * the user's thread is opt-in, and the CLI's own default is an
     * experiment flag we neither control nor want to inherit silently.
     */
    "enabled"?: boolean;

    /**
     * Inbound is the delivery policy, meaningful only when Enabled.
     * Empty means EffectiveInbound's default, which is Accept — see
     * there for why "unset" is never sent on the wire.
     */
    "inbound"?: string;

    /** Creates a new ClaudeCrossSession instance. */
    constructor($$source: Partial<ClaudeCrossSession> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeCrossSession instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaudeCrossSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeCrossSession($$parsedSource as Partial<ClaudeCrossSession>);
    }
}

/**
 * ClaudeSubagentLimits caps Claude Code's subagent fan-out for the
 * sessions Agent Overflow spawns. Both are delivered as environment
 * variables inside the `--settings` env block, which outranks the
 * subprocess environment (`flagSettings` > `userSettings`), and both are
 * `int({min:1, digitsOnly:true})` on the CLI side — so ZERO means "send
 * nothing and let the CLI decide" rather than "no subagents".
 * 
 * The CLI's own defaults are not fixed numbers this package can restate:
 * the concurrency default is 20, but the spawn-depth default comes from a
 * remote experiment value with a build-time fallback. Leaving a field at
 * zero is therefore the only honest way to express "whatever the binary
 * decides".
 */
export class ClaudeSubagentLimits {
    /**
     * MaxSpawnDepth → CLAUDE_CODE_MAX_SUBAGENT_SPAWN_DEPTH. How many
     * levels of subagent-spawning-a-subagent the session permits.
     */
    "maxSpawnDepth"?: number;

    /**
     * MaxConcurrent → CLAUDE_CODE_MAX_CONCURRENT_SUBAGENTS. How many
     * subagents may hold a concurrency slot at once.
     */
    "maxConcurrent"?: number;

    /** Creates a new ClaudeSubagentLimits instance. */
    constructor($$source: Partial<ClaudeSubagentLimits> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeSubagentLimits instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaudeSubagentLimits {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeSubagentLimits($$parsedSource as Partial<ClaudeSubagentLimits>);
    }
}

/**
 * ClaudeThinking is the user's extended-thinking preference for the
 * headless Claude sessions Agent Overflow spawns.
 * 
 * BudgetTokens is meaningful ONLY with Mode == budget, and the validators
 * enforce that rather than trusting it: a stored budget beside mode "off"
 * would be a value that reads as configuration and behaves as nothing.
 * 
 * Mode and Display are two independent axes on the CLI side and stay
 * independent here — `thinking_display` alone is an accepted live request
 * (spike-verified 2.1.237) — with one exception the wire imposes: a
 * DISABLED session drops display entirely, so Display beside Mode "off" is
 * inert rather than wrong.
 */
export class ClaudeThinking {
    "mode"?: string;
    "budgetTokens"?: number;
    "display"?: string;

    /** Creates a new ClaudeThinking instance. */
    constructor($$source: Partial<ClaudeThinking> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaudeThinking instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaudeThinking {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaudeThinking($$parsedSource as Partial<ClaudeThinking>);
    }
}

/**
 * EditorSettings groups the open-in-editor preferences. Lives in its
 * own nested object so future fields (custom argv template, last-used
 * editor for analytics, etc.) can land without reshuffling the
 * top-level Settings struct.
 */
export class EditorSettings {
    /**
     * Preference is the editor ID (e.g. "code", "cursor",
     * "env:editor") the user explicitly selected. Empty falls back
     * to the catalog priority order in internal/editor.Resolve.
     */
    "preference": string;

    /** Creates a new EditorSettings instance. */
    constructor($$source: Partial<EditorSettings> = {}) {
        if (!("preference" in $$source)) {
            this["preference"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EditorSettings($$parsedSource as Partial<EditorSettings>);
    }
}

/**
 * NetworkSettings groups LAN-bind preferences for the embedded
 * transport server. Persisted as a nested object so the JSON shape
 * stays stable when more network fields land (origin allow-list,
 * TLS hints, etc.).
 */
export class NetworkSettings {
    /**
     * BindAll, when true, asks the transport server to listen on
     * 0.0.0.0 so other devices on the LAN can reach the app. Default
     * false keeps the bind on 127.0.0.1 — the safe loopback behaviour.
     */
    "bindAll": boolean;

    /** Creates a new NetworkSettings instance. */
    constructor($$source: Partial<NetworkSettings> = {}) {
        if (!("bindAll" in $$source)) {
            this["bindAll"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkSettings($$parsedSource as Partial<NetworkSettings>);
    }
}

/**
 * PromptOverride replaces a provider's built-in system prompt for the
 * models it names. Zero value is inert: a disabled entry, or one with no
 * models, never matches.
 */
export class PromptOverride {
    /**
     * Enabled gates the entry without the user having to delete it.
     */
    "enabled": boolean;

    /**
     * Models holds normalized model slugs WITHOUT a context-tier marker
     * (`claude-opus-5`, not `claude-opus-5[1m]`). Matching normalizes both
     * sides, so a marker that slips in still compares equal.
     */
    "models": string[];

    /**
     * Prompt is the replacement text, placeholders unrendered.
     */
    "prompt": string;

    /** Creates a new PromptOverride instance. */
    constructor($$source: Partial<PromptOverride> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptOverride instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptOverride {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField1_0($$parsedSource["models"]);
        }
        return new PromptOverride($$parsedSource as Partial<PromptOverride>);
    }
}

/**
 * ProviderEnvVar is one user-defined environment variable applied to the
 * provider subprocesses Agent Overflow spawns for that provider — the chat
 * session, the account/identity/rate-limit probes, and the text-generation
 * CLI. Use cases are backend redirection (`ANTHROPIC_BASE_URL`) and corporate
 * proxy configuration (`HTTPS_PROXY`, `NO_PROXY`, custom CA bundles).
 * 
 * SECURITY: Value is persisted verbatim in settings.json, in plaintext, like
 * every other field on Settings — see the SECURITY NOTE on the Settings
 * struct. Sensitive=true is a DISCLOSURE control, not an encryption one: it
 * keeps the value off the `GetSettings` wire shape (see RedactProviderEnvVars)
 * so a LAN-attached token-holder can't harvest it, and the UI renders it
 * masked. It does not make settings.json a safe place for a long-lived
 * credential.
 * 
 * List, not map[string]string, deliberately:
 * 
 *   - A map cannot carry the per-variable Sensitive flag without becoming a
 *     map of structs, at which point it has a list's shape and a map's
 *     drawbacks.
 *   - A map silently collapses duplicate names at JSON decode (last wins), so
 *     `PROXY` typed twice would be applied without the user ever learning one
 *     of their two entries was dropped. A list carries both to the validator,
 *     which rejects the pair with a message naming the collision.
 *   - Order is the user's; a map has none, so the settings UI would reshuffle
 *     rows on every save.
 * 
 * Application order is irrelevant to behaviour because duplicates (including
 * case-insensitive ones) are rejected before anything is spawned.
 */
export class ProviderEnvVar {
    "name": string;
    "value": string;
    "sensitive"?: boolean;

    /** Creates a new ProviderEnvVar instance. */
    constructor($$source: Partial<ProviderEnvVar> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderEnvVar instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderEnvVar {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderEnvVar($$parsedSource as Partial<ProviderEnvVar>);
    }
}

/**
 * RemoteEndpoint is one stored `--connect` target. The desktop binary
 * takes a URL+token from this list (or from --connect on the command
 * line) and points the Wails webview at the remote backend instead of
 * booting a local transport.
 * 
 * IDs are opaque strings the settings layer mints; the UI keys list
 * rows by ID so a rename/edit doesn't require re-targeting the
 * underlying record. LastUsedAt is updated by the settings UI's
 * "Connect" affordance — the settings layer doesn't observe runtime
 * connection state.
 * 
 * SECURITY: this struct is the on-disk persistence shape — it carries
 * the plaintext Token because the launcher needs it when the user
 * chooses to --connect. It MUST NOT be returned directly to the wire;
 * the bound App methods in app_remote.go project it onto
 * RemoteEndpointSummary (no Token field) before crossing the
 * transport boundary, with a single explicit GetRemoteEndpointToken
 * path for token retrieval. Adding a JSON tag here that hides Token
 * would break persistence; the protection lives at the wire shape
 * instead.
 */
export class RemoteEndpoint {
    "id": string;
    "name": string;
    "url": string;
    "token": string;
    "lastUsedAt"?: number;

    /** Creates a new RemoteEndpoint instance. */
    constructor($$source: Partial<RemoteEndpoint> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteEndpoint instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteEndpoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteEndpoint($$parsedSource as Partial<RemoteEndpoint>);
    }
}

/**
 * RemoteEndpointSummary is the token-redacted wire shape returned by
 * the bound `ListRemoteEndpoints` / `AddRemoteEndpoint` /
 * `UpdateRemoteEndpoint` App methods. The Token field is structurally
 * absent so a LAN-attached token-holder cannot harvest credentials for
 * other backends through the bulk list path — token retrieval goes
 * through the dedicated server-logged GetRemoteEndpointToken method.
 * 
 * Keeping the projection here (rather than at the App boundary) makes
 * it impossible for a future field on RemoteEndpoint that needs
 * special handling to slip onto the wire without going through this
 * type.
 */
export class RemoteEndpointSummary {
    "id": string;
    "name": string;
    "url": string;
    "lastUsedAt"?: number;

    /** Creates a new RemoteEndpointSummary instance. */
    constructor($$source: Partial<RemoteEndpointSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteEndpointSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteEndpointSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteEndpointSummary($$parsedSource as Partial<RemoteEndpointSummary>);
    }
}

/**
 * RetentionSettings groups TTL cleanup preferences for the background
 * sweeper that prunes stale threads (and their on-disk side effects)
 * plus dated provider-event log files and bug-report bookmark files.
 * Persisted as a nested object so future retention knobs (per-resource
 * overrides, exemption lists) can land without reshuffling Settings.
 */
export class RetentionSettings {
    /**
     * Days is the age threshold in days. Threads whose updated_at is
     * older than now-(Days*24h) are eligible for sweep, as are dated
     * provider-event log files and bug-report bookmark files. A value
     * of 0 disables the sweep entirely.
     */
    "days": number;

    /** Creates a new RetentionSettings instance. */
    constructor($$source: Partial<RetentionSettings> = {}) {
        if (!("days" in $$source)) {
            this["days"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RetentionSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): RetentionSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RetentionSettings($$parsedSource as Partial<RetentionSettings>);
    }
}

/**
 * Settings holds all user-configurable preferences.
 */
export class Settings {
    /**
     * SchemaVersion is the version of the on-disk shape this struct
     * expects. Older files (or files written before versioning) load as
     * SchemaVersion=0 and the Service treats them identically to
     * CurrentSchemaVersion until a future shape change introduces a
     * migration step. Never written by users; always overwritten to
     * CurrentSchemaVersion on any save via writeSparse.
     */
    "$schemaVersion"?: number;

    /**
     * NOTE: "theme" used to live here and is RETIRED (see
     * retiredSettingsFieldNames and docs/architecture/theme-system.md §6.2). The
     * light/dark mode is a property of the CLIENT MACHINE, not of a backend,
     * so it moved to <configDir>/themes/appearance.json. The old value is
     * CONSUMED ONCE at boot (initThemeDirectory reads it raw via
     * RetiredString) and DROPPED by the next sparse write — a retired field
     * is excluded from unknown-field preservation, so nothing republishes
     * it. Boot ordering is what makes that safe, and it is load-bearing.
     */
    "timestampFormat": string;

    /**
     * SansFont and MonoFont select the typefaces wired into the
     * `--font-sans` and `--font-mono` CSS variables on the frontend.
     * Each is one of {"geist", "hack-nerd", "system"}. "geist" is the
     * eagerly-bundled default; "hack-nerd" lazy-loads a separate woff2
     * chunk so users on the default never pay its bundle cost; "system"
     * falls through to the OS fallback chain and adds zero weight.
     */
    "sansFont": string;
    "monoFont": string;
    "fontSize": number;
    "recentWorkspaces": string[];
    "diffWordWrap": boolean;

    /**
     * CollapseDiffPreviews starts chat-timeline file-edit diff cards
     * collapsed (header row only). It controls the default state, not
     * capability: cards stay individually expandable either way.
     */
    "collapseDiffPreviews": boolean;
    "streamingEnabled": boolean;

    /**
     * LowPowerMode minimizes rendering work for GPU-constrained
     * environments (weak machines, or a game/GPU-heavy app running
     * alongside): scroll placement is instant instead of spring-gliding,
     * streamed text reveals per wire chunk instead of animating, and the
     * activity shimmer is suppressed. Display-only — content and timing
     * are unaffected.
     */
    "lowPowerMode": boolean;

    /**
     * BrowserEnabled exposes Agent Overflow's built-in browser MCP tools to
     * headless Claude and Codex sessions. BrowserShowWindow selects a visible
     * full Chrome window; BrowserPersistSiteData checkpoints encrypted cookies
     * and local storage per workspace. All three default on. Outside-workspace
     * file access is the separate, deliberately off-by-default authority grant.
     */
    "browserEnabled": boolean;
    "browserShowWindow": boolean;
    "browserPersistSiteData": boolean;
    "browserAllowOutsideWorkspace"?: boolean;
    "confirmArchive": boolean;
    "confirmDelete": boolean;
    "claudeBinaryPath": string;
    "codexBinaryPath": string;
    "claudeEnabled": boolean;
    "codexEnabled": boolean;

    /**
     * ClaudeTUIEnabled surfaces the claude-tui provider — the real
     * interactive Claude TUI driven inside a PTY — in the model/provider
     * pickers. It runs Claude's binary under Claude's auth, so
     * ClaudeEnabled gates it too: the frontend offers claude-tui only
     * when BOTH are on (frontend/src/lib/providers/catalog.ts,
     * providerIsEnabled).
     * 
     * Deliberately absent from DefaultSettings, unlike the two fields
     * above: its default is the Go zero value, false (user decision,
     * 2026-08-18). The inversion is the point. Every settings file that
     * exists today predates this key, and an absent key must read as
     * "hidden" so upgrading users get the requested default instead of a
     * provider appearing in their pickers unasked. Defaulting it true
     * would also invert writeSparse — which persists only what differs
     * from DefaultSettings — and make `false` the value that survives a
     * write while `true` was dropped.
     * 
     * Visibility only: an existing claude-tui thread keeps rendering,
     * resuming and sending with this off, exactly as a claude thread does
     * under ClaudeEnabled=false. Nothing in Go reads any of the three.
     */
    "claudeTuiEnabled": boolean;

    /**
     * ClaudeHiddenModels / CodexHiddenModels list catalog model slugs
     * the user has hidden from model pickers. Hide-list semantics:
     * slugs absent from the list — including models a later app update
     * adds to the catalog — stay visible. Hiding is display-only:
     * existing threads on a hidden model keep working, and slug /
     * cost / capability resolution still sees the full catalog. The
     * Claude list applies to both the claude and claude-tui providers
     * (one binary, one catalog). Unknown slugs are kept as-is so a
     * hidden Codex model survives the live catalog being offline.
     */
    "claudeHiddenModels"?: string[];
    "codexHiddenModels"?: string[];

    /**
     * ClaudeCustomEnv / CodexCustomEnv are user-defined environment
     * variables applied to the provider processes Agent Overflow spawns
     * for that provider — chat sessions, account / identity / rate-limit
     * probes, and the text-generation CLI. Applied at spawn, so a change
     * reaches new sessions and probes only. The Claude list also covers
     * claude-tui (one binary, one backend).
     * 
     * Names Agent Overflow pins itself are rejected on save rather than
     * dropped at spawn — see providerenv.go for the shape rules, the
     * reserved names, and why this is a list rather than a map. Sensitive
     * values are redacted out of the GetSettings wire shape; they are NOT
     * encrypted on disk (see the SECURITY NOTE below).
     */
    "claudeCustomEnv"?: ProviderEnvVar[];
    "codexCustomEnv"?: ProviderEnvVar[];

    /**
     * ClaudePromptOverrides / CodexPromptOverrides replace the provider's
     * own system prompt for the models each entry names — Claude via
     * `--system-prompt`, Codex via `baseInstructions`. Read at session
     * spawn, so an edit reaches the next session started and never
     * disturbs a running one. First ENABLED entry whose Models contains
     * the session's normalized model slug wins; the list is per provider
     * because the default prompt is model-shaped on both sides.
     * 
     * Prompt text may carry `{{...}}` placeholders (workdir, git snapshot,
     * platform, model, Claude memory dir) rendered at spawn — see
     * internal/promptoverride, which owns both the match and the render.
     */
    "claudePromptOverrides"?: PromptOverride[];
    "codexPromptOverrides"?: PromptOverride[];

    /**
     * ClaudeDisabledTools / CodexDisabledTools remove built-in tool
     * schemas from the model's context. Provider-wide (not model-scoped)
     * and spawn-only on both sides.
     * 
     * The two lists speak different vocabularies on purpose. Claude has a
     * flat `--disallowedTools` deny list, so entries are RAW TOOL NAMES
     * ("Workflow", "WebSearch") and an unknown name is harmless. Codex has
     * no deny list at all — each entry is a CURATED TOGGLE ID that maps to
     * one or more per-thread config keys (see
     * internal/provider/codex.DisabledToolConfigOverrides, which owns the
     * table and skips ids it does not know). Neither list is enum-validated
     * here: Claude's vocabulary is the CLI's, and duplicating Codex's
     * toggle table into this package (which must not import
     * internal/provider) would give it a second place to drift.
     */
    "claudeDisabledTools"?: string[];
    "codexDisabledTools"?: string[];

    /**
     * ClaudeTodoRemindersDisabled turns off Claude Code's periodic
     * "track your work with the todo tools" nudges by exporting
     * CLAUDE_CODE_TODO_REMINDER_MODE=off into Claude sessions (headless
     * and claude-tui — one binary). Spawn-only, like the tool lists.
     * Default false keeps the vendor's behavior: the CLI nudges only
     * while the todo tools are actually in the session's tool set, so a
     * user who disables the whole todo group needs no reminder setting
     * at all — this exists for the keep-the-tools, lose-the-nudges
     * middle ground. Zero-value default, so it stays out of
     * DefaultSettings by construction.
     */
    "claudeTodoRemindersDisabled"?: boolean;

    /**
     * The Claude-only spawn-time axes delivered through the CLI's
     * `--settings` flagSettings block. None has a CLI flag; the settings
     * key is the delivery mechanism. Shapes, allowed values, validators
     * and the "why claude-tui is excluded" note live in claudesession.go.
     * 
     * Every one of them treats its ZERO VALUE as "say nothing" — the key
     * is omitted from the rendered block and the CLI's own resolution
     * stands. That is what keeps them out of DefaultSettings and makes an
     * absent key in an older settings file read as the CLI default.
     * 
     * Note which fields carry `omitempty` and which do not: it is a no-op
     * on a STRUCT under encoding/json, so writing it there would claim an
     * omission that never happens. The struct-valued axes below spell the
     * tag plainly and state their zero-value meaning in prose instead;
     * only the string-valued ones actually omit.
     * 
     * ClaudeOutputStyle names one of Claude Code's four built-in output
     * styles (Concise / Proactive / Explanatory / Learning).
     */
    "claudeOutputStyle"?: string;

    /**
     * ClaudeCrossSession is the machine-wide peer inbox: whether other
     * Claude sessions on this host may discover and message AO's threads,
     * and what happens to a message that arrives. Shape, allowed values
     * and the reason "hold" is not one of them live in
     * claudecrosssession.go.
     * 
     * It is NOT part of ClaudeSessionAxes below even though half of it
     * rides the same `--settings` block: those axes are spawn-only BY
     * CONSTRUCTION (invisible to PlanLiveUpdate), while this one travels
     * on provider.SessionOptions so a save converges a running session
     * through the ordinary deferred-restart path. The inbox binds once at
     * setup, so a restart is the only way to change it.
     */
    "claudeCrossSession": ClaudeCrossSession;

    /**
     * ClaudeSubagentLimits caps subagent spawn depth and concurrency via
     * CLAUDE_CODE_MAX_SUBAGENT_SPAWN_DEPTH /
     * CLAUDE_CODE_MAX_CONCURRENT_SUBAGENTS in the block's env map.
     */
    "claudeSubagentLimits": ClaudeSubagentLimits;

    /**
     * ClaudeToolMemoryLimit caps the memory cgroup Claude installs for
     * its tool subprocesses (CLAUDE_CODE_TOOL_MEMORY_LIMIT). The CLI
     * implements this by writing a cgroup file under /proc/self/cgroup,
     * so it takes effect only when the backend runs on Linux (including
     * the WSL backend) — on macOS and native Windows the value is inert.
     */
    "claudeToolMemoryLimit"?: string;

    /**
     * ClaudeThinking is the extended-thinking preference for headless
     * Claude sessions: leave it to Claude Code, turn thinking off, or pin
     * a fixed token budget — plus whether thinking text reaches the wire.
     * 
     * It sits beside the four axes above but is NOT one of them: those
     * ride the `--settings` block and are spawn-only, while this one has
     * BOTH a spawn form (`--thinking` / `--max-thinking-tokens` /
     * `--thinking-display`) and a live form (the `set_max_thinking_tokens`
     * control_request), so a change reaches running sessions. The one
     * exception is the return to "Claude Code decides", which has no wire
     * form at all and lands as a deferred restart — exactly like turning a
     * prompt override off (docs/specs/prompt-tool-overrides.md).
     */
    "claudeThinking": ClaudeThinking;

    /**
     * DefaultThreadEnvMode seeds the workspace mode for new draft threads.
     * Accepts "local" or "worktree"; unknown values fall back to "local"
     * when settings are loaded.
     */
    "defaultThreadEnvMode": string;

    /**
     * WorktreeBranchPrefix is prepended to auto-generated temporary and
     * semantic worktree branch names. It is intentionally flat (default
     * "ao-") rather than namespace-like ("ao/") so generated branches
     * read like normal feature branches.
     */
    "worktreeBranchPrefix": string;

    /**
     * PaneDensity controls the minimum workspace pane width before the pane
     * host starts horizontal scrolling. One of {"compact", "comfortable",
     * "spacious"}.
     */
    "paneDensity": string;

    /**
     * ActivityRunDefault is the starting state for a run of consecutive
     * tool/thinking rows in the transcript. One of {"expanded",
     * "collapsed"}. Applies to every run the user has not explicitly
     * toggled, including the live one -- with "collapsed" a streaming run
     * shows as a chip with counts ticking until opened.
     */
    "activityRunDefault": string;

    /**
     * ActivityRunWindowRows is how many of a run's newest rows stay mounted.
     * Sized to overfill the run's height cap so its tail always has content
     * below the fold; older rows mount on demand behind an "N earlier" line.
     */
    "activityRunWindowRows": number;

    /**
     * TextGenerationProvider selects which CLI drives non-chat text
     * generation (commit messages today; PR bodies and thread titles
     * eventually). Mirrors t3-code's RoutingTextGeneration: one of
     * {"codex", "claude"}. Empty falls through to the default at the
     * validation layer.
     */
    "textGenerationProvider": string;

    /**
     * TextGenerationModel is the model id the text-generation CLI uses.
     * Empty string means "use the per-provider default" (codex ->
     * gpt-5.6-luna, claude -> claude-haiku-4-5). We avoid forcing a
     * concrete default on the field itself because the right model
     * depends on which provider is selected, and a cross-provider
     * default would be wrong half the time.
     */
    "textGenerationModel": string;

    /**
     * TextGenerationReasoningEffort controls the reasoning budget the
     * text-generation CLI spends. Mirrors the provider-specific reasoning
     * effort enum. Default is "low" — commit/PR message generation benefits
     * more from speed than from heavy reasoning.
     */
    "textGenerationReasoningEffort": string;

    /**
     * CommitMessageStyle selects the phrasing guidance generated commit
     * messages follow: "conventional" (Conventional Commits, the
     * default), "repo" (match the repository's recent commit subjects),
     * or "custom" (follow CommitMessageStyleCustom). Mirrors t3-code's
     * source-control writing-style options.
     */
    "commitMessageStyle": string;

    /**
     * CommitMessageStyleCustom holds the user's free-text style
     * instructions, consumed only when CommitMessageStyle == "custom".
     * Trimmed and length-capped at validation.
     */
    "commitMessageStyleCustom": string;

    /**
     * Auto-compact thresholds, percent-of-window. Per provider per tier;
     * model-agnostic by design (the user picks model + active window via
     * the composer's pickers, not via Settings). At session start the
     * resolved threshold is `thread.AutoCompactPercent || settings.<...>`,
     * so editing the slider applies live to the next turn on existing
     * threads unless the user has set a per-thread override.
     * 
     * Range 1..90; load-time sanitization clamps out-of-range values to
     * the default (90) rather than rejecting the file.
     */
    "claudeAutoCompactStandardPercent": number;
    "claudeAutoCompactExtendedPercent": number;
    "codexAutoCompactStandardPercent": number;
    "codexAutoCompactExtendedPercent": number;

    /**
     * Observability — all opt-in. Empty/false defaults leave the app quiet.
     * 
     * SECURITY NOTE: this file is stored on disk in plaintext and is
     * read/written without any encryption. settings.json itself lands
     * at 0600 (the default os.CreateTemp picks for the temp file we
     * rename in over the destination), and the parent directory is
     * created at 0700 since this struct now persists per-launch tokens.
     * Even with restrictive perms, anything that could reasonably be
     * called a long-lived secret (API keys, OAuth refresh tokens, user
     * credentials) does NOT belong here: this file lives in a
     * user-visible config dir and may be swept into cloud backup tools
     * without the user realising. Put long-lived secrets in the OS
     * keychain via a dedicated package and keep this struct for
     * preferences plus per-launch bootstrap material only.
     */
    "observabilityTracingEnabled": boolean;
    "observabilityOtlpEndpoint": string;
    "observabilityEventLogEnabled": boolean;

    /**
     * Network groups LAN-bind preferences. Default zero value keeps
     * the transport on loopback; flipping BindAll triggers a
     * transport-server rebind to 0.0.0.0 without restarting the app.
     */
    "network": NetworkSettings;

    /**
     * Editor holds the open-in-editor preferences. Default zero value
     * lets internal/editor pick the best available editor via catalog
     * priority; setting Editor.Preference pins a specific one even
     * when later WSL detection finds a higher-priority option.
     */
    "editor": EditorSettings;

    /**
     * Retention controls the background TTL sweep. Default
     * Retention.Days = 30 cleans threads, dated provider-event logs,
     * and bug-report bookmark files older than the window. 0 disables.
     */
    "retention": RetentionSettings;

    /**
     * BackgroundGitFetch enables the periodic `git fetch` the app runs
     * for the repositories behind the sidebar's projects, so ahead/behind
     * counts reflect the remote instead of freezing at the user's last
     * manual fetch. Default true; one fetch per repository per
     * git.FetchStaleWindow, origin only, never --prune.
     * 
     * Turn it off for a metered or VPN-gated connection, or for a
     * monorepo whose fetch is expensive. Off means the counts are only
     * as fresh as the last explicit fetch/pull/prune — nothing else
     * changes. See app_git_background_fetch.go for the cadence.
     */
    "backgroundGitFetch": boolean;

    /**
     * GitLabSelfHostedHosts is the user's allowlist of self-hosted
     * GitLab hostnames (bare hosts, e.g. "gitlab.mycompany.com").
     * Origin URLs whose host matches an entry classify as the "gitlab"
     * forge, enabling the Ship Changes wizard, MR labels, and the
     * `glab` CLI integration. `gitlab.com` does not need to be listed;
     * it is recognised by literal hostname match. Entries are stored
     * lowercase, deduped, and stripped of scheme/path on write.
     */
    "gitlabSelfHostedHosts"?: string[];

    /**
     * RemoteEndpoints stores the user's `--connect` targets: remote-
     * hosted backends the desktop binary can attach to instead of
     * booting a local transport. Persisted as a flat list keyed by
     * stable IDs so the settings UI can rename / re-order without
     * disturbing the connect commands the user has already shared.
     * 
     * SECURITY NOTE: this list contains ephemeral session tokens. They
     * are stored in plaintext alongside settings.json (file lands at
     * 0600, parent dir at 0700). That matches the threat model
     * documented above — settings.json must not contain anything more
     * sensitive than what a local-process attacker could already read
     * out of running webviews. If the remote endpoints' tokens ever
     * become long-lived bearer tokens, move this field to a
     * keychain-backed store and remove the JSON persistence path.
     */
    "remoteEndpoints"?: RemoteEndpoint[];

    /**
     * ProjectSortMode controls sidebar project ordering. One of
     * {"lastActivity", "createdAt", "manual"}. Persisted here rather
     * than in the webview's localStorage because localStorage is
     * ephemeral on some platforms (WebKit2GTK / WSL2).
     */
    "projectSortMode": string;

    /**
     * UsagePeriod is the selected time period for the usage surfaces
     * (sidebar usage footer + usage modal). One of {"day", "week",
     * "month", "all"} — calendar periods, not rolling windows. Same
     * persistence rationale as ProjectSortMode.
     */
    "usagePeriod": string;

    /**
     * The composer's working-indicator knobs. Two independent axes —
     * the WORD beside the spinner and the sprite that animates — plus the
     * per-axis curation lists.
     * 
     * SpinnerVerbsEnabled turns the rotating verb ("Deliberating…",
     * "Reticulating…") on. Default TRUE, and therefore present in
     * DefaultSettings: the verbs are what the indicator has always shown,
     * so an absent key in every settings file that predates this must read
     * as on. Contrast ClaudeTUIEnabled, whose default is the zero value
     * and which stays out of DefaultSettings for exactly the mirrored
     * reason.
     */
    "spinnerVerbsEnabled": boolean;

    /**
     * SpinnerAnimationsEnabled turns the animated sprite on. Default
     * false (zero value, so it stays out of DefaultSettings by
     * construction): motion beside the composer is opt-in, and a user who
     * upgrades into this feature should not find their indicator moving
     * unasked.
     */
    "spinnerAnimationsEnabled"?: boolean;

    /**
     * SpinnerCustomVerbs are the user's own verbs, added to the pool the
     * indicator draws from. Trimmed and deduped; bounds and the
     * reject-don't-truncate rule live in spinner.go.
     */
    "spinnerCustomVerbs"?: string[];

    /**
     * SpinnerBuiltinVerbsDisabled removes the shipped verbs from the pool,
     * leaving only SpinnerCustomVerbs. Zero-value default: the built-ins
     * are what the indicator shows today.
     */
    "spinnerBuiltinVerbsDisabled"?: boolean;

    /**
     * SpinnerDisabledAnimations lists the animation ids the user
     * UNCHECKED from the random pool. An EXCLUSION list, not a selection:
     * a sprite dropped into <configDir>/spinners tomorrow, or one a later
     * app version bundles, joins the pool automatically instead of staying
     * invisible until someone goes and ticks it.
     */
    "spinnerDisabledAnimations"?: string[];

    /**
     * SpinnerCompactionAnimation pins one sprite to auto-compaction, which
     * is the one moment the indicator means something specific rather than
     * "working". "" means never chosen and resolves to the default;
     * "none" is the explicit choice of nothing; anything else is an
     * animation id. Whether that id still resolves is the frontend's
     * question — this package cannot see which sprites exist, and the
     * default sprite for "" is the frontend's to name (catalog.ts), so no
     * id is ever baked in here.
     */
    "spinnerCompactionAnimation"?: string;

    /**
     * WorkflowPaused is the global workflow kill switch: while set, no
     * workflow phase starts anywhere and in-flight turns finish. It is
     * persisted so a paused engine stays paused across a restart.
     */
    "workflowPaused": boolean;

    /**
     * KeepAwakeEnabled is the master switch for the OS sleep inhibitor
     * (internal/power). While set, the machine does not idle-sleep, so a
     * long unattended turn is not cut off by a suspend.
     * 
     * Deliberately absent from DefaultSettings, the ClaudeTUIEnabled
     * pattern: the default is the Go zero value, false. Holding a system
     * power assertion is the kind of thing a user must ask for, and every
     * settings file that predates this key must read as "off" rather than
     * silently start pinning the machine awake after an upgrade.
     * Defaulting it true would also invert writeSparse — which persists
     * only what differs from DefaultSettings — and make `false` the value
     * that survives a write while `true` was dropped.
     */
    "keepAwakeEnabled": boolean;

    /**
     * KeepAwakeScreen additionally keeps the DISPLAY on while
     * KeepAwakeEnabled is set. With it off, only system sleep is blocked
     * and the screen may blank and lock normally. Meaningless on its own —
     * the master switch is what decides whether anything is held at all.
     * 
     * Default TRUE, and therefore present in DefaultSettings (the mirror
     * of KeepAwakeEnabled, and the same reasoning as SpinnerVerbsEnabled):
     * "keep awake" colloquially means the screen stays up, so the axis
     * starts at the meaning of the phrase and the user narrows it. An
     * absent key must read as on, which only DefaultSettings can do.
     */
    "keepAwakeScreen": boolean;

    /**
     * Window stores the desktop window placement (position, size, and
     * maximized/fullscreen state) so the app reopens where it was last
     * closed. Owned by the Go side, not the frontend — written from
     * window move/resize events, never through the Settings UI. The zero
     * value (Valid=false) means "never saved" and the window centers.
     * Not used by the WSL/Windows launcher, which is a separate window in
     * a separate coordinate space and persists to its own window.json.
     */
    "window": windowgeom$0.Geometry;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("timestampFormat" in $$source)) {
            this["timestampFormat"] = "";
        }
        if (!("sansFont" in $$source)) {
            this["sansFont"] = "";
        }
        if (!("monoFont" in $$source)) {
            this["monoFont"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("recentWorkspaces" in $$source)) {
            this["recentWorkspaces"] = [];
        }
        if (!("diffWordWrap" in $$source)) {
            this["diffWordWrap"] = false;
        }
        if (!("collapseDiffPreviews" in $$source)) {
            this["collapseDiffPreviews"] = false;
        }
        if (!("streamingEnabled" in $$source)) {
            this["streamingEnabled"] = false;
        }
        if (!("lowPowerMode" in $$source)) {
            this["lowPowerMode"] = false;
        }
        if (!("browserEnabled" in $$source)) {
            this["browserEnabled"] = false;
        }
        if (!("browserShowWindow" in $$source)) {
            this["browserShowWindow"] = false;
        }
        if (!("browserPersistSiteData" in $$source)) {
            this["browserPersistSiteData"] = false;
        }
        if (!("confirmArchive" in $$source)) {
            this["confirmArchive"] = false;
        }
        if (!("confirmDelete" in $$source)) {
            this["confirmDelete"] = false;
        }
        if (!("claudeBinaryPath" in $$source)) {
            this["claudeBinaryPath"] = "";
        }
        if (!("codexBinaryPath" in $$source)) {
            this["codexBinaryPath"] = "";
        }
        if (!("claudeEnabled" in $$source)) {
            this["claudeEnabled"] = false;
        }
        if (!("codexEnabled" in $$source)) {
            this["codexEnabled"] = false;
        }
        if (!("claudeTuiEnabled" in $$source)) {
            this["claudeTuiEnabled"] = false;
        }
        if (!("claudeCrossSession" in $$source)) {
            this["claudeCrossSession"] = (new ClaudeCrossSession());
        }
        if (!("claudeSubagentLimits" in $$source)) {
            this["claudeSubagentLimits"] = (new ClaudeSubagentLimits());
        }
        if (!("claudeThinking" in $$source)) {
            this["claudeThinking"] = (new ClaudeThinking());
        }
        if (!("defaultThreadEnvMode" in $$source)) {
            this["defaultThreadEnvMode"] = "";
        }
        if (!("worktreeBranchPrefix" in $$source)) {
            this["worktreeBranchPrefix"] = "";
        }
        if (!("paneDensity" in $$source)) {
            this["paneDensity"] = "";
        }
        if (!("activityRunDefault" in $$source)) {
            this["activityRunDefault"] = "";
        }
        if (!("activityRunWindowRows" in $$source)) {
            this["activityRunWindowRows"] = 0;
        }
        if (!("textGenerationProvider" in $$source)) {
            this["textGenerationProvider"] = "";
        }
        if (!("textGenerationModel" in $$source)) {
            this["textGenerationModel"] = "";
        }
        if (!("textGenerationReasoningEffort" in $$source)) {
            this["textGenerationReasoningEffort"] = "";
        }
        if (!("commitMessageStyle" in $$source)) {
            this["commitMessageStyle"] = "";
        }
        if (!("commitMessageStyleCustom" in $$source)) {
            this["commitMessageStyleCustom"] = "";
        }
        if (!("claudeAutoCompactStandardPercent" in $$source)) {
            this["claudeAutoCompactStandardPercent"] = 0;
        }
        if (!("claudeAutoCompactExtendedPercent" in $$source)) {
            this["claudeAutoCompactExtendedPercent"] = 0;
        }
        if (!("codexAutoCompactStandardPercent" in $$source)) {
            this["codexAutoCompactStandardPercent"] = 0;
        }
        if (!("codexAutoCompactExtendedPercent" in $$source)) {
            this["codexAutoCompactExtendedPercent"] = 0;
        }
        if (!("observabilityTracingEnabled" in $$source)) {
            this["observabilityTracingEnabled"] = false;
        }
        if (!("observabilityOtlpEndpoint" in $$source)) {
            this["observabilityOtlpEndpoint"] = "";
        }
        if (!("observabilityEventLogEnabled" in $$source)) {
            this["observabilityEventLogEnabled"] = false;
        }
        if (!("network" in $$source)) {
            this["network"] = (new NetworkSettings());
        }
        if (!("editor" in $$source)) {
            this["editor"] = (new EditorSettings());
        }
        if (!("retention" in $$source)) {
            this["retention"] = (new RetentionSettings());
        }
        if (!("backgroundGitFetch" in $$source)) {
            this["backgroundGitFetch"] = false;
        }
        if (!("projectSortMode" in $$source)) {
            this["projectSortMode"] = "";
        }
        if (!("usagePeriod" in $$source)) {
            this["usagePeriod"] = "";
        }
        if (!("spinnerVerbsEnabled" in $$source)) {
            this["spinnerVerbsEnabled"] = false;
        }
        if (!("workflowPaused" in $$source)) {
            this["workflowPaused"] = false;
        }
        if (!("keepAwakeEnabled" in $$source)) {
            this["keepAwakeEnabled"] = false;
        }
        if (!("keepAwakeScreen" in $$source)) {
            this["keepAwakeScreen"] = false;
        }
        if (!("window" in $$source)) {
            this["window"] = (new windowgeom$0.Geometry());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField5_0 = $$createType0;
        const $$createField21_0 = $$createType0;
        const $$createField22_0 = $$createType0;
        const $$createField23_0 = $$createType2;
        const $$createField24_0 = $$createType2;
        const $$createField25_0 = $$createType4;
        const $$createField26_0 = $$createType4;
        const $$createField27_0 = $$createType0;
        const $$createField28_0 = $$createType0;
        const $$createField31_0 = $$createType5;
        const $$createField32_0 = $$createType6;
        const $$createField34_0 = $$createType7;
        const $$createField52_0 = $$createType8;
        const $$createField53_0 = $$createType9;
        const $$createField54_0 = $$createType10;
        const $$createField56_0 = $$createType0;
        const $$createField57_0 = $$createType12;
        const $$createField62_0 = $$createType0;
        const $$createField64_0 = $$createType0;
        const $$createField69_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentWorkspaces" in $$parsedSource) {
            $$parsedSource["recentWorkspaces"] = $$createField5_0($$parsedSource["recentWorkspaces"]);
        }
        if ("claudeHiddenModels" in $$parsedSource) {
            $$parsedSource["claudeHiddenModels"] = $$createField21_0($$parsedSource["claudeHiddenModels"]);
        }
        if ("codexHiddenModels" in $$parsedSource) {
            $$parsedSource["codexHiddenModels"] = $$createField22_0($$parsedSource["codexHiddenModels"]);
        }
        if ("claudeCustomEnv" in $$parsedSource) {
            $$parsedSource["claudeCustomEnv"] = $$createField23_0($$parsedSource["claudeCustomEnv"]);
        }
        if ("codexCustomEnv" in $$parsedSource) {
            $$parsedSource["codexCustomEnv"] = $$createField24_0($$parsedSource["codexCustomEnv"]);
        }
        if ("claudePromptOverrides" in $$parsedSource) {
            $$parsedSource["claudePromptOverrides"] = $$createField25_0($$parsedSource["claudePromptOverrides"]);
        }
        if ("codexPromptOverrides" in $$parsedSource) {
            $$parsedSource["codexPromptOverrides"] = $$createField26_0($$parsedSource["codexPromptOverrides"]);
        }
        if ("claudeDisabledTools" in $$parsedSource) {
            $$parsedSource["claudeDisabledTools"] = $$createField27_0($$parsedSource["claudeDisabledTools"]);
        }
        if ("codexDisabledTools" in $$parsedSource) {
            $$parsedSource["codexDisabledTools"] = $$createField28_0($$parsedSource["codexDisabledTools"]);
        }
        if ("claudeCrossSession" in $$parsedSource) {
            $$parsedSource["claudeCrossSession"] = $$createField31_0($$parsedSource["claudeCrossSession"]);
        }
        if ("claudeSubagentLimits" in $$parsedSource) {
            $$parsedSource["claudeSubagentLimits"] = $$createField32_0($$parsedSource["claudeSubagentLimits"]);
        }
        if ("claudeThinking" in $$parsedSource) {
            $$parsedSource["claudeThinking"] = $$createField34_0($$parsedSource["claudeThinking"]);
        }
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField52_0($$parsedSource["network"]);
        }
        if ("editor" in $$parsedSource) {
            $$parsedSource["editor"] = $$createField53_0($$parsedSource["editor"]);
        }
        if ("retention" in $$parsedSource) {
            $$parsedSource["retention"] = $$createField54_0($$parsedSource["retention"]);
        }
        if ("gitlabSelfHostedHosts" in $$parsedSource) {
            $$parsedSource["gitlabSelfHostedHosts"] = $$createField56_0($$parsedSource["gitlabSelfHostedHosts"]);
        }
        if ("remoteEndpoints" in $$parsedSource) {
            $$parsedSource["remoteEndpoints"] = $$createField57_0($$parsedSource["remoteEndpoints"]);
        }
        if ("spinnerCustomVerbs" in $$parsedSource) {
            $$parsedSource["spinnerCustomVerbs"] = $$createField62_0($$parsedSource["spinnerCustomVerbs"]);
        }
        if ("spinnerDisabledAnimations" in $$parsedSource) {
            $$parsedSource["spinnerDisabledAnimations"] = $$createField64_0($$parsedSource["spinnerDisabledAnimations"]);
        }
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField69_0($$parsedSource["window"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ProviderEnvVar.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PromptOverride.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ClaudeCrossSession.createFrom;
const $$createType6 = ClaudeSubagentLimits.createFrom;
const $$createType7 = ClaudeThinking.createFrom;
const $$createType8 = NetworkSettings.createFrom;
const $$createType9 = EditorSettings.createFrom;
const $$createType10 = RetentionSettings.createFrom;
const $$createType11 = RemoteEndpoint.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = windowgeom$0.Geometry.createFrom;
