// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings holds all user-configurable preferences.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("timestampFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestampFormat"] = "";
        }
        if (!("defaultProvider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultProvider"] = "";
        }
        if (!("defaultModelClaude" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultModelClaude"] = "";
        }
        if (!("defaultModelCodex" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultModelCodex"] = "";
        }
        if (!("recentWorkspaces" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["recentWorkspaces"] = [];
        }
        if (!("diffWordWrap" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["diffWordWrap"] = false;
        }
        if (!("streamingEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["streamingEnabled"] = false;
        }
        if (!("confirmArchive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmArchive"] = false;
        }
        if (!("confirmDelete" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmDelete"] = false;
        }
        if (!("claudeBinaryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["claudeBinaryPath"] = "";
        }
        if (!("codexBinaryPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codexBinaryPath"] = "";
        }
        if (!("claudeEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["claudeEnabled"] = false;
        }
        if (!("codexEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["codexEnabled"] = false;
        }
        if (!("defaultRuntimeMode" in $$source)) {
            /**
             * DefaultRuntimeMode is the three-tier approval axis applied to every
             * new thread when the user hasn't picked a different mode at creation
             * time. Accepts "approval-required", "auto-accept-edits", or
             * "full-access"; unknown values are coerced to "full-access" at the
             * provider-mode chokepoint so a stale settings file can't lock the
             * app into an invalid mode.
             * @member
             * @type {string}
             */
            this["defaultRuntimeMode"] = "";
        }
        if (!("observabilityTracingEnabled" in $$source)) {
            /**
             * Observability — all opt-in. Empty/false defaults leave the app quiet.
             * 
             * SECURITY NOTE: this file is stored on disk in plaintext and is
             * read/written without any encryption. That is fine for the fields
             * we currently persist — an OTLP endpoint is not a secret (it's a
             * gRPC/HTTP URL the user already exposes to every app running on
             * their machine). If a future field stores anything that could
             * reasonably be called a secret (API keys, bearer tokens, user
             * credentials), do NOT put it here: settings.json is written with
             * 0644 permissions, landed in a user-visible config dir, and may
             * be synced to cloud backup without the user realising. Put secrets
             * in the OS keychain via a dedicated package and keep this struct
             * for non-sensitive preferences only.
             * @member
             * @type {boolean}
             */
            this["observabilityTracingEnabled"] = false;
        }
        if (!("observabilityOtlpEndpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["observabilityOtlpEndpoint"] = "";
        }
        if (!("observabilityEventLogEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["observabilityEventLogEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentWorkspaces" in $$parsedSource) {
            $$parsedSource["recentWorkspaces"] = $$createField5_0($$parsedSource["recentWorkspaces"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
