// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * QueuedItem is the wire-side projection of a triage QueuedFlushItem,
 * used by the frontend to mirror the backend's per-thread queue. The
 * wire shape mirrors SendMessageOptions's data fields plus the
 * frontend-allocated id and stamped enqueuedAt — together they're
 * enough for both the queue overlay rendering and the UP-arrow
 * retract path that re-hydrates the composer draft.
 * 
 * AttachmentIDs (not full Attachment records) ride the wire because
 * the frontend already has the full records in its attachment store
 * keyed by id; cross-wire transmission would duplicate bytes for no
 * gain. Plan refs are passed by value because they're tiny and
 * already used as plain JSON across the existing send path.
 */
export class QueuedItem {
    "id": string;
    "threadId": string;
    "message": string;
    "attachmentIds"?: string[];
    "sourceProposedPlan"?: store$0.ProposedPlanSourceRef | null;
    "revisionSourceProposedPlan"?: store$0.ProposedPlanSourceRef | null;
    "revisionSourceCommentIds"?: string[];
    "revisionSourceDiffReview"?: store$0.DiffReviewSourceRef | null;
    "revisionSourceDiffCommentIds"?: string[];
    "enqueuedAt": number;

    /** Creates a new QueuedItem instance. */
    constructor($$source: Partial<QueuedItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("threadId" in $$source)) {
            this["threadId"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("enqueuedAt" in $$source)) {
            this["enqueuedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueuedItem instance from a string or object.
     */
    static createFrom($$source: any = {}): QueuedItem {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType4;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachmentIds" in $$parsedSource) {
            $$parsedSource["attachmentIds"] = $$createField3_0($$parsedSource["attachmentIds"]);
        }
        if ("sourceProposedPlan" in $$parsedSource) {
            $$parsedSource["sourceProposedPlan"] = $$createField4_0($$parsedSource["sourceProposedPlan"]);
        }
        if ("revisionSourceProposedPlan" in $$parsedSource) {
            $$parsedSource["revisionSourceProposedPlan"] = $$createField5_0($$parsedSource["revisionSourceProposedPlan"]);
        }
        if ("revisionSourceCommentIds" in $$parsedSource) {
            $$parsedSource["revisionSourceCommentIds"] = $$createField6_0($$parsedSource["revisionSourceCommentIds"]);
        }
        if ("revisionSourceDiffReview" in $$parsedSource) {
            $$parsedSource["revisionSourceDiffReview"] = $$createField7_0($$parsedSource["revisionSourceDiffReview"]);
        }
        if ("revisionSourceDiffCommentIds" in $$parsedSource) {
            $$parsedSource["revisionSourceDiffCommentIds"] = $$createField8_0($$parsedSource["revisionSourceDiffCommentIds"]);
        }
        return new QueuedItem($$parsedSource as Partial<QueuedItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = store$0.ProposedPlanSourceRef.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = store$0.DiffReviewSourceRef.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
