// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveThread(arg1) {
  return window['go']['main']['App']['ArchiveThread'](arg1);
}

export function CreateThread(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateThread'](arg1, arg2, arg3);
}

export function DeleteThread(arg1) {
  return window['go']['main']['App']['DeleteThread'](arg1);
}

export function GetPayloadData(arg1) {
  return window['go']['main']['App']['GetPayloadData'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetThread(arg1) {
  return window['go']['main']['App']['GetThread'](arg1);
}

export function InterruptTurn(arg1) {
  return window['go']['main']['App']['InterruptTurn'](arg1);
}

export function ListItems(arg1) {
  return window['go']['main']['App']['ListItems'](arg1);
}

export function ListPayloadMetas(arg1) {
  return window['go']['main']['App']['ListPayloadMetas'](arg1);
}

export function ListThreads() {
  return window['go']['main']['App']['ListThreads']();
}

export function RenameThread(arg1, arg2) {
  return window['go']['main']['App']['RenameThread'](arg1, arg2);
}

export function RespondToApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondToApproval'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}
