// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function ArchiveThread(arg1:string):Promise<void>;

export function CreateThread(arg1:string,arg2:string,arg3:string):Promise<store.Thread>;

export function DeleteThread(arg1:string):Promise<void>;

export function GetPayloadData(arg1:string):Promise<string>;

export function GetSettings():Promise<Record<string, any>>;

export function GetThread(arg1:string):Promise<store.Thread>;

export function InterruptTurn(arg1:string):Promise<void>;

export function ListItems(arg1:string):Promise<Array<store.Item>>;

export function ListPayloadMetas(arg1:string):Promise<Array<store.PayloadMeta>>;

export function ListThreads():Promise<Array<store.Thread>>;

export function RenameThread(arg1:string,arg2:string):Promise<void>;

export function RespondToApproval(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StartSession(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;
