// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nearby$0 from "../nearby/models.js";

/**
 * Config is one complete desired native-listener generation. Generation orders
 * listener replacement and rejects reports from an earlier configuration.
 * ScanID is independent: it correlates one bounded discovery request without
 * allowing a later scan to replace the result a prior caller is consuming.
 */
export class Config {
    "generation": number;
    "pairingOpen": boolean;
    "enabled": boolean;
    "backendId": string;
    "name": string;
    "target": string;
    "scanId": number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("pairingOpen" in $$source)) {
            this["pairingOpen"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("backendId" in $$source)) {
            this["backendId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("scanId" in $$source)) {
            this["scanId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * State belongs to one Config generation. Reject a stale generation before
 * publishing Addresses or Error. Nearby completes a discovery request only
 * when ScanID also matches that pending request; listener updates need no scan.
 */
export class State {
    "generation": number;
    "addresses": string[];
    "error": string;
    "scanId": number;
    "nearby": nearby$0.Host[];

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("generation" in $$source)) {
            this["generation"] = 0;
        }
        if (!("addresses" in $$source)) {
            this["addresses"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("scanId" in $$source)) {
            this["scanId"] = 0;
        }
        if (!("nearby" in $$source)) {
            this["nearby"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField1_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addresses" in $$parsedSource) {
            $$parsedSource["addresses"] = $$createField1_0($$parsedSource["addresses"]);
        }
        if ("nearby" in $$parsedSource) {
            $$parsedSource["nearby"] = $$createField4_0($$parsedSource["nearby"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = nearby$0.Host.createFrom;
const $$createType2 = $Create.Array($$createType1);
