// gen-chroma-css emits the CSS rules required by the `ch-`-prefixed
// classes that goldmark-highlighting writes into fenced-code output.
//
// Run via `go run ./cmd/gen-chroma-css`; the Makefile wires it into
// `build` and `check` so the generated files stay in lockstep with the
// Chroma style tables on every commit.
//
// Two files, one per theme, both under frontend/src/styles/. The light
// palette is rewritten so every rule is scoped under `html.light` so
// both palettes can coexist in one stylesheet and toggling the `light`
// class on <html> swaps the code-block colors CSS-only. The prefix
// must match the runtime renderer (see internal/highlight/markdown.go)
// so the emitted classes actually hit.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

type target struct {
	style    string
	outFile  string
	scopedBy string // optional CSS scope prefix (e.g. "html.light") added to every rule
}

// classPrefix must stay in sync with internal/highlight/markdown.go's
// chromahtml.ClassPrefix("ch-"). Bumping one without the other breaks
// highlighting silently (classes render but CSS doesn't match).
const classPrefix = "ch-"

var (
	// commentRE matches the `/* name */ ` leader Chroma emits before each
	// rule so we can keep it out of the selector when rescoping.
	commentRE = regexp.MustCompile(`^(\s*/\*[^*]*\*/\s*)`)
)

func main() {
	targets := []target{
		{style: "github-dark", outFile: "frontend/src/styles/chroma-dark.css"},
		{style: "github", outFile: "frontend/src/styles/chroma-light.css", scopedBy: "html.light"},
	}

	for _, t := range targets {
		style := styles.Get(t.style)
		if style == nil {
			fmt.Fprintf(os.Stderr, "gen-chroma-css: unknown Chroma style %q\n", t.style)
			os.Exit(1)
		}
		formatter := html.New(html.WithClasses(true), html.ClassPrefix(classPrefix))

		var buf bytes.Buffer
		if err := formatter.WriteCSS(&buf, style); err != nil {
			fmt.Fprintf(os.Stderr, "gen-chroma-css: write css %s: %v\n", t.outFile, err)
			os.Exit(1)
		}

		output := buf.String()
		if t.scopedBy != "" {
			output = rescope(output, t.scopedBy)
		}

		if err := os.MkdirAll(filepath.Dir(t.outFile), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "gen-chroma-css: mkdir %s: %v\n", filepath.Dir(t.outFile), err)
			os.Exit(1)
		}
		header := fmt.Sprintf("/* Generated by cmd/gen-chroma-css from Chroma style %q. DO NOT EDIT. */\n", t.style)
		if err := os.WriteFile(t.outFile, []byte(header+output), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "gen-chroma-css: write %s: %v\n", t.outFile, err)
			os.Exit(1)
		}
		fmt.Printf("gen-chroma-css: wrote %s (style=%s scope=%q)\n", t.outFile, t.style, t.scopedBy)
	}
}

// rescope prefixes every selector in the generated CSS with the scope.
// Each rule Chroma emits sits on its own line in the form
//   /* Name */ .ch-X { decls } [newline]
// so we can split line-by-line, preserve the leading comment, and
// prepend the scope to the selector tokens.
func rescope(css, scope string) string {
	var out strings.Builder
	for _, line := range strings.Split(css, "\n") {
		if strings.TrimSpace(line) == "" {
			out.WriteString(line)
			out.WriteString("\n")
			continue
		}
		leader := ""
		rest := line
		if m := commentRE.FindStringIndex(rest); m != nil {
			leader = rest[:m[1]]
			rest = rest[m[1]:]
		}
		braceAt := strings.Index(rest, "{")
		if braceAt < 0 {
			// Rule without braces (shouldn't happen in Chroma output); keep as-is.
			out.WriteString(line)
			out.WriteString("\n")
			continue
		}
		selectors := strings.TrimSpace(rest[:braceAt])
		body := rest[braceAt:]
		scoped := make([]string, 0, 2)
		for _, sel := range strings.Split(selectors, ",") {
			sel = strings.TrimSpace(sel)
			if sel == "" {
				continue
			}
			scoped = append(scoped, scope+" "+sel)
		}
		out.WriteString(leader)
		out.WriteString(strings.Join(scoped, ", "))
		out.WriteString(" ")
		out.WriteString(body)
		out.WriteString("\n")
	}
	return out.String()
}
